### ISSUE TITLE
Integrating with gh-ost

### ISSUE THREAD

**Issue by shlomi-noach** [skeema/skeema#1]
From `README.md`: 

> Integration with gh-ost is more challenging, because its recommended execution mode requires passing it a replica, not the master

Nonetheless `gh-ost` supports pure-master migrations, with the requirement that it uses `ROW` based replication.

I'm happy to assist in making the ~~introductions~~ integration.

**Comment by evanelias** [comment]
Awesome, thanks Shlomi! There are a few ways to approach this, of varying complexity. I'm thinking I may add one or two small features that help in the short-term, and have tighter/cleaner integration as a goal in the medium to long term.

A few options for supporting connect-to-replica mode in Skeema:

### Point alter-wrapper to a custom script
Skeema's `alter-wrapper` option already supports executing any command line for ALTER operations, with replacement for certain variables like {HOST}, which points at a master. In theory, one could write a small custom script which asks service discovery "What is the preferred replica of {HOST} for doing gh-ost operations?" -- and then executes gh-ost with that discovered replica passed in, rather than using {HOST} directly.

This is already supported today, without any changes in Skeema. But since it requires custom scripting on behalf of the user/DBA, it's not very user-friendly. Also it's hard to come up with an example for the docs, since service discovery systems vary, especially in terms of how you would "tag" a particular replica as being preferred for gh-ost.

### Add a new placeholder variable for alter-wrapper
In addition to {HOST}, Skeema could support {TARGET-REPLICA} which just gets passed as-is from options (target-replica in a .skeema option file, or --target-replica on the CLI). This feels slightly hacky, since it would be a Skeema option that "doesn't do anything" on its own. But it would be very easy to implement, just a few lines of code.

This wouldn't really help with gh-ost's `--throttle-control-replica` though, unless a second new Skeema option is added for that too.

### Real integration
Eventually we could add features that make integration with specific OSC tools (at minimum pt-osc and gh-ost) easier than the current alter-wrapper solution. For gh-ost in particular, since it's written in Go, there's an opportunity for very tight integration.

I figure working on that auto-GTID-cleanup FR for gh-ost will provide me with a good opportunity to become more familiar with gh-ost's codebase. Once I'm more knowledgeable on gh-ost, I'd love to collaborate on how best to support integration -- probably in a few months? Of course, feel free to propose something sooner, if you start playing with Skeema and see some good integration points.

That reminds me, I still need to create a CONTRIBUTING.md etc :)

**Comment by shlomi-noach** [comment]
Re: Go-level integration; the one outstanding issue right now with `gh-ost` is that it feels free to `Fatal()` (i.e. bail out with error code) when it feels like it, and this does not play nice with being _called_ (as opposed to _executed as subprocess_, which is fine) from your own Go app.

**Comment by evanelias** [comment]
Good to know, thanks!

Could be worse -- most of Skeema's logic is in `main` package ;) I intend to move it out at some point so it's actually importable... oh well, at least two main chunks of logic are already in separate modules ([skeema/tengo](http://www.github.com/skeema/tengo) and [skeema/mycli](http://www.github.com/skeema/mycli))

**Comment by shlomi-noach** [comment]
😱

**Comment by dontstopbelieveing** [comment]
I wanted to check on this issue. If I was okay running gh-ost on master (as opposed to the recommended way of running on the replica) can Skeema do this now? Also, does the wrapper provide functionality to add hooks (e.g. JIRA comments, ServiceNow comments etc. etc.  ) but I think that's a question for another thread.

**Comment by evanelias** [comment]
> If I was okay running gh-ost on master (as opposed to the recommended way of running on the replica) can Skeema do this now?

Yes, in theory Skeema already supports this either way (master or replica). It just requires some configuration. If running gh-ost on master, the setup is more straightforward, since you can just pass `--host={HOST}` to gh-ost on the `alter-wrapper` command-line. Or you can run it on a replica, but the setup requires writing a custom wrapper script which interacts with your service discovery system (see "Point alter-wrapper to a custom script" above).

This open issue is more about making it *easier* to use gh-ost in Skeema, by providing tighter integration and/or better documentation. For example, perhaps Skeema could support querying Orchestrator to look up master and replica info to pass to gh-ost, or at least have a doc showing examples of how to configure Skeema + gh-ost + Orchestrator together.

> Also, does the wrapper provide functionality to add hooks (e.g. JIRA comments, ServiceNow comments etc. etc. ) but I think that's a question for another thread.

Skeema's various wrapper options all support passing in any arbitrary command-line. So you can run any custom script, and have it interact with any third-party systems that you want. A few links for more info:
* [alter-wrapper](https://github.com/skeema/skeema/blob/master/doc/options.md#alter-wrapper)
* [ddl-wrapper](https://github.com/skeema/skeema/blob/master/doc/options.md#ddl-wrapper)
* [host-wrapper](https://github.com/skeema/skeema/blob/master/doc/options.md#host-wrapper)
* [schema](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) (if you surround the value with backticks, it is interpreted as a command-line to shell out to)
* [Variable interpolation](https://github.com/skeema/skeema/blob/master/doc/config.md#options-with-variable-interpolation) doc for these options in general

More hooks may be added in the near future, such as pre-push / post-push hooks to facilitate custom behavior such as [loading seed data](https://github.com/skeema/skeema/issues/22#issuecomment-459907251).

**Comment by evanelias** [comment]
I fear this issue is confusing some users, so I am closing it. A number of users have recently expressed the misconception that gh-ost cannot be used with Skeema. (Not your fault at all Shlomi; I think people are not reading enough of the discussion here!)

To be clear to anyone finding this issue in the future: **You can use gh-ost with Skeema.** It works fine, and **always** has been supported, in every single version of Skeema. There’s just no example in the Skeema docs because there are a few different ways to use gh-ost, and the setup depends a bit on your environment. In most cases you will need to write a small wrapper script. If a company needs assistance with this (or any other aspect of Skeema), I am happy to help with company-specific issues via a short paid consulting engagement.
