### ISSUE TITLE
DROP TABLE not permitted

### ISSUE THREAD

**Issue by akuzminsky** [skeema/skeema#10]
skeema refuses to DROP a table even though MySQL account has a DROP privilege.

```
2017-09-04 05:45:32 [ERROR] DROP TABLE not permitted. The affected DDL statement will be skipped. See --help for more information.
/* DROP TABLE `sb_woocommerce_shipping_table_rates`; */
```

```
[root@ip-172-31-37-147 sb]# mysql -e 'SHOW GRANTS FOR CURRENT_USER()'
+----------------------------------------------------------------------------------------------------------------------------------------+
| Grants for root@localhost                                                                                                              |
+----------------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY PASSWORD '****' WITH GRANT OPTION |
| GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by evanelias** [comment]
Thank you for trying out Skeema! This is working as designed though. Skeema considers destructive actions (e.g. dropping tables, dropping columns, lossy changes to column types, etc) to be "unsafe" by default, and won't execute them unless you specifically configure it to do so. That's why it is telling you to `See --help for more information` :) That said, I should make this message clearer to indicate it's because of Skeema's settings, not because of grants.

You can configure unsafe operations to always be executed only in certain environments (e.g. dev), and/or can configure them to be OK depending on the table size (e.g. allow them if the table is under 1GB, or allow them only if the table has no rows).

More docs on this:
* https://github.com/skeema/skeema/blob/master/doc/examples.md#generate-ddl-from-adding-or-removing-files
* https://github.com/skeema/skeema/blob/master/doc/options.md#allow-unsafe
* https://github.com/skeema/skeema/blob/master/doc/options.md#safe-below-size
* https://github.com/skeema/skeema/blob/master/doc/faq.md#destructive-operations-are-prevented-by-default
* https://github.com/skeema/skeema/blob/master/doc/requirements.md#renaming-columns-or-tables
