### ISSUE TITLE
add-environment workflow feedback

### ISSUE THREAD

**Issue by kaihendry** [skeema/skeema#100]
Continuing from https://twitter.com/EvanElias/status/1168732285639831553

Does this look like a good workflow? https://s.natalian.org/2019-09-03/add-env.mp4

Does `skeema pull` pull from all configured environments? I think it's just "production", but I don't have a "production" environment...

In retrospect, I wish I **init**ed from dev. I would prefer to see the diff between folders, since then it would be clear in my mind what is the source and what is the target.

**Comment by evanelias** [comment]
It pulls from the environment you specify, or "production" if you didn't specify anything. All of the commands work this way, they take the environment name as an optional command-line. So if you want to pull from dev, you run `skeema pull dev`. Please see `skeema pull --help`, and again https://github.com/skeema/skeema/blob/master/doc/config.md#specifying-options-via-option-files

> In retrospect, I wish I inited from dev.

It doesn't really matter which one you init from. You could always add-environment dev and then pull from dev. Same result.

> I would prefer to see the diff between folders, since then it would be clear in my mind what is the source and what is the target.

Not sure I follow. In any case, the idea is the filesystem repo represents the *desired state*. If dev has the latest changes, then yes it may make sense to pull from dev. Or make changes directly to files and diff/push to dev. It depends on your preferred workflow. See step 2 in https://github.com/skeema/skeema/blob/master/doc/workflow.md#schema-change-process.

> Does this look like a good workflow? https://s.natalian.org/2019-09-03/add-env.mp4

No, you probably should not have separate environments for each database schema. If you applications presumably have a common notion of "dev", "test", "stage", whatever -- then their schemas do too.

Sorry but I cannot continue to provide support by responding to videos, due to how time-consuming they are.

**Comment by kaihendry** [comment]
Some people like videos, some people don't. No hard feelings.

> No, you probably should not have separate environments for each database schema. If you applications presumably have a common notion of "dev", "test", "stage", whatever -- then their schemas do too.

I don't follow. We have one schema, "bugzilla", but they can are currently do differ between say 
{dev,prod} stages.

https://github.com/unee-t/skeema-experiment/blob/master/bugzilla/.skeema


What should I have done differently?

**Comment by evanelias** [comment]
> We have one schema, "bugzilla"

It seems you have 3 schemas: bugzilla, tmp, unee_t_enterprise. Are you trying to manage all 3 using Skeema, or only manage "bugzilla"? I see you have two levels of directories named "bugzilla" so it seems something is amiss here.

The layout of your repo directories + the setup of your environments will depend entirely on how you setup your MySQL instances and schemas. If you explain which schemas exist and on what master hosts / Aurora clusters, I can recommend a Skeema layout and set of commands to achieve it.

**Comment by kaihendry** [comment]
tmp & unee_t_enterprise databases in my case, I would actually prefer to ignore, but I don't know-how.

They should be removed and cleared out at some point. I'm actually not the DBA, I'm just keen on having better insight and the current state of our application's environment.

Happy to adopt your recommendations.

**Comment by evanelias** [comment]
> tmp & unee_t_enterprise databases in my case, I would actually prefer to ignore, but I don't know how.

There are a few different ways to do this, all covered in the docs. In your use-case my recommendation would be to delete what you have and start fresh, this time running `skeema init` with `--schema bugzilla`. This will cause Skeema to *only* export that one specific schema to the filesystem, into a single "flat" directory, with a .skeema file configuring everything in one file (host, flavor, schema). You can then use `skeema add-environment` to add the additional environments.

You should end up with a single directory with *.sql files and a single .skeema file that looks like this:

```
default-character-set=utf8mb4
default-collation=utf8mb4_unicode_520_ci
schema=bugzilla

[production]
flavor=mysql:5.7
host=auroradb.unee-t.com
port=3306
user=root

[dev]
flavor=mysql:5.7
host=auroradb.dev.unee-t.com
port=3306
user=root

[demo]
flavor=mysql:5.7
host=auroradb.demo.unee-t.com
port=3306
user=root
```

You can also set this up manually, or freely edit the .skeema file to achieve the desired configuration.

> I'm actually not the DBA, I'm just keen on having better insight and the current state of our application's environment.

Does this mean all of your actual schema changes are made outside of Skeema? (in other words, are you saying you won't ever use `skeema push` to actually make schema changes?)

The tool is designed to manage schema changes, and the intended workflow is to have git commits corresponding to each set of changes. Although you can deviate from that and still perhaps find the tool useful in a "pull-only" setup, many things are going to be awkward if so.

> they can & currently do differ between say {dev,prod} stages.

That's fine and expected. You still just want a single directory representing these. Think of how application deploys work:
* the production deployment of your app may be on commit A
* the dev deployment of your app may be on a newer commit, B, which has not yet been deployed to prod
* the master branch of your app's repo could be on an even newer commit, C, which has not yet been deployed anywhere
* Despite being on different *commits/branches*, you still just have one repo storing your application's code, rather than duplicating the application code for each environment

Skeema is an *infrastructure as code* tool; the relationship between your environments and your schema repo is completely analogous to how application code repos work. In other words, the intended workflow looks like this:
* Your databases for different environments may be "on" different commits. Regardless, you still just have one common repo (one directory of *.sql files) representing the desired state.
* At any given time, your master branch in git might have commits (schema changes) that have not yet been deployed.
* Your local working copy (git clone) may have changes that have not yet been committed, which you may diff/push vs dev as needed. and/or you may use git branches to track in-progress work that is not yet ready for prod.
* You can see the differences between the repo and dev by running `skeema diff dev`, and then if you want to "deploy" those changes to dev you run `skeema push dev`. Or you can work in the opposite direction -- if someone manually made changes to dev (outside of Skeema) and you want to bring those changes into the repo, you can run `skeema pull dev` and then commit the changes to git.
* Once a commit is ready for production, you can sanity-check the changes by running `skeema diff production` (or just `skeema diff` since production is the default, just like "master" is the default in git), and then can deploy them using `skeema push production` (or just `skeema push`).

**Comment by kaihendry** [comment]
Thank you for taking the time to explain this really well.

I think I've followed you advice here: https://github.com/unee-t/skeema-experiment where you might find https://github.com/unee-t/skeema-experiment/blob/master/init.sh interesting or not.

Fantastic work.

**Comment by evanelias** [comment]
Looks mostly good, but I still don't understand why you are putting schema names inside of the environment names? This does not provide any benefit, and just makes everything more complicated.

Why not just use `production`, `dev`, and `demo` across both directories? That way,
* If you want to pull both DBs from their respective dev environments: cd to the parent dir (`skeema-experiment`) and run `skeema pull dev`
* If you want to pull just buzilla: cd to `skeema-experiment/bugzilla` and run `skeema pull dev`
* If you want to pull just unte: cd to `skeema-experiment/unte` and run `skeema pull dev`

Ditto with any other skeema command... they are all recursive from the current working directory, and so by combination of working directory + environment name, you already can control what's being targeted. No reason to put the schema name inside the environment...

**Comment by kaihendry** [comment]
unte-dev has a different database host (RDS) to bugzilla-dev. Since I keep the passwords in `~/.skeema`, I need a way of telling them apart. Perhaps there is a smarter way of creating `~/.skeema`? Something based on host so I can keep {dev,demo,prod} names?

**Comment by evanelias** [comment]
Ahhh, I see -- thank you, that totally makes sense now re: different passwords. There actually isn't a better way to solve this yet, but I've just created #101 to track this.
