### ISSUE TITLE
Support for foreign keys

### ISSUE THREAD

**Issue by egtann** [skeema/skeema#11]
I was checking out Skeema and testing it on my DB--looks like a great library, and I'm very interested in the declarative approach... but then I hit a snag. It seems that foreign keys are an unsupported feature.

I use foreign keys in almost every table (and certainly in every project) to enforce data consistency, which unfortunately means I can't use Skeema just yet. FKs are a pretty fundamental feature of SQL.

Is foreign key support in the works?

Edit: I see the PR adding support, but the last update was July 30th.

**Comment by evanelias** [comment]
Thanks for checking out Skeema! Yes, foreign key support is under development. An external contributor wrote some initial code and I'm currently adding a few things on top (see https://github.com/skeema/skeema/pull/8 and https://github.com/skeema/tengo/issues/2). It's just taking quite some time due to complexities of InnoDB's foreign key support, as well as interaction with third-party tools like pt-osc.

I should also add my usual disclaimer that I do not recommend using foreign keys in MySQL in most circumstances, especially with non-trivial database sizes / high-volume OLTP environments. They negatively impact write performance, and they tend to interact poorly with online schema change tools. Every large-scale MySQL deployment I've worked with (Facebook and Tumblr) has avoided them for this reason. Fingers crossed that Oracle will improve things there in future MySQL versions!

That all said, totally understand that many MySQL shops do use foreign keys, and I do still view this as a high priority to get working in Skeema :)

**Comment by egtann** [comment]
I'm not opposed to learning a new workflow and I am by no means an expert in SQL, so I'm genuinely curious how you maintain consistency without DB-imposed constraints. Do you have any reading material or suggestions on other approaches to this problem?

**Comment by evanelias** [comment]
The alternative to foreign keys is just handling the logic at the application level. In an unsharded environment you can just do writes to multiple tables in a single transaction to ensure atomicity. Granted, there's risk of bugs from human error -- e.g. an engineer writes application logic that modifies one table but forgets to write to the other tables that refer to it. This can be solved with a homegrown ORM / data access layer that enforces the constraints in application code.

Things get much trickier in a sharded environment, since data on one shard can refer to data on another shard, which may be on a physically separate instance of MySQL. Neither foreign keys nor transactions help at that point, and doing things at the application level is basically the only option, at least in InnoDB. That gets especially hairy when one write succeeds but a subsequent related write fails, for example due to a networking issue or transient hardware failure. Sometimes you can order your writes such that negative user impact is avoided in a partial failure scenario, but it depends a lot on the application. Another approach is to write scripts that scan for inconsistencies and fix them; yet another is to queue up failed writes to another datastore and replay them later.

Anyway, overall it depends a lot on your application's scale, and how much flexibility you have to make trade-offs between consistency and performance :) Academics will say that referential integrity is absolutely essential, and in some sectors (such as finance/banking) that's absolutely true! But meanwhile in a large-scale OLTP environment, such as a social network, foreign keys are often skipped in favor of application-enforced consistency.

**Comment by evanelias** [comment]
I should also mention one other angle: on many web sites and apps (of all varieties), DELETEs have actually become more rare. In the modern era of cheap storage, it's quite common to just flag an object as deleted by updating a `status` column for example, and also enforce that in application logic, rather than fully deleting a row. This trend naturally reduces the usefulness of things like ON DELETE CASCADE.

**Comment by evanelias** [comment]
Foreign keys are finally supported in the master branch of Skeema, so closing out this issue. I'm planning on tagging a release by the end of next week, and including prebuilt binaries for linux/amd64 and darwin/amd64. 

A few new configuration options that are relevant to foreign keys:

* [--exact-match](https://github.com/skeema/skeema/blob/master/doc/options.md#exact-match) affects whether or not foreign key *names* are considered to be significant. This defaults to false, meaning the names are cosmetic. This provides easy compatibility with external tools like `pt-online-schema-change`, which need to mangle foreign key names in order to function. If set to true, Skeema's auto-generated DDL may include dropping and re-adding foreign keys in order to match the exact names specified in a table's *.sql file.

* [--foreign-key-checks](https://github.com/skeema/skeema/blob/master/doc/options.md#foreign-key-checks) affects whether or not new foreign keys on existing tables are checked for integrity. This defaults to false, meaning that if you add a new foreign key to an existing table, no server-side integrity check will be performed on existing data. This allows for faster`ALTER TABLE`s and removes a possible failure vector. If set to true, the server will perform an integrity check on any new foreign key that is being added to an existing table, and the `ALTER TABLE` will fail if the existing rows do not meet the constraint; this is viewed as a fatal error by Skeema. This is safer and more correct, but slower (especially with large tables) and potentially disruptive to automated processes if `skeema push` is used as part of a CI pipeline.
