### ISSUE TITLE
Issue with naming

### ISSUE THREAD

**Issue by obissick** [skeema/skeema#113]
Having a issue where files are being overwritten due to a table and stored procedure having the same name. An example is i have a table named `quality` and the stored procedure name is `Quality`, they are conflicting on git.

**Comment by evanelias** [comment]
Skeema supports having multiple objects with the same identical name, and supports having multiple CREATE statements in a single file. So for example you could have a table, stored procedure, and function all called `quality` and `skeema init` / `skeema pull` will put all of them in a single file `quality.sql`.

However, in your case it sounds like there are issues involving a case-insensitive filesystem conflating lowercase `quality` with capitalized `Quality`. 

I've tried reproducing this using a combo of case insensitive (Mac) and case sensitive (Linux) filesystems, but so far everything seems to work properly when I test. On Mac the two statements end up in the same file, which then works fine.

A few questions to help debug:
* What operating system are you running `skeema` from?
* Are you running `git` from the same place as `skeema`? (and if not, what operating system is used where you're running `git`?)
* Have you reconfigured any of Git's options around case sensitivity?
* What operating system is the MySQL / MariaDB server using?
* Can you share a log, cut-and-paste, or screencap of what is happening? If you can't post publicly, please use the support email address shown on https://github.com/skeema - thanks!

**Comment by obissick** [comment]
I checked the file and it only contains the create for the table. I am running skeema from a gitlab linux runner, this also is using git. Locally i am on a MAC using git on vscode. No i did not reconfigure Git. 
MariaDB is running on Centos 7.

**Comment by obissick** [comment]
I sent two screen recordings to email.

**Comment by evanelias** [comment]
Received them, thanks. However what I would need to see here is an example of a `skeema` command specifically doing the wrong thing... unfortunately screen recordings of vscode or gitlab won't really help narrow this down as being a Skeema specific problem.

Please understand that git has [many known difficulties](https://www.google.com/search?q=git+case+insensitive) when switching between case-sensitive and case-insensitive filesystems, if you have 2 files whose names only differ by case, which is what is happening in your example. 

What operating system did you initially run `skeema init` from? If you ran that from Linux, and then committed to git from Linux, your repo would end up with 2 separate files `Quality.sql` and `quality.sql`, since this is totally legal on case-sensitive filesystems under Linux. But if you then clone that git repo on a default case-insensitive OS like MacOS, its filesystem cannot represent these as 2 separate files, so you'd understandably encounter some issues with that operation. 

Some possible workarounds include either of the following:
* Run the initial `skeema init` from MacOS, which will put both CREATEs into a single file (this works properly in my testing)
or
* If running `skeema init` from Linux, manually rename `Quality.sql` to `quality-proc.sql` before committing it to git

If you need a more automatic solution, we could change this issue to be a feature request, to make Skeema only ever create lower-case filenames. But this will be low-priority if the problem is just due to OS/filesystem/git complexity and not a Skeema bug.

**Comment by obissick** [comment]
Thanks for the info, it looks like it has to do with the user. As you can see below i ran using the specific user and it removed the stored procs, then i did it with root and it added then back and also did what you mentioned earlier about appending to the the table create file. Not sure why the user is an issue since that user as full permissions to that database.
```
db git:(development) ✗ /Users/obissick/Downloads/skeema_1.3.1_mac_amd64/skeema pull development -p
Enter password: 
2019-12-04 19:07:45 [INFO]  Updating /Users/obissick/Documents/project_clones/greatdataworks/db to reflect 10.1.10.222:3306 dataworks
2019-12-04 19:07:45 [INFO]  Deleted /Users/obissick/Documents/project_clones/greatdataworks/db/Dashboard.sql
2019-12-04 19:07:45 [INFO]  Deleted /Users/obissick/Documents/project_clones/greatdataworks/db/CONVERT_TO_HMS.sql

 db git:(development) ✗ /Users/obissick/Downloads/skeema_1.3.1_mac_amd64/skeema pull development -u root -p
Enter password: 
2019-12-04 19:08:50 [INFO]  Updating /Users/obissick/Documents/project_clones/greatdataworks/db to reflect 10.1.10.222:3306 dataworks
2019-12-04 19:08:50 [INFO]  Wrote /Users/obissick/Documents/project_clones/greatdataworks/db/Quality.sql (21045 bytes) -- appended new object
2019-12-04 19:08:50 [INFO]  Created /Users/obissick/Documents/project_clones/greatdataworks/db/Dashboard.sql (2148 bytes)
2019-12-04 19:08:50 [INFO]  Created /Users/obissick/Documents/project_clones/greatdataworks/db/CONVERT_TO_HMS.sql (583 bytes)
2019-12-04 19:08:50 [INFO]  Wrote /Users/obissick/Documents/project_clones/greatdataworks/db/Report.sql (12376 bytes) -- appended new object
```

**Comment by evanelias** [comment]
> Not sure why the user is an issue since that user as full permissions to that database.

This is subtle but expected behavior -- in both mysql and mariadb, database permissions aren't actually sufficient to view stored procs / funcs that have a *different* user as the DEFINER. For example if you run `SHOW CREATE PROCEDURE dataworks.Dashboard` as the non-root user in the top example, I suspect you'll get a NULL proc body (`Create Procedure` column) in the result. This then means Skeema [won't be able to manage the proc](https://github.com/skeema/skeema/issues/81#issuecomment-508283894) with that user, because it lacks access to fully see it.

More info in https://mariadb.com/kb/en/library/show-create-procedure/ -- you can fix this by granting the user `SELECT on mysql.proc`, or possibly `USAGE on *.*` ... otherwise you need to either use root/superuser, or ensure that all of your procs/funcs have the same DEFINER as Skeema's user.

**Comment by obissick** [comment]
Yeah i see that now, thanks for the info.
