### ISSUE TITLE
Usage/best practice question

### ISSUE THREAD

**Issue by seanbrumwell** [skeema/skeema#117]
We have an application that unfortunately sees a lot of schema changes (hence why we're looking to use Skeema), and the actual DB schemas can vary quite a bit between different development and sometimes even production branches.  The approach I am using is to have each branch include it's own Skeema files.  This appears to be working fine in tests, however I have hit an interesting issue where I'm not sure of the best approach.

We have a client that runs the "normal" production code, however due to their use cases and data volume, several custom fields and indexes have been added to the normal DB schema on their system.  So, this basically means that the Skeema files attached to the branch they have deployed are no longer reflective what they have in production, so doing a push would potentially delete manually added indexes and fields.

I could just ignore the tables where this is done, but then any updates to them in the Skeema files would also be ignored, which we don't want.  The only other thought I have is it to keep a separate set of Skeema files in the branch just for them (this would be easy to do), however another question that was asked was whether it would be possible to keep an "augmented" set of Skeema files just for them.  So basically apply the normal ones, but then also have a separate set of "additions" that are added to certain tables just for them (instead of keeping a full separate set for them).

I'm not clear from the documentation if this is possible currently.  I don't believe it is, but figured it couldn't hurt to ask.  I'm currently leaning towards simply having a different set of Skeema files specifically for that client.

**Comment by evanelias** [comment]
Great question, and thank you for describing your use-case so clearly!

Currently there's no built-in way to keep a set of changes that are applied on top of the base files just for a particular db/shard. I think you've already identified the two best work-arounds, but just to summarize:

a) Use a separate dir for that customer, but within the same repo and branch. To avoid complete duplication, for any tables that are identical in both, you can use relative symlinks for just those .sql files. For example, if table foo has no customer-specific changes, `special_customer/foo.sql` could just be a symlink to `../base_customer/foo.sql`. This should generally work in all Skeema commands, as long as it's a relative symlink pointing within the same git repo.

or

b) Use a different git branch for that customer, containing extra commit(s) that already applied the unique customer-specific changes. Meanwhile, whenever a change is made to the master branch, be sure to also merge it into this branch (possibly resolving any git conflicts in the process). But be careful to never merge the other direction, since you don't want to accidentally introduce the customer-specific changes back into your normal production version.

Longer-term, there are a few possible ways this could be improved in Skeema:
* Support for templating logic in .sql files, allowing conditional behaviors
* Support for hook scripts in more places, allowing scripts that perform programmatic adjustments on the CREATE statements, the resulting "desired state" database objects, and/or the diff's generated DDL statements
* Ability to track "additions" as you've described, basically a set of extra CREATE and/or ALTER statements that are applied on top of the base CREATEs in certain conditions
* Ability to run a push in "additive only" mode, where DROP clauses are never even generated / missing things are just ignored

These are all getting somewhat advanced though, in terms of being geared towards businesses with special requirements. So just to set expectations, if any of these improvements are implemented, it's possible they'll end up in an upcoming commercial edition of Skeema rather than in open source.

**Comment by seanbrumwell** [comment]
Thank you for the detailed response, it's extremely helpful!  We've had to previously use the second methodology you mentioned in the past for similar situations, but due to the extra management (and potential for a backwards merge) I'm more inclined to go with the first option and simply keep a separate set of files for that client in the same branch.  I had not thought of the simlinks though.  I will definitely explore that avenue.

Thanks again!
