### ISSUE TITLE
host-wrapper function not being called

### ISSUE THREAD

**Issue by bracki** [skeema/skeema#118]
I'm trying to use `host-wrapper` to setup an SSH tunnel so I can connect via `127.0.0.1` to an AWS RDS instance in a private network.

This is my `.skeema` file:
```
default-character-set=utf8
default-collation=utf8_general_ci
schema=radio
host-wrapper="../scripts/skeema-host-wrapper {ENVIRONMENT}"

[test]
flavor=mysql:5.7
host=127.0.0.1
port=3306
user=admin

[beta]
flavor=mysql:5.7
host=127.0.0.1
port=3306
user=admin

[prod]
flavor=mysql:5.7
host=127.0.0.1
port=3306
user=admin
```

The script itself looks like this:
```
#!/usr/bin/env bash
set -e

log() { echo "$@" >&2; }

environment=$1

# Query the DB endpoint
databaseEndpoint="$(aws rds describe-db-cluster-endpoints --region eu-central-1 --db-cluster-identifier $environment-database --query 'DBClusterEndpoints[?EndpointType==`WRITER`].Endpoint' --output text)"

# Create an autoclosing tunnel
ssh -f -L 3306:$databaseEndpoint:3306 ec2-user@bastion.$environment.example.com  sleep 60

# Echo back the server to skeema
echo 127.0.0.1
```

It seems that the wrapper isn't being called. When I remove the `host`-lines from the `.skeema` file it complains with:
```
2020-02-13 16:10:51 [WARN]  Skipping .../database-schemas: no host defined for
                            environment "prod"
```

What can I do about this? Even cooler would be a native SSH support like [this](https://gist.github.com/vinzenz/d8e6834d9e25bbd422c14326f357cce0) or similar.

**Comment by evanelias** [comment]
Cool idea -- thanks for opening this issue!

I was able to get it working with one minor tweak: in your skeema-host-wrapper script, you must redirect the ssh command's STDOUT and STDERR to somewhere else, for example:

```
ssh -f -L 3306:$databaseEndpoint:3306 ec2-user@bastion.$environment.example.com sleep 60 >/dev/null 2>&1
```

Otherwise, despite the use of `ssh -f`, Skeema still seems to get blocked for the full 60 seconds before proceeding with attempting the diff logic, and by that time the tunnel is inherently closed. Apparently it's waiting for the child process to close those file handles; I believe this is a side effect of Golang's [Cmd.Wait()](https://golang.org/pkg/os/exec/#Cmd.Wait) behavior.

Side note, but for now I'd warn against using a relative path in the value of `host-wrapper`. It will be interpreted relative to the current working directory, which is potentially confusing -- this will only work if you know you will only ever have 1 skeema dir (no subdirs) and you always invoke `skeema` from this working dir. This may be improved in a future release, but for now it's better to either use an absolute path, or no path (e.g. put the script somewhere in your $PATH).

> When I remove the `host`-lines from the .skeema file it complains with:

This is actually intended behavior; you have to set the `host` value to *something* (even some invalid placeholder value) so that Skeema knows which dirs to run the wrapper script in. This comes up more in complex environments with multiple separate db clusters and multiple levels of subdirs -- this functionality allows you to set a common `host-wrapper` just once in a higher-level option file, and then in each actual cluster's config file you just set `host` there without needing to repeat the wrapper config.

That behavior is currently documented in the [host option](https://github.com/skeema/skeema/blob/master/doc/options.md#host) but I should improve this and also document it in host-wrapper.

> Even cooler would be a native SSH support like [this](https://gist.github.com/vinzenz/d8e6834d9e25bbd422c14326f357cce0) or similar.

Very nice, I agree that built-in SSH tunneling could be very useful. There's just some configuration ergonomics/flexibility to figure out, since some users will want to tunnel to a bastion host, while other users may need to tunnel to the database itself (e.g. companies whose security policy restricts grants for off-host connections)... possibly *also* through a bastion first :)

Anyway, let me know if the redirection hack fixes the behavior for you? If so, we can close this and open a separate feature request issue to track built-in SSH tunneling.

**Comment by bracki** [comment]
Yes, works as suggested. Thank you for the quick and detailed reply. `skeema` is a great tool, your effort is appreciated.

**Comment by evanelias** [comment]
Happy to say that [Skeema v1.8.0 has been released](https://www.skeema.io/blog/2022/06/02/v180-released/), and the Premium edition now includes extensive built-in support for SSH tunnels!
