### ISSUE TITLE
Add linter for reserved words in upcoming MySQL versions

### ISSUE THREAD

**Issue by morgo** [skeema/skeema#120]
MySQL 8.0 has a lot more reserved words than prior versions (the rationale was to peek ahead at the standard and add them all at once).  They are also all accessible via `information_schema`:

```
mysql8019> SELECT word FROM information_schema.keywords WHERE reserved=1;
+-------------------------------+
| WORD                          |
+-------------------------------+
| ACCESSIBLE                    |
| ADD                           |
| ALL                           |
| ALTER                         |
| ANALYZE                       |
| AND                           |
| AS                            |
..
| WRITE                         |
| XOR                           |
| YEAR_MONTH                    |
| ZEROFILL                      |
+-------------------------------+
261 rows in set (0.00 sec)
```

My feature request is to take this static list and add a linter, so that nobody who is currently developing on an earlier version will accidentally add a new column with a name that could cause them problems in the future.

**Comment by evanelias** [comment]
Thank you for the feature request!

**Comment by Madhur1997** [comment]
Hey @evanelias, I went through this repo and it seemed really interesting. I would be happy to work on this issue.

**Comment by evanelias** [comment]
Thanks @Madhur1997, much appreciated! Let me know if you have any questions. There are some brief development guidelines on #132.

This new linter check should only flag names that match a reserved word in a newer version than what the user is running. For example, if the user is running MySQL 5.6, this linter check should flag any names that are newly-added reserved words in MySQL 5.7 or 8.0. Meanwhile if the user is running MySQL 8.0, the linter check shouldn't flag anything, as no newer major release exists yet.

In order to make the user's current DB version available to linter checks, I've [added a commit today](https://github.com/skeema/skeema/commit/eb4289b) that exposes it via new [Flavor field in the linter.Options struct](https://godoc.org/github.com/skeema/skeema/linter#Options).

Here are the lists of newly-added reserved words in MySQL versions -- only the handful marked (R) are relevant for this linter check:
* [MySQL 5.6](https://dev.mysql.com/doc/refman/5.6/en/keywords.html#keywords-new-in-current-series)
* [MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/keywords.html#keywords-new-in-current-series)
* [MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series)
* No need to handle words added in MySQL 5.5 or older, since 5.5 is the oldest version supported by Skeema.

As far as I know, Percona Server's list is identical to MySQL's, so the linter check can treat them as equivalent.

Meanwhile MariaDB tracks it all on one page, noting the version in the Notes column: 
* https://mariadb.com/kb/en/reserved-words/
* Only need to care about the small handful of reserved words added in MariaDB 10.2 or newer, since 10.1 is the oldest version supported by Skeema.

No need to account for point releases. For example, if a new reserved word was added in MySQL 8.0.14, for simplicity's sake just treat it as MySQL 8.0.

**Comment by Madhur1997** [comment]
Thanks for the reply @evanelias. I will be doing some reading, understand the code flow and will get started on this.

**Comment by Madhur1997** [comment]
Is it required to provide the exact flavor that would cause troubles for the keyword?
Or just flagging it as incompatible for some future release is the requirement?

**Comment by evanelias** [comment]
In order to only flag reserved words that will be added in a future version, you will need to have a mapping of reserved words to their initial version anyway. So the linter check message might as well include the specific information about the version, since your code will already have this available.

No need to capture the specific point (patch) release number though. e.g. 8.0 is sufficient, rather than say 8.0.14.

**Comment by Madhur1997** [comment]
@evanelias so I was wondering, it shouldn't be too bad using the entire keyword list for each flavour instead of just using diff between 2 consecutive releases, comparing ~20 words vs ~200 words. 
The reason I ask this is I would base my design upon this choice.
Also, I was planning to have a json file storing the keywords and the corresponding flavor information.

**Comment by evanelias** [comment]
You only need the reserved words introduced in each version starting with MySQL 5.6 and MariaDB 10.2, as there's no benefit to capturing the list of ones introduced earlier than that. 

For performance reasons, you'll need a data structure with constant-time lookups, such as a map of reserved word => version introduced. When linting, this map will need to be consulted for every single identifier (table name, column name, index name, foreign key name, etc) and some users have hundreds of tables, so the lookups must be fast.

I would recommend just hard-coding this map in Go. I don't see a benefit to storing this in JSON, can you clarify why this would be desirable?

**Comment by Madhur1997** [comment]
The only reason for having JSON was cosmetics, but since we are storing diff of keywords. That should be fine for in program storage.
Also, there are some words that might be introduced say in mysql5.6 but got dropped in mysql5.7 and perhaps gets added in mysql8.0. So, what output would you have it display?

**Comment by evanelias** [comment]
> Also, there are some words that might be introduced say in mysql5.6 but got dropped in mysql5.7 and perhaps gets added in mysql8.0. So, what output would you have it display?

Do you have any examples? I don't see any where this is the case...

**Comment by Madhur1997** [comment]
Sorry, I was looking up somewhere else as well. But that wasn't really a reserved keyword. There doesn't seem to be such a case in the mysql list.

**Comment by evanelias** [comment]
Skeema v1.10 is [now available](https://github.com/skeema/skeema/releases/tag/v1.10.0) and includes this excellent feature. Thanks again for the pull request!
