### ISSUE TITLE
Add to list of 'system schemas'

### ISSUE THREAD

**Issue by morgo** [skeema/skeema#121]
From the code:
https://github.com/skeema/skeema/blob/3b4e46c5fb0f63c0181ef60ad285393d4a721efd/fs/dir.go#L418-L423

There are some additional schemas I would like to suggest:
- `INFORMATION_SCHEMA` / `PERFORMANCE_SCHEMA` (as caps)
- `METRICS_SCHEMA`
- `INSPECTION_SCHEMA`
- `ndbinfo`
- `percona`

This helps cover system schemas from NDB/Percona Toolkit/TiDB.

**Comment by evanelias** [comment]
Thank you for the issue report!

I agree the check against these names should be case-insensitive; I'll fix that in a commit momentarily. FWIW this code chunk only affects attempts to directly target a system schema, e.g. if a user intentionally modifies a .skeema file to contain `schema=INFORMATION_SCHEMA` for some weird reason.

In other code paths which gather/examine a list of all schemas, system schemas are automatically removed/ignored via https://github.com/skeema/tengo/blob/5584e1/instance.go#L293 and https://github.com/skeema/tengo/blob/5584e1/instance.go#L326.

I'm going to hold off on the other suggested additions though. I just don't have the resources to support NDB or TiDB in any capacity at this time. Users may already choose to have Skeema ignore any arbitrary schema name via the [ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) regex option, so that's a potential work-around.
