### ISSUE TITLE
unsupported statement `DROP TABLE IF EXISTS tbl;`

### ISSUE THREAD

**Issue by pznamensky** [skeema/skeema#122]
In almost all our projects, we use auto-generated `structure.sql` [1] file, which includes statements like this:
```
DROP TABLE IF EXISTS `tbl1`;
CREATE TABLE `tbl1` (
...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `tbl2`;
CREATE TABLE `tbl2` (
...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
But Skeema ignores statements like this `DROP TABLE IF EXISTS ...` with the following warning:
```
Unable to parse statement
Ignoring unsupported or unparseable SQL statement
```
It's not a big problem, but it generates a lot of noise in PRs.
Could you please add the ability to parse that statements?

[1] https://guides.rubyonrails.org/v3.2/migrations.html#types-of-schema-dumps

**Comment by evanelias** [comment]
Afraid I don't understand. Can you please describe your use-case / workflow / repo layout in more detail please?

Skeema is designed to parse *.sql files in a layout initially created via `skeema init`. Skeema will not ever place `DROP TABLE` statements in those files because they are completely unnecessary in Skeema's model or workflow.

**Comment by pznamensky** [comment]
It's funny that Skeema works fine with that files :)

>Afraid I don't understand. Can you please describe your use-case / workflow / repo layout in more detail please?

Here is an example (some random Ruby on Rails app): https://github.com/otwcode/otwarchive/blob/master/db/structure.sql
`db/structure.sql` usually describes a schema of a database used by app and in case of any changes in schema, the file is changing too and this file is being analyzed by Skeema in corresponding PR.

>Skeema is designed to parse *.sql files in a layout initially created via skeema init.

We're using Skeema CI, and everything we did is added Skeema in GitHub Apps.

**Comment by evanelias** [comment]
So it sounds like you are still using Rails migrations to make schema changes, and not using the Skeema command-line tool at all?

The Skeema CI github integration is designed to be used with the Skeema command-line tool. It's one cohesive system, with an intended pull request workflow described in the [docs](https://github.com/skeema/skeema/blob/master/doc/workflow.md).

The CI github integration is not designed to be used with random other tools like Rails, since Rails uses a completely different schema change workflow than Skeema. I guess the CI linting aspect might work fine, or it might not. But in any case, if you're using the CI system with something *other than* the `skeema` command-line tool, that's not a use-case I can provide support for at this time. Doing this negates most of the benefits of the system, as Rails is auto-generating your DDL already.

Also just to clarify, this repo is the **open source Skeema command-line tool**, and issues here should pertain specifically to this tool please. For questions/feedback pertaining only to the CI github integration, please see https://www.skeema.io/contact/ -- thanks!
