### ISSUE TITLE
Unable to lock temporary schema on docker container

### ISSUE THREAD

**Issue by modnar1226** [skeema/skeema#123]
Skeema version:
1.4.0

OS:
linux ubuntu 18.04

Objective:
Trying to run skeema diff after skeema pull and review diff.

Expected outcome:
To view the diff of the schema

Actual outcome:
[WARN] skipping table:  Unable to lock temporary schema on mysqlContainer: Unable to acquire lock
[ERROR] Skipped 16 operations due to errors

global .skeema contents:
[dev]
connect-options="innodb_strict_mode=0,sql_mode='ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
flavor=mysql5.7
host=mysqlContainer
port=3306
user=root
password=password

I am not sure if there is something I'm doing wrong. 
There was a schema already in place by other devs.
I ran 'skeema pull dev' and I got the updated files in the repo.
I then ran 'skeema diff dev' and received the above errors.

**Comment by evanelias** [comment]
This error typically means someone else is running `skeema diff` or `skeema push` at the same moment. 

If you try again, does the error still happen? If so, please run this query manually on that database instance and paste the result in a comment here:
```sql
SELECT IS_FREE_LOCK('skeema._skeema_tmp'), IS_USED_LOCK('skeema._skeema_tmp');
```

When you say "on docker container" in the title here, do you mean the `dev` instance just happens to be a copy of mysqld running in a container? Or do you mean you're using Skeema's built-in Docker workspace functionality (`--workspace=docker`)?

Side note but your workflow doesn't make sense to me:

> I ran 'skeema pull dev' and I got the updated files in the repo.
> I then ran 'skeema diff dev'

When running `skeema pull dev`, the purpose of this is to update your local filesystem to reflect the structure from `dev`. 

When running `skeema diff dev`, the purpose of this is to compare the structure on the local filesystem to the structure from `dev`.

If you run `skeema pull dev` and then immediately run `skeema diff dev` afterwards, the diff will inherently always be empty/blank. The pull already made the filesystem identical to `dev`. There's nothing to diff after that.

Typically you should run `skeema pull dev` after making *manual* changes to dev (e.g. you ran some DDL in MySQL directly, outside of Skeema) which you want to have reflected in the filesystem. You can then commit these changes to your repo (git or any other SCM tool). Afterwards you might perhaps run `skeema diff production` to compare these changes **to prod** (or some other environment/db), but not dev, since that's where the changes came from in the first place.

**Comment by modnar1226** [comment]
Thank you for such a detailed response!

**_If so, please run this query manually on that database instance and paste the result in a comment here:

SELECT IS_FREE_LOCK('skeema._skeema_tmp'), IS_USED_LOCK('skeema._skeema_tmp');_**

Current db query 03-02-2020 approx 9 am.
![Screenshot from 2020-03-02 08-57-34](https://user-images.githubusercontent.com/42381732/75682772-f8912180-5c63-11ea-861b-49d95963189c.png)

I am just running an instance of mysql on a docker container not using the built in workspace.

I think I was working on this at the end of the day and tried did a `skeema diff` originally, but still received the errors. So I tried running  `skeema pull` to see if that worked (ran without errors)  which it did. Then retried running `skeema diff` again. 

The documented workflow makes perfect sense, I was trying anything to see what issues I might run into. Error responses and such. I would like to integrate this into a pre-commit process for my test environment.

**Comment by evanelias** [comment]
Thanks, that query seems to show nothing is holding the lock. To confirm, you're still consistently getting that same error from `skeema diff` today?

Afraid I can't reproduce this and I don't see any obvious cause yet. A few additional questions:

* What exact version of MySQL is your dev environment using? (If unsure, please run `SELECT  @@version, @@version_comment;` and paste result here)
* Is there a 30-second pause between when you run `skeema diff` and when the error is returned, or does the error come up right away?
* When you said "global .skeema contents", which .skeema file(s) are you referring to -- i.e. do you mean a .skeema file in the same directory as your *.sql files, a parent directory, your $HOME directory, or a truly global location like /etc/skeema ?
* You said your config has `flavor=mysql5.7`, is this verbatim copy-paste or did you retype it? (It should normally have a colon in it, for example `flavor=mysql:5.7`)
* In the warning `[WARN] skipping table: Unable to lock temporary schema on mysqlContainer: Unable to acquire lock` is that really referring to a specific **table** name? With that error I would normally expect it should be a **directory** name, not a table name. Also `Skipped 16 operations due to errors` is weird, that suggests your directory is being mapped to 16 different database instances...

It would be helpful for me to see a full capture of the `skeema diff` output and full capture of the .skeema file(s). Feel free to obscure any sensitive information (password, hostnames, etc). If you don't want to post publicly, please use the support e-mail address shown on https://github.com/skeema -- thanks!

**Comment by modnar1226** [comment]
No today is all good so far. I think I just had something hung up in the background. From firing off commands.

There was a delay before errors. 

By global i meant in the folder that was created by `skeema init`.

There is a colon between it reads flavor=mysql:5.7

There are 13 separate sub folders under the skeema folder, which is correct and there are 13 databases. 

So far I have not had any more issues. It would seem it was hung up but not now. 
You can close this ticket if you would like. I really do appreciate you detailing your responses, and being responsive. Its a nice product. 

Thanks for your time.
