### ISSUE TITLE
AWS Aurora: unable to diff tables with multiple foreign keys

### ISSUE THREAD

**Issue by kaitlynbrown** [skeema/skeema#124]
I recently migrated both my dev and prod RDS databases from MySQL to Aurora MySQL

After the migration, I was able to make schema changes on dev using skeema with no problems, however when I tried running the same changes on prod, I kept getting errors like the following:

```
2020-03-27 12:07:25 [WARN]  Skipping table `telemedicine_sessions_cancelled`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2020-03-27 12:07:25 [DEBUG] --- Expected CREATE
2020-03-27 12:07:25 [DEBUG] +++ MySQL-actual SHOW CREATE
2020-03-27 12:07:25 [DEBUG] @@ -9,2 +9,2 @@
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `_fk-telemedicine-sessios-cancelled-session` FOREIGN KEY (`session_id`) REFERENCES `telemedicine_sessions` (`id`),
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `fk-telemedicine-session-cancelled-clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`)
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `fk-telemedicine-session-cancelled-clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`),
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `_fk-telemedicine-sessios-cancelled-session` FOREIGN KEY (`session_id`) REFERENCES `telemedicine_sessions` (`id`)
2020-03-27 12:07:25 [WARN]  Skipping table `telemedicine_sessions_rejected`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2020-03-27 12:07:25 [DEBUG] --- Expected CREATE
2020-03-27 12:07:25 [DEBUG] +++ MySQL-actual SHOW CREATE
2020-03-27 12:07:25 [DEBUG] @@ -8,2 +8,2 @@
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `__fk-telemedicine-session-rejected-clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`),
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `fk-telemedicine-sessios-rejected-session` FOREIGN KEY (`session_id`) REFERENCES `telemedicine_sessions` (`id`)
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `fk-telemedicine-sessios-rejected-session` FOREIGN KEY (`session_id`) REFERENCES `telemedicine_sessions` (`id`),
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `__fk-telemedicine-session-rejected-clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`)
2020-03-27 12:07:25 [WARN]  Skipping table `telemedicine_sessions`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2020-03-27 12:07:25 [DEBUG] --- Expected CREATE
2020-03-27 12:07:25 [DEBUG] +++ MySQL-actual SHOW CREATE
2020-03-27 12:07:25 [DEBUG] @@ -39,2 +39,2 @@
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `_fk-telemedicine-session-clinics` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`),
2020-03-27 12:07:25 [DEBUG] -  CONSTRAINT `telemedicine_sessions_ibfk_1` FOREIGN KEY (`practitioner_id`) REFERENCES `users` (`id`)
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `telemedicine_sessions_ibfk_1` FOREIGN KEY (`practitioner_id`) REFERENCES `users` (`id`),
2020-03-27 12:07:25 [DEBUG] +  CONSTRAINT `_fk-telemedicine-session-clinics` FOREIGN KEY (`clinic_id`) REFERENCES `clinics` (`id`)
```

I tried changing the order of the foreign keys in my CREATE TABLE statements to match what it wants, but that doesn't seem to change anything, I still get the same errors. 

The only thing that allowed me to update any of the affected tables was deleting its foreign keys entirely, but it gives me the same errors when I try to add them back in.

**Comment by evanelias** [comment]
Thank you for the issue report. A few quick questions to help narrow this down:

* What version of Skeema are you using? (`skeema --version`)
* What version of Aurora/MySQL are you using, as reported in the AWS console?
* Please run this query in dev and prod and paste the result:
```sql
SELECT @@global.version_comment, @@global.version;
```

Unfortunately it is difficult to maintain perfect compatibility with Aurora since it is essentially a closed-source fork of MySQL, and its behavior does not exactly track that of equivalent MySQL versions. Since there's no free version of Aurora, it isn't feasible to include it in Skeema's automated test suite at this time, unless a corporation is interested in sponsoring this effort.

Sometimes Amazon back-ports changes from more recent MySQL versions into their fork. In this case I suspect they back-ported some changes from MySQL 8.0.19, which was known to affect the reported ordering of foreign keys. Skeema v1.4.2 already has a fix for this, but it is only applied if the database self-reports as 8.0.19+, which Aurora presumably doesn't do. I'm hoping that Aurora provides some other indicator (perhaps in `@@global.version_comment`) that Skeema can use to conditionally apply this fix.

As a hacky temporary work-around, you could try overriding `flavor=mysql:8.0.19` in your host-level .skeema file, but this is likely to break other things since Aurora doesn't support all aspects of MySQL 8.

**Comment by alexandre-vaniachine** [comment]
Earlier I was able circumvent a similar problem by adding --skip-verify to the push command.

**Comment by evanelias** [comment]
@alexandre-vaniachine That's unrelated -- using `--skip-verify` only suppresses "Diff verification failure" errors, not "unable to generate DDL due to use of unsupported features" errors. That said, using `--skip-verify` normally should not be necessary unless there's a bug in Skeema; please open a separate issue for your situation. Thanks!

@kaitlynbrown just following up to see if you could provide more information please, thanks!

**Comment by alexandre-vaniachine** [comment]
Hi @evanelias my earlier issue was resolved in [#83]. Indeed to circumvent the issue then, I also compiled the skeema executable with just one [line](https://github.com/skeema/tengo/blob/master/instance.go#L1253)  commented out:
```
			if actual != expected {
//				t.UnsupportedDDL = true
			}
```

**Comment by evanelias** [comment]
Please don't ever remove that line or recommend to others removing that line. It's a core safety check that must remain in place for this software to be safe to use.

**Comment by kaitlynbrown** [comment]
Sorry for the delay in response, I forgot about this for a while

I'm using version 1.4.2 of skeema. 
The Aurora version of my DB is 1.17.98
The MySQL version of my DB is 5.6

Let me know if there's any other info I can provide

**Comment by evanelias** [comment]
Hi @kaitlynbrown, thanks but I really need the full output of the query from the 3rd bullet of my original reply -- please run this query in dev and prod and paste the result:

```sql
SELECT @@global.version_comment, @@global.version;
```

I'm hoping that Aurora puts extra information in one of those variables that would permit Skeema to auto-detect when it is running under Aurora.

**Comment by evanelias** [comment]
Ah nevermind I see your edited reply now, thanks. Unfortunately it doesn't seem there's anything Skeema can do to auto-detect Aurora. I'll have to think about this more, but in the near-term I'm not optimistic about being able to support Aurora unless a corporation wants to sponsor that development effort.

**Comment by zylo47** [comment]
@evanelias for Aurora you can run this command

`select AURORA_VERSION();`

It will return something like this

> +------------------+
> | AURORA_VERSION() |
> +------------------+
> | 1.22.1           |
> +------------------+

On non-Aurora versions you will get an error like this

> ERROR 1046 (3D000): No database selected

Perhaps you can check for this when testing if it's an Aurora database

**Comment by evanelias** [comment]
@zylo47 thank you, but the full picture is more complicated than that. I was hoping Aurora would provide a hint in one of the variables *already queried by Skeema*, but it does not.

Some Skeema users are very latency-sensitive, due to running it from local machines against DBs in remote datacenters. So generally it's important to keep the number of superfluous queries to a minimum. Since the vast majority of Skeema users are *not* using Aurora, I'm very hesitant to introduce an extra Aurora-specific query.

This could be mitigated by *only* running that query when the `@@global.version` matches a known value reported by Aurora (e.g. 5.6.10), but this would require a bit of testing against different Aurora clusters to build a mapping of all possible Aurora versions to purported MySQL versions. And overall, Aurora would really need its own distinct [flavor](https://github.com/skeema/skeema/blob/master/doc/options.md#flavor) in Skeema in order to model the behavioral differences between it and "real" MySQL; this is the system already used by Skeema to model MySQL vs Percona Server vs MariaDB.

However, I don't personally use Aurora or have access to an Aurora cluster, and none of my current consulting clients use Aurora either. I'm not inclined to spend my own time and money to implement support for a proprietary commercial database. If a company who uses Aurora wants to pay for this development time to make Skeema support their use-case, then I'd be more than happy to work with them on this. But absent that, this is simply not going to happen in open source Skeema. 

Alternatively, if/when a commercial edition of Skeema is developed, this can be reapproached at that time if there's sufficient interest from potential paying customers.

**Comment by davideicardi** [comment]
Do you know when exactly this problem occurs in Aurora?
I mean, this problem occurs on all tables with multiple foregn keys or just in some specific circustances?

**Comment by shandrew** [comment]
AWS has been eager to help out open source projects with lots of credits:
https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

If anyone here has the specific unusual behavior for "show create table", I'm happy to pass it along to AWS support or Aurora team to see if it's a bug or to figure out other details behind the key ordering.

(I don't work for Amazon but I work closely with them as a customer)

**Comment by evanelias** [comment]
@shandrew those credits are only valid for one year, and they're aimed at "projects with maintainers from multiple entities or that are owned by foundations or non-profits." This is simply not a viable solution for an independent open source project like Skeema.

Bigger-picture, the issue here is that Aurora is a **proprietary fork**: it is not MySQL under the hood, and it is not open source. Even if the FK issue is resolved, there are likely other incompatibilities lurking in there already. Properly implementing Aurora support in Skeema involves adding it as a new Vendor/Flavor, which is how differences between MySQL, Percona Server, and MariaDB are already managed; this is **non-trivial** in terms of initial time commitment. Additional incompatibilities may come in the future, requiring **ongoing maintenance time** to keep Skeema compatible, even putting the cost aside.

I've tried to explain this twice in this thread already, and clearly have failed to get my point across, so let me be blunt: **I am not interested in spending my time or money building *open-source* solutions for proprietary systems, full stop**. My thinking is that if a company uses a proprietary commercial database system like Aurora, surely such a company can also purchase commercial tooling around it, such as a future commercial edition of Skeema with first-class Aurora support.

**Comment by evanelias** [comment]
I'm happy to announce that the Premium edition of the Skeema CLI is now available! It adds full compatibility with AWS Aurora, including a fix for this issue. Learn more at the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
