### ISSUE TITLE
no-op USING BTREE index clause is unsupported

### ISSUE THREAD

**Issue by oliverzheng** [skeema/skeema#13]
I have a table that has some single-column indices and some multi-column indices. Its structure is as such:

```
CREATE TABLE `tableName` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `repository_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `repository_id` (`repository_id`),
  KEY `user_id` (`user_id`),
  KEY `perm_search` (`repository_id`,`user_id`) USING BTREE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

When I run `skeema diff` without making changes to the schema or the table, it says there are unsupported features. When run with `--debug` it seems like it's pointing at the multi-column indices. It sounds like it's saying it doesn't see the fact that there is a `USING BTREE` statement in the schema and thinks it needs to modify the type of the index.

```
[WARN]  Skipping table tableName: unable to generate ALTER TABLE due to use of unsupported features
[DEBUG] --- Skeema-expected
[DEBUG] +++ MySQL-actual
[DEBUG] -  KEY `perm_user_search` (`repository_id`,`user_id`)
[DEBUG] +  KEY `perm_user_search` (`repository_id`,`user_id`) USING BTREE
[INFO]  127.0.0.1:3306 db: diff complete
[WARN]  Skipped 1 operation due to unsupported feature
[DEBUG] Exit code 1
```

Is this a bug, or are multi-column indices not supported?

```
$ skeema --version
skeema version 0.2 (beta)
```

**Comment by evanelias** [comment]
Thank you for trying out Skeema and reporting an issue! Yes, multi-column indexes are fully supported. The problem in this case is simply the `USING BTREE` clause.

That clause actually has no effect in InnoDB, since all InnoDB indexes are always btree indexes; InnoDB doesn't actually support any other type. (See https://dev.mysql.com/doc/refman/5.7/en/create-index.html#create-index-storage-engine-index-types)

However, despite InnoDB not supporting any other index type, it seems that MySQL remembers the `USING` clause and, if it was present originally, it will include it in its output of `SHOW CREATE TABLE`. But if no `USING` clause was supplied (much more common in my experience), MySQL omits it from `SHOW CREATE TABLE`, even though for InnoDB omitting the clause means the exact same thing as `USING BTREE`.

This is what is confusing Skeema -- it has a safety-check to ensure that its understanding of the table structure matches MySQL's exactly, but it isn't taking `USING` clauses into account. Hopefully this is an easy fix, but I'll have to investigate how `information_schema` represents that clause when it is missing vs when it is present. I'll update this issue after researching more. Thanks again for reporting this! 

For a workaround, in theory you could ALTER your table directly to drop that index and re-add it without the `USING BTREE` clause. (But of course depending on your MySQL version, table size, and replication setup, be careful with this, since index manipulations on large tables can be operationally disruptive.)

**Comment by oliverzheng** [comment]
Ah gotcha. I created the table/indices with phpMyAdmin, which likely specified the index type as it would for other types of storages.

Thanks so much for creating this tool, Evan. I was used to having EntSchema at Facebook converting declarative schemas to mutation statements, and was surprised to find no replacement elsewhere. Skeema fills a big need here!

**Comment by evanelias** [comment]
I finally got a chance to dig deeper into this. Apologies for the long delay -- this bug is a fairly rare edge case, so a few other things took priority.

The general problem is that there are a few rare CREATE TABLE clauses which have no effect in InnoDB and are not reflected anywhere in `information_schema`, yet MySQL nonetheless "remembers" in its *.frm table definition files. These clauses do still appear in `SHOW CREATE TABLE` though, which tricks Skeema into thinking the table is using features that it doesn't support, since it can't come up with a matching `CREATE TABLE`.

There are a few types of no-op clauses where this comes up, though I've only ever seen the first two in the wild:
1. `USING BTREE` and `USING HASH` index clauses, as described earlier in this issue
2. `KEY_BLOCK_SIZE=n` clauses on indexes, which confusingly comes up if you compress an InnoDB table and then later remove compression (described in [mysql bug 70534](https://bugs.mysql.com/bug.php?id=70534))
3. `STORAGE MEMORY` and `STORAGE DISK` clauses on columns
4. `COLUMN_FORMAT DYNAMIC` and `COLUMN_FORMAT FIXED` clauses on columns

Reopening this until I commit a fix later today. The plan is simply for Skeema to ignore/strip these clauses entirely for InnoDB tables, which is safe since none of them have any effect in InnoDB.
