### ISSUE TITLE
cannot create users

### ISSUE THREAD

**Issue by a5a5a9** [skeema/skeema#131]
Is this supported ? 

I get 
 17:56:46 [WARN]  Ignoring 2 unsupported or unparseable statements found in this directory's *.sql files; run `skeema lint` for more info

skeema lint doesn't give any valuable info

**Comment by evanelias** [comment]
> Is this supported ?

Skeema does not interact with users/grants yet, as mentioned in [the docs](https://github.com/skeema/skeema/blob/master/doc/requirements.md#unsupported-features).

The primary focus of Skeema is managing tables, although it now also supports stored procedures and functions. It is likely that [views](https://github.com/skeema/skeema/issues/63), [triggers](https://github.com/skeema/skeema/issues/62), [events](https://github.com/skeema/skeema/issues/61), and maybe users/grants/roles will be supported at some point in the future.

Out of curiosity, how did you end up with `CREATE USER` statements in your schema repo? Commands like `skeema init` and `skeema pull` won't ever put them there.

> skeema lint doesn't give any valuable info

It should have given you the file and line number of each unsupported statement. Did it not do so?

**Comment by a5a5a9** [comment]
I got that after a skeema push  to a fresh new mysql database. 

with Skeema lint

0-06-03 11:17:25 [INFO]  Linting /home/myskeema/schemas
2020-06-03 11:17:25 [INFO]  Linting /home/myskeema/schemas/common
2020-06-03 11:17:25 [INFO]  Linting /home/myskeema/schemas/common/nnnn
2020-06-03 11:17:25 [WARN]  /home/myskeema/schemas/common/nnnn/xxxxxx.sql:1:1:
                            Ignoring unsupported or unparseable SQL statement
2020-06-03 11:17:25 [WARN]  /home/myskeema/schemas/common/nnn/xxxxxx.sql:2:1:
                            Ignoring unsupported or unparseable SQL statement
2020-06-03 11:17:25 [WARN]  Found 2 warnings

**Comment by evanelias** [comment]
> I got that after a skeema push to a fresh new mysql database.

My question was how did the `CREATE USER` (or `GRANT` or equivalent) end up in your .sql files in the first place -- did someone put those in there manually? Or are you combining Skeema with some other dump tool? (Skeema itself won't ever put user/grant-related statements into your .sql files...)

I'm just trying to better understand your use-case, to see if Skeema is even a fit for it. Thanks!

> 2020-06-03 11:17:25 [WARN] /home/myskeema/schemas/common/nnnn/xxxxxx.sql:1:1:
Ignoring unsupported or unparseable SQL statement

Cool, `skeema lint` is working as intended here. You mentioned it doesn't give "valuable info" here, but there's nothing more it can do about this situation. It is pointing out the filename and line number of the statements that it cannot parse. Since it cannot parse these statements, it doesn't know anything else about them, so it can't provide a more informative message.
