### ISSUE TITLE
Consider adding a CONTRIBUTING document

### ISSUE THREAD

**Issue by techwolf359** [skeema/skeema#132]
Hello!

Requesting some additional documentation around contributing. The types of information I would be interested in are around how to get started developing and what kind of test coverage would be expected for pull requests.

This may lower the bar for people interested in contributing back to this excellent project.

**Comment by evanelias** [comment]
Thanks, I agree this would be beneficial. I hope to write up a thorough doc at some point, but unfortunately my bandwidth for open source work is a bit limited for the next few months.

Until then, some quick tidbits that may help:

* Skeema uses only standard Go toolchain invocations (`go build`, `go test`, etc) so there's no notion of a makefile or build script beyond that.

* CI is currently using [Travis](https://github.com/skeema/skeema/blob/master/.travis.yml) but will likely switch to GitHub Actions in the near future. CI ensures that all tests pass, all files are formatted according to `gofmt`, and all lint checks in `golint` pass as well.

* Code coverage is tracked via Coveralls, which will automatically comment on PRs with the coverage delta. Ideally each PR should maintain or improve the current coverage %, unless there's a compelling reason otherwise. 

* Tests can be run locally as well, no need to wait for CI. By default, `go test` will run Skeema's unit tests, but not integration tests. The integration tests require Docker, and you can use the `SKEEMA_TEST_IMAGES` env var to control which DBMS flavors/versions are tested against. Some examples of local test invocations:
  * Run unit tests, and integration tests against MySQL 5.7, for the package in the current directory: `SKEEMA_TEST_IMAGES=mysql:5.7 go test -v`
  * Run unit tests, and integration tests against Percona Server 5.7 and 8.0, for current dir and its subdirs: `SKEEMA_TEST_IMAGES=percona:5.7,percona:8.0 go test -v -p 1 ./...`
  * Re-run a specific failing integration test, in this example just `SkeemaIntegrationSuite.TestPullHandler` on mariadb 10.2: `SKEEMA_TEST_IMAGES=mariadb:10.2 go test -v -run Integ/Pull`

* The first time you run a test against a given flavor/version, it'll be a bit slow since the corresponding image will be fetched from dockerhub and a container will be created. The test containers are halted after tests complete, but aren't destroyed -- so subsequent test invocations are much faster since they just restart the existing container. But this also means you have to manually destroy/prune containers/images/volumes if you want to reclaim disk space, or force usage of a brand new mysql point release, etc.
