### ISSUE TITLE
Diff is not consistant between 2 timestamp columns

### ISSUE THREAD

**Issue by gregoryb** [skeema/skeema#134]
Hello,

I just made an init followed by a diff.

Skeema suggests the following modification

```
ALTER TABLE `xxxx` 
MODIFY COLUMN `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, MODIFY COLUMN `importDate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00';
```

Here's the definition of my table

```
CREATE TABLE `xxxx` (
  `date` timestamp NOT NULL,
  `importDate` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I don't understand why the change is not the same between the 2 columns.

Thank you

**Comment by evanelias** [comment]
This is a MySQL behavior. By default the first TIMESTAMP column of a table behaves differently than subsequent TIMESTAMP columns in a table. From the [MySQL manual](https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html):
```
TIMESTAMP and DATETIME columns have no automatic properties unless they are 
specified explicitly, with this exception: If the explicit_defaults_for_timestamp
system variable is disabled, the first TIMESTAMP column has both DEFAULT
CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP if neither is specified explicitly.
```

If you ever doubt the output of `skeema diff`, I would recommend that you try recreating the scenario on an empty table in a temporary location. After running your intended `ALTER` manually on the empty table, you can use `SHOW CREATE TABLE` and examine the result. In this case you'd see the columns automatically get the same ON UPDATE or DEFAULT properties you're seeing `skeema diff` display, even if you omitted them from your manual `ALTER`.

The output from Skeema is *always* going to match the manual verification in this manner, because internally, Skeema is doing this same verification technique, as one of many safety checks.

**Comment by evanelias** [comment]
Also just to clarify, the exact behavior you'll see depends on your database server's configured value of `explicit_defaults_for_timestamp`, which [defaults to OFF](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp) in MySQL 5.7 and older (and all versions of MariaDB), but [defaults to ON in MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp).

If you originally created a table when this variable was ON, but later switched to it being OFF globally, you may see unexpected/confusing diffs like above. To prevent this, you must either switch `explicit_defaults_for_timestamp` back to ON globally on the database server, or just for Skeema's sessions by configuring `connect-options="explicit_defaults_for_timestamp=ON"` in a .skeema file.

**Comment by gregoryb** [comment]
Great explanation. Thank you. I've learned something ;)
