### ISSUE TITLE
Splitting tables and stored procedures into sub-directories

### ISSUE THREAD

**Issue by gregoryb** [skeema/skeema#137]
Hello,

Is there an option to create a sub directory for each group of scripts.
I would like to have the following directory structure

- my-db\tables\my_table.sql
- my-db\storedprocedures\my_stored_procedure.sql

When a i reproduce this structure skeema detects a DROP.

Thank you.

**Comment by evanelias** [comment]
All objects in the same logical schema must be placed in the same directory.

It is possible that more flexible subdir placement may be supported in the future, but there are no concrete plans for this yet.

**Comment by gregoryb** [comment]
It might simplify the organization of the files rather than having all the items mixed up.

In the meantime, I'll organize my scripts with subdirectories and just before running skeema, i'll move everything to the same level in a temporary directory.

Thank you!

**Comment by evanelias** [comment]
Sounds like a good workaround.

Just for background, natively supporting this would be pretty complex to implement -- several weeks of fulltime effort. Until very recently, all of the filesystem-related logic assumed a 1:1 mapping between subdirs and logical schemas. As of the latest release, there is now limited support for multiple logical schemas in a single subdir, but not vice versa. Allowing a single logical schema to span multiple subdirs would greatly affect all of the dir parsing code, fs dumping code, and subdir walking code.

The company who generously sponsored the development of the stored proc support was fine with everything in one subdir, so that's how it was implemented. This is one of the benefits of sponsoring open source development: a sponsored feature will be implemented in a way that matches the sponsor's use-case / preferences :)

Normally I'd keep this open as a feature request issue, but the broader concepts are being tracked in an older/larger issue, see 2nd bullet of https://github.com/skeema/skeema/issues/22#issuecomment-459907251
