### ISSUE TITLE
lint panic

### ISSUE THREAD

**Issue by razor-1** [skeema/skeema#141]
Haven't had time to dig into why this is happening, or what minimal schema might trigger it.

```
$ skeema --debug lint
2020-08-02 21:19:50 [INFO]  Linting /[redacted]
2020-08-02 21:19:50 [INFO]  Linting /[redacted]
2020-08-02 21:19:50 [DEBUG] goroutine 1 [running]:
                            runtime/debug.Stack(0xc000181880, 0x89724f, 0x5)
                            	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/debug/stack.go:24 +0x9d
                            main.main.func1(0xc0004b9f58)
                            	/home/runner/work/skeema/skeema/skeema.go:37 +0x14d
                            panic(0x8167e0, 0xbdbfc0)
                            	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/panic.go:969 +0x166
                            github.com/skeema/tengo.(*Instance).CanSkipBinlog(0x0, 0x89df21)
                            	/home/runner/work/skeema/skeema/vendor/github.com/skeema/tengo/instance.go:269 +0x37
                            github.com/skeema/skeema/workspace.OptionsForDir(0xc00014b0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                            	/home/runner/work/skeema/skeema/workspace/workspace.go:158 +0x38d
                            main.lintDir(0xc00014b0e0, 0x4)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:144 +0xd79
                            main.lintWalker(0xc00014b0e0, 0x4, 0x1)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:92 +0xc4
                            main.lintWalker(0xc00014b050, 0x5, 0xc000181880)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:115 +0x473
                            main.LintHandler(0xc000181880, 0xc00019c4b0, 0x898211)
                            	/home/runner/work/skeema/skeema/cmd_lint.go:55 +0x7f
                            github.com/skeema/mybase.(*Config).HandleCommand(0xc000181880, 0x0, 0x0)
                            	/home/runner/work/skeema/skeema/vendor/github.com/skeema/mybase/config.go:88 +0x19d
                            main.main()
                            	/home/runner/work/skeema/skeema/skeema.go:53 +0xec
                            
2020-08-02 21:19:50 [ERROR] runtime error: invalid memory address or nil pointer dereference
2020-08-02 21:19:50 [DEBUG] Exit code 2

$ skeema --version
skeema version 1.4.5, commit 55f2c1b58bec6af7d40f6caa34911ed7f3e9b4d7, released 2020-07-27T21:21:38Z
```

**Comment by evanelias** [comment]
Thank you for the issue report! This appears to affect `skeema lint` and `skeema format` under certain conditions where they are unable to operate anyway. Prior to Skeema v1.4.0, these commands printed a user-friendly error message in these situations, rather than a panic. I'll fix this in the main branch soon.

The panic occurs when a directory contains 1 or more .sql files, but is not ever mapped to a database instance. This can happen in any of these situations:
* There's no .skeema file at all, in this dir or its parent dirs
* There's a .skeema file but it doesn't ever define [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host)
* There's a .skeema file defining [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host), but not for the current environment name (e.g. it defines [host](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host) only under `[development]` but you're specifying a different environment name, or just running `skeema lint` which defaults to `production` environment)
* The [host-wrapper](https://github.com/skeema/skeema/blob/9be20ec/doc/options.md#host-wrapper) option is in use, but the configured command returns an empty result for this directory

Does one of the above scenarios match your situation?

**Comment by razor-1** [comment]
Indeed it does, the third one to be precise. I had missed the statement in the lint help about needing access to a db instance and assumed based on the other docs that lint could operate just on the files in the directory. Thank you! I agree that a friendlier error message would be nice.

**Comment by evanelias** [comment]
Awesome, thanks! And yes it's a bit counter-intuitive but most Skeema commands do indeed need access to a DB; explainer doc is here: https://github.com/skeema/skeema/blob/master/doc/faq.md#no-reliance-on-sql-parsing
