### ISSUE TITLE
Unable to initialize skeema

### ISSUE THREAD

**Issue by matthewmueller** [skeema/skeema#147]
I have a MySQL instance running locally with a handful of databases. Here's the configuration I normally connect with:

![image](https://user-images.githubusercontent.com/170299/98552505-d3e35400-229e-11eb-847e-d3481f28472c.png)

I'm trying to initialize with skeema, but unfortunately no luck:

```
$ skeema init -h 127.0.0.1 -d mysql
[mysql] 2020/11/09 15:17:10 packets.go:36: unexpected EOF
[mysql] 2020/11/09 15:17:10 connection.go:135: write unix ->/tmp/mysql.sock: write: broken pipe
2020-11-09 15:17:10 [ERROR] Cannot examine schemas on localhost:/tmp/mysql.sock:
                            Error querying information_schema.tables for schema
                            db_test2: invalid connection
[mysql] 2020/11/09 15:17:10 packets.go:122: closing bad idle connection: EOF
[mysql] 2020/11/09 15:17:10 connection.go:135: write unix ->/tmp/mysql.sock: write: broken pipe
[mysql] 2020/11/09 15:17:10 packets.go:122: closing bad idle connection: EOF
[mysql] 2020/11/09 15:17:10 connection.go:135: write unix ->/tmp/mysql.sock: write: broken pipe
```

I've tried quite a few variations including `-o tls=preferred`. I also followed [this answer](https://stackoverflow.com/questions/748478/cannot-find-mysql-sock) to verify that the socket is located in `/tmp/mysql.sock`.

**Comment by matthewmueller** [comment]
**Update**: it turns out `db_test2` the table had some problems. I dropped it and now it's working. I'm not sure what the problem with that table was. Feel free to close since I'm not blocked.

**Comment by evanelias** [comment]
Glad you were able to get it working! 

FWIW, a problematic table won't affect ability to connect. Most likely the problem was use of `localhost`, which in MySQL ecosystem tools always means "use a unix domain socket file". If you want a tcp/ip connection you must use `127.0.0.1`. More info in Skeema's [host option](https://github.com/skeema/skeema/blob/main/doc/options.md#host) doc, but this is also how the `mysql` client (and all stock tools including `mysqldump` etc) work as well.

Also no need to set `-o tls=preferred` in recent versions of Skeema, as this is [enabled by default](https://github.com/skeema/skeema/blob/main/doc/options.md#connect-options) since v1.4.4.

**Comment by evanelias** [comment]
Sorry, was going by the original issue text, I see you edited re: use of `127.0.0.1`. Out of curiosity what did the error output look like with `127.0.0.1`? The error text above is currently socket (`localhost`) specific so that can't be accurate :)

**Comment by matthewmueller** [comment]
Ah sorry, I edited to match it with the screenshot. I tried both :-) 

Unfortunately, I can't reproduce this anymore now that I removed the old tables. I presume it said `127.0.0.1:/tmp/mysql.sock`, but I can't be sure.

**Comment by evanelias** [comment]
It must have been a different error entirely if using `127.0.0.1`, since in that case you're using TCP/IP, and `/tmp/mysql.sock` is not involved in any way. No worries though.
