### ISSUE TITLE
Provide a way for current working directory to be the project root and use skeema

### ISSUE THREAD

**Issue by matthewmueller** [skeema/skeema#148]
This is a minor quality-of-life improvement.

## Problem

After using `skeema init -d schema`, all your databases are in `schema/` but the skeema commands are based on your current working directory. 

It doesn't seem like there's a flag to be able to set the directory to `schema/` to be able to run `skeema diff` or `skeema push`

## Current workaround

```
cd schema/
skeema diff
skeema push
```

## Possible Solution

Offer a "dir" flag.

```
skeema -d schema/ diff
skeema -d schema/ push
```

**Comment by evanelias** [comment]
Thank you for the feature request, but the current behavior of using `cd` is intentional and by design. From the [docs](https://github.com/skeema/skeema/blob/main/doc/config.md#execution-model-and-per-directory-option-files):
```
Most Skeema commands -- including skeema diff, skeema push, skeema pull, and skeema lint -- then operate in a
recursive fashion. Starting from the current directory, they proceed as follows:
1. Read and apply any .skeema file present
2. If both a host and schema have been defined (by this directory's .skeema file and/or a parent directory's),
execute command logic as appropriate on the *.sql table files in this directory.
3. Recurse into subdirectories, repeating steps 1-3 on each subdirectory.
```

Skeema is unopinionated regarding your project root / repo layout. Some users have just a single schema stored in a single flat directory. Others have many schemas and/or many database instances; this can be arranged as a nested tree in a single Skeema-specific repo, or as a subtree within a mono-repo that also contains application code, or even as separate repos for each DB. In all cases the only thing Skeema cares about is that you **`cd` to the right place** first, to unambiguously indicate which directory structure you wish to operate on.

Adding a "dir" flag risks confusion: now there would be two distinct ways to indicate what dirs you want to operate on. Additionally, the interaction between the two methods would be unclear in cases of conflict. What happens if the current dir (or its parent hierarchy) has a `.skeema` file, but you've indicated a different dir in the `--dir` flag -- should those options in the current dir's .skeema file apply or not? And what happens if a user tries setting `dir` *in a .skeema file* instead of the command-line?

Taking all that into consideration, I'm not convinced this would be beneficial. I would suggest that users with a single-dir layout can use simple bash functions for convenience if desired, for example:
```bash
function skeema() {
    cd ~/schema
    /usr/local/bin/skeema $*
    cd -
}
```

**Comment by matthewmueller** [comment]
Fair enough. Thanks for sharing the details!

**Comment by evanelias** [comment]
Sorry, afraid I don't understand the comment in your edit. What issue do you run into by using the `-d` option? If you omit that option, the dir name defaults to being based on the hostname.

Do you just mean that the subsequent examples should include `cd`ing to the directory after init? I hoped this was clear from all the screencasts, which already include it.

**Comment by matthewmueller** [comment]
Ah! I didn't even know these were screencasts, I thought they were screenshots. Maybe adding the play button would help inform people that it's clickable.

<img width="1213" alt="CleanShot 2020-11-13 at 15 50 06@2x" src="https://user-images.githubusercontent.com/170299/99085004-f4295080-25c7-11eb-987d-bb2fb34b83fd.png">

**Comment by evanelias** [comment]
The thumbnail images are dynamically generated by asciinema, that's just how it renders them, it doesn't include a play button.

Anyway the docs are being moved off of GitHub very soon, which will enable direct embedding of the JS asciinema player, which does include the button overlay.
