### ISSUE TITLE
Support for views

### ISSUE THREAD

**Issue by Motaz-Al-Zoubi** [skeema/skeema#154]
Hi thanks for the effort, it is really and interesting tool
I would like to ask for supporting database views as we are using it extensively
is there any near support for this feature?

another question:
how can I specify the source folder in the file system for `skeema push` command so that it doesn't need to search all the working directory.

sometimes when I run the tool it logs the following

```
2020-12-27 17:45:32 [WARN]  Skipping subdirs of /usr/src/app/src/main/java/com/motaz: max depth reached
                            
2020-12-27 17:45:32 [WARN]  Skipping subdirs of /usr/src/app/src/test/java/com/motaz: max depth reached
                            
2020-12-27 17:45:32 [WARN]  Skipping subdirs of /usr/src/app/target/myapp-1.0-SNAPSHOT/WEB-INF/classes/com: max depth reached
                            
2020-12-27 17:45:32 [INFO]  Pushing changes from /usr/src/app/schemas/db/*.sql to myapp_db_1:3306 db
2020-12-27 17:45:32 [INFO]  myapp_db_1:3306 db: No differences found
                            
2020-12-27 17:45:32 [INFO]  Pushing changes from /usr/src/app/schemas/db/Tables/*.sql to myapp_db_1:3306 db
-- instance: myapp_db_1:3306
USE `db`;
CREATE TABLE `Todo` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `summary` varchar(500) NOT NULL,
  `description` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
2020-12-27 17:45:32 [INFO]  myapp_db_1:3306 db: push complete
                            
2020-12-27 17:45:32 [ERROR] Skipped 3 operations due to errors
```
we have  ` [ERROR] Skipped 3 operations due to errors` even though that we have 3 Warning not errors, so does it consider the warning as error?

**Comment by evanelias** [comment]
> I would like to ask for supporting database views as we are using it extensively
> is there any near support for this feature?

Current plan is to support views in the upcoming commercial edition of Skeema. Likely release date is in 3 to 6 months, but no guarantees. Please see #63.

> how can I specify the source folder in the file system for skeema push command so that it doesn't need to search all the working directory.

`skeema` operates recursively from the current working directory. You should always `cd` to the right place before running `skeema`. Please see [examples](https://www.skeema.io/docs/examples/) (right before the "Alter a table" section) or the [config doc section on execution model](https://www.skeema.io/docs/config/#execution-model-and-per-directory-option-files).

> even though that we have 3 Warning not errors, so does it consider the warning as error?

It's logged as a warning because those directories very likely don't contain anything relevant to Skeema, and it isn't fatal to the rest of the command. However, the summary message and exit code both treat it as an error, to ensure the user sees it or to ensure that any automation pipeline treats it as a mistake. I'll try to make the message clearer or more consistent in a future release.

**Comment by evanelias** [comment]
I'm happy to announce that the Premium edition of the Skeema CLI, including full support for views, is now available! Learn more at the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
