### ISSUE TITLE
Add max-user-connections option for skeema init

### ISSUE THREAD

**Issue by splanes** [skeema/skeema#157]
Hi,

When trying to initialize a new skeema with the following command,

`skeema init -h myHost.com -u my_username -p -d schemas --schema=my_schema`

we get the following error message due to a limit in the max number of connections against a host.

```
2021-01-19 13:23:57 [ERROR] Cannot examine schemas on myHost.com:3306: Error executing SHOW CREATE TABLE for
                            `my_schema`.`some_table`: Error 1226: User 'my_username' has exceeded the 'max_user_connections' resource (current value: 10)
```

Unfortunately the max_user_connections option cannot be modified due to a company restriction.

Could you please add a parameter to restrict the max number of connections to establish against a host?

Thanks!

**Comment by evanelias** [comment]
Thank you for the feature request. However, configuring MySQL with a max_user_connections as low as 10 is pretty unusual. Is there any technical reason in your environment for this restriction? Connections are designed to be "cheap" in MySQL, since it uses a threaded connection model rather than a process-based one.

Currently, there are multiple spots in the codebase where Skeema will run upwards of 15 to 20 queries concurrently, in order to speed up its operation. This high concurrency level is only used on queries that are known to be harmless performance-wise, e.g. `SHOW CREATE` to obtain the canonical form of an object, or `SELECT 1 FROM table_name LIMIT 1` to inexpensively check whether a table is empty.

If a limit was implemented, this would greatly reduce Skeema's performance, particularly in cases where the number of tables is high and/or nontrivial network latency is present. This may also be relatively difficult to implement properly, due to a nuance of how connection pools work: Skeema must maintain a separate connection pool for each unique combination of session variables, and different spots in the codebase require different sets of session variables; however this proposed connection limit feature would need to be applied "globally" across all connection pools to a given database instance.

Connection limit aside and speaking more generally: since Skeema is database automation, its user needs a somewhat wide range of permissions in order to function, as compared to e.g. an application user. Just to confirm, are you certain your user has all of the other [privileges required](https://www.skeema.io/docs/requirements/#privileges) anyway?

**Comment by splanes** [comment]
Thank you for such a dedicated response!

Yes, I know 10 connections max is unusual. It's a global company restriction and many many users connect to some DBs with non trivial queries.

Does the program have an upper limit of connections to attempt a request for modifying the max_user_connections for a certain user?

We do have a non-trivial and somewhat expensive alternative that is dumping the schema only of each DB to a dockerized local DB and run skeema against them at the cost of loosing `skeema push`.

I confirm that our users have all required privilegies.

Thank you

**Comment by evanelias** [comment]
It's hard to predict what the exact upper limit would be, for the same reason it would be complex to implement a configurable global limit. Best way to find out may be to test on your local db that has a dump of your real schemas.

Absolute worst-case, I would think around 40 to 45 connections for most commands; less for `skeema init`. 

You can lower that a bit if one of the following is true:
* You have few stored procedures/functions, or none at all
* You have any number of stored procedures/functions, but grant Skeema's user SELECT privs to the mysql.proc table (this doesn't work in mysql 8 though, that table no longer exists)

And then lower further with one of these:
* You configure [workspace=docker](https://www.skeema.io/docs/options/#workspace)
* You keep the default of [workspace=temp-schema](https://www.skeema.io/docs/options/#workspace) but do configure [temp-schema-threads=1](https://www.skeema.io/docs/options/#temp-schema-threads)

In theory this could get the number down to about 20 connections.

**Comment by splanes** [comment]
Done with docker by fetching copies of the remote schemas. Thank you anyways!

**Comment by evanelias** [comment]
@splanes just wanted to mention that today's release of [Skeema v1.5.0](https://github.com/skeema/skeema/releases/tag/v1.5.0) includes some connection management improvements. This should allow Skeema to run with a relatively low server-side value for max_user_connections, without needing the configuration changes mentioned in my previous comment. Skeema now queries max_user_connections automatically, and throttles down pool sizes if the value is low.

There's still the problem of managing multiple separate connection pools, so I'm not positive that all commands will work with a server-side 10 connection limit, but it's worth a try. It will depend a bit on your environment, such as whether or not you have procs/funcs, and whether you have multiple schemas per database instance. I'm hopeful that with a value around 15, everything should work in most environments.
