### ISSUE TITLE
Support for BIT fields

### ISSUE THREAD

**Issue by efixler** [skeema/skeema#16]
Skeema chokes generating a diff on BIT fields:  

2018-02-26 13:00:05 [WARN]  Skipping table income: unable to generate ALTER TABLE due to use of unsupported features
2018-02-26 13:00:05 [DEBUG] --- Skeema-expected
2018-02-26 13:00:05 [DEBUG] +++ MySQL-actual
2018-02-26 13:00:05 [DEBUG] @@ -10 +10 @@
2018-02-26 13:00:05 [DEBUG] -  `is_joint_filer` bit(1) NOT NULL DEFAULT 'b''0''',
2018-02-26 13:00:05 [DEBUG] +  `is_joint_filer` bit(1) NOT NULL DEFAULT b'0',

This looks like a relatively small matter, just a little impedance mismatch on the single-quotes in bit context. Skeema looks like a really well-designed, useful, and straightforward tool. I'd be happy to try and fix this (if desired); a pointer to where in the code to start a fix (I can see where the log happens -
 target.go line 328)

**Comment by evanelias** [comment]
Great catch -- thank you for the bug report! I'm able to reproduce as described.

The bug is with Skeema's handling of default values that use a [bit-value literal](https://dev.mysql.com/doc/refman/5.6/en/bit-value-literals.html), which I must confess is actually a MySQL feature I've never seen before 😅 

If you want to take a stab at fixing this, I'd welcome a PR with open arms :) But also happy to patch on my end; up to you, let me know if you get stuck. There are potentially a couple spots where this would need to be fixed, both in the [Go La Tengo package](http://github.com/skeema/tengo):

1. [tengo.ColumnDefault](https://github.com/skeema/tengo/blob/master/column.go#L9) could be changed to have first-class support for bit value literals. Alternatively (and more simply), it could support them as-is via the existing `ColumnDefaultExpression()` constructor, which creates non-quoted values, and just have the `expression` be `"b'101'"` or whatever, though that's maybe a little hacky. If going the latter route, the comment for `ColumnDefaultExpression()` could just be updated to mention bit literals are another possible use for that constructor.

2. [tengo.Schema.Tables()](https://github.com/skeema/tengo/blob/master/schema.go#L154) is where the main schema introspection logic occurs: this method reads MySQL information_schema data and converts it to Go structs. The handling of default values, in the conditional on lines 154-160, would need to be expanded to handle bit-value literals. I think these will only ever show up in for `bit` type columns, but I'm not certain.

Tengo also has modest unit test coverage (~60%), although no tests currently interact with a live mysqld, so you can't fully test the 2nd item accurately yet. You could maybe have a simple test that bit-value literals work as default types by virtue of adding a bit column to the existing [aTable() test helper](https://github.com/skeema/tengo/blob/master/tengo_test.go#L23). But advance warning, the current test setup is brittle, and many tests make assumptions about what the helpers are returning, so unfortunately it's easy to accidentally break other tests. I plan on reorganizing the test logic in the near future to be a lot more flexible, so no worries if you decide to hold off on this piece!

Once you open a PR in tengo and get it merged, I can update the vendored dep here in skeema.

Thanks again for trying out Skeema and for opening an issue!

**Comment by efixler** [comment]
Thanks, Evan. I've just discovered the bit-literal syntax as well, it is a little odd. Plain old integer would have been preferred here (by me at least :), although I sort of understand that this fits into a general orientation around data 'display' vs specification.

Thanks for the pointers. I will look at this this week. If for some reason I am unable to do this by end of week, I'll ping you back here.

**Comment by efixler** [comment]
@evanelias : https://github.com/skeema/tengo/pull/5

1 test does fail; see the PR + please advise.

**Comment by evanelias** [comment]
Thanks! Just merged skeema/tengo#5. The last remaining step is to update the vendored dep for tengo here in skeema:

* install godep if missing: `go get github.com/tools/godep`
  * I'll move Skeema over to Golang's new official `dep` tool in the near future, but until then, it's still using legacy `godep`
* in $GOPATH/src/github.com/skeema/tengo, `git pull` to get latest commits in master
* in $GOPATH/src/github.com/skeema/skeema, check out a new branch, run `godep update github.com/skeema/tengo` to update the vendored dep, commit, push, open PR

Let me know if you'd like to give the above a try and open a PR? Or I can run it on my end; no real preference, but wanted to give you the opportunity to have the commit here if you want :)

**Comment by efixler** [comment]
https://github.com/skeema/skeema/pull/17 -- I think this should be correct.

Thanks for the vanity credit :)

**Comment by evanelias** [comment]
Looks good, merging momentarily. Thanks again for the issue report and PRs!
