### ISSUE TITLE
Lint enum type

### ISSUE THREAD

**Issue by tonyqiu2020** [skeema/skeema#163]
*Please refer to the Contributing link in the sidebar for guidance.*

MySQL enum type has a lot of [issues](http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/). We would like the linter has the option to enable `enum` type linting. If any column has enum type, the linter will show as a warning.

**Comment by evanelias** [comment]
Thank you for the feature request. For background, which specific enum problems motivate your decision to avoid them? 

Although I myself also usually avoid enums in MySQL, some of the historical problems with them have been fixed in modern versions of MySQL -- including many from the 2011 article you linked. For example, an ALTER to add a new allowed value to the end of the list is now a non-blocking metadata-only change (as long as it isn't the 256th value, but that situation is quite rare).

For other changes, such as reordering the values, removing a value, or adding a value somewhere other than the end, Skeema will already automatically mark this as an unsafe change. That's performed outside of the linter engine, though.

**Comment by tonyqiu2020** [comment]
Thanks for your comments. Historically we have many issues with using ENUM (before using Skeema). I agree with you some limitations can be detected as unsafe change, but since we already have a company-agreed rule to avoid using it, I hope it could be an option for lint, so the tool can show a warning if needed. It will help with our CI automation.

**Comment by evanelias** [comment]
> Historically we have many issues with using ENUM

I am asking you to please clarify what these issues are, specifically. Without this information, I cannot write documentation for this feature, or even justify merging it at all.

For examples of what I'm looking for here, please see the docs on some similar options:

* [lint-has-fk](https://www.skeema.io/docs/options/#lint-has-fk)
* [list-has-float](https://www.skeema.io/docs/options/#lint-has-float)
* [list-has-routine](https://www.skeema.io/docs/options/#lint-has-routine)
* [lint-has-time](https://www.skeema.io/docs/options/#lint-has-time)
* [lint-has-trigger](https://www.skeema.io/docs/options/#lint-has-trigger)
* [lint-has-view](https://www.skeema.io/docs/options/#lint-has-view)

All of these linter options discuss specific reasons why a company would want to disallow each column type or object type. I'll need something similar for enums in order to justify adding the lint-has-enum option. Thanks.

**Comment by tonyqiu2020** [comment]
Companies that restrict the use of ENUM type typically do so for one of these reasons:

- In the older version of MySQL (nonstrict mode), there is no error on inserting invalid ENUM value
- MySQL stores enum values internally as integer keys to reference ENUM members. It's easy to end up referencing the index instead of the value and vice-versa. 
- MySQL stores enum values in order. If the change doesn't preserve the order, it will cause an expensive table copy. 
- String operations and functions do not work on ENUM
- Generally speaking, it is not very flexible to extend compared with the lookup table appoarch.

**Comment by evanelias** [comment]
Thank you. I'll take this under consideration and will review your PR once I'm able to devote more time to open source, likely in a few weeks.

**Comment by evanelias** [comment]
Merged associated PR #164, closing this too. Thanks!
