### ISSUE TITLE
Functions Not Being Written Before Needed

### ISSUE THREAD

**Issue by chrisajohn80** [skeema/skeema#168]
**Describe the bug**
When I try to populate an empty database, Skeema is not writing objects in the correct order.  I have a view that references a Function.  The function is not yet written and so it cannot create the view and throws an error.

**Environment**
- Newest Premium Skeema Version
- MySql 5.7 running on Docker

**To Reproduce**
Create a view that references a function.  Try to push changes to database.

**Expected behavior**
I expected the function to be written first so there are no errors.

**Comment by evanelias** [comment]
Thank you for the report! I've verified the bug as you've described.

The fix for this specific case is straightforward (Skeema should always apply DDL to views *after* DDL for procs/funcs), but it uncovered another more complex related issue in the push-to-empty-db case: if some views refer to *other views*, they must be created in a specific order, i.e. *within* just the list of views to create.

Skeema's *workspace* logic actually handles all of this correctly -- that's the piece that translates your \*.sql files into an in-memory representation. But currently that view ordering/dependency logic from the workspace isn't serialized or transferred to the diff/push applier yet, which will be needed for the full proper fix here.

In terms of fix ETA, I'll do a bit more research and then will email you before end-of-day.

In the meantime, as an awkward workaround in the push-to-empty-db case, you could first push with [--ignore-table](https://www.skeema.io/docs/options/#ignore-table) on the command-line to skip the view(s) in question, and then push again without that:
```
skeema push --ignore-table='^(some_view_name|other_view_name)$'
skeema push
```

**Comment by evanelias** [comment]
I'm happy to announce that Skeema v1.5.3 has been released today, and the views ordering issue is now fixed in the Premium CLI. This includes proper ordering for functions before views (thanks again for the issue report!) as well as the related problem of proper ordering for views that query other views.
