### ISSUE TITLE
Writing Output Incorrect Order With Foreign Keys

### ISSUE THREAD

**Issue by chrisajohn80** [skeema/skeema#169]
**Describe the bug**
When I am populating a database from scratch, it writes the SQL in the wrong order when there are foreign keys.

**Environment**
- Skeema version: 1.5.3 Premium
- Database vendor, version, OS/platform: MySql 5.7, Windows 10

**To Reproduce**
Create two tables, one that has a foreign key constraint to the other.  Run skeema diff.

**Expected behavior**
The SQL should run in the correct order where the table that has a column used as a foreign key is written before the table that needs to use it.

**Comment by evanelias** [comment]
Thank you for the report. As far as I know the Foreign Key mechanics are still working as intended... In this situation, are you actually encountering an error when using `skeema push` with FKs to an empty DB? Or are you just observing the order appears wrong when viewing `skeema diff` output?

By default, `skeema push` operates with MySQL's  [`foreign_key_checks=0`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_foreign_key_checks) variable set at the session level for its connections, which means the table order should not actually matter when populating a database from scratch.

Core tools such as `mysqldump` actually use the exact same approach. Because MySQL permits circular foreign key relationships between two or more tables, a "correct" legal order to create the tables may not even exist if FK checks are enabled.

That said, when altering an *existing* database with a mix of column additions, index additions, and FK additions, there may be cases where you need to manually order your commits and do multiple pushes in order for the operation to succeed. This is necessary due to the wrinkles of how MySQL's `foreign_key_checks=0` operates: it allows you to add FKs referencing tables that don't exist yet, but it does *not* allow referencing nonexistent *columns* of tables that *do* already exist. Skeema does not attempt to unwind such dependency chains at this time, but it could be treated as a feature request if it's actually impacting users.

Separately, `skeema push` does have [an option to enable MySQL's `foreign_key_checks` at the session level](https://www.skeema.io/docs/options/#foreign-key-checks), but its use-cases should be pretty rare.

**Comment by evanelias** [comment]
Actually, I misspoke in the 4th paragraph: Skeema will actually already use the correct order for ALTERs that add FKs, as long as the FKs are within a single database schema. ALTERs that add FKs get separated out and executed after other table-related operations.

**Comment by chrisajohn80** [comment]
Thank you for the detailed explanation.  One of the ways I'm using Skeema is to create scripts that I use to create databases for unit testing and local development.  So it seems like I need to turn off foreign key checks when using these scripts in this way.

There are some in my organization that aren't comfortable yet with Skeema making changes in production.  My plan was to run the "diff" command and output it to a file during the pipeline run so someone can run it manually.  I guess we will need to either update the script manually to get things in correct order, or run our session using the correct flags like you mention. With our existing database in production the table changes will be minor in count so easier to fix manually.

BTW I can confirm with our database that the other issue I had with views went away with 1.5.3.  Appreciate it.

Consider this closed, thanks!

**Comment by evanelias** [comment]
Awesome, thanks, glad to hear!

Yes, sounds like the easiest fix would be to ensure foreign_key_checks=0 is set for sessions. If folks are running the SQL manually (or piping generated SQL to `mysql` command-line client), you could have your pipeline prepend `SET SESSION foreign_key_checks=0;` to the SQL right before the output from `skeema diff`. This should also work for more automated solutions, although languages with connection pools may require more complicated ways of setting session vars.

btw, would it be useful if `skeema diff` output included this line automatically in the future? I could see that being beneficial so that this behavior is more explicit.

**Comment by chrisajohn80** [comment]
Interesting idea.  Yes, I do think it would be helpful so we know what is happening.  Also add it to the docs if it isn't out there already.
