### ISSUE TITLE
Foreign key diff involving ON UPDATE/DELETE RESTRICT vs. [nothing] triggers "unable to generate DDL" and skips table

### ISSUE THREAD

**Issue by andywall66** [skeema/skeema#170]
I'm comparing my local schema to an Amazon RDS MySQL instance. Everything was in sync with no issues from Skeema, even with my local machine version @ 8.0.19 vs. RDS version @ 5.7.33. 

Today, I upgraded the RDS instance - using the AWS console tool - to 8.0.23 (their latest version). Now, when I do a diff, I get a warning/table skip on almost every table with foreign keys. It has to do with the lack of the `RESTRICT` definitions in my local copy. Here's an example (I get 44 of these):

```
2021-09-09 22:24:53 [WARN]  Skipping table `tag_settingsform`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2021-09-09 22:24:53 [DEBUG] --- Expected CREATE
2021-09-09 22:24:53 [DEBUG] +++ MySQL-actual SHOW CREATE
2021-09-09 22:24:53 [DEBUG] @@ -9 +9 @@
2021-09-09 22:24:53 [DEBUG] -  CONSTRAINT `fk_tag_settingsform` FOREIGN KEY (`settingsform_id`) REFERENCES `settingsform` (`id`) ON UPDATE CASCADE
2021-09-09 22:24:53 [DEBUG] +  CONSTRAINT `fk_tag_settingsform` FOREIGN KEY (`settingsform_id`) REFERENCES `settingsform` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
```

To make sure I'm not crazy, I re-read the official docs from MySQL:
_Specifying RESTRICT (or NO ACTION) is the same as omitting the ON DELETE or ON UPDATE clause._

So, it's a cosmetic difference...

I thought maybe it was a minor version difference from my 8.0.19 vs. their 8.0.23, so I upgraded local to 8.0.25 (closest I could get), but with the same issue. So, I thought it might be some peculiarity/configuration with the specific RDS flavor of MySQL...

...but then I got the same `SHOW CREATE TABLE` discrepancy on my own machine by using MySQL Workbench, changing a table to `ON UPDATE CASCADE` and then back to `ON UPDATE RESTRICT`, and now `SHOW CREATE TABLE` explicitly includes it and thus triggers an error like above.

The question is: what can be done?

Perhaps there is a flag I could change in MySQL, to force it to include/ignore the `RESTRICT` statements in `SHOW CREATE TABLE`, but I couldn't find anything. Alternatively, could this be mitigated by Skeema? Seems appropriate for when `exact-match=false` ?  Skeema is already saving the day for me in so many ways, so if this had to be a Pro feature I would not be opposed.

**Environment**
Skeema version: 1.5.1-community
Remote:    Originally MySQL 5.7.33; issue occurs after upgrade to 8.0.23. AWS RDS.
Local:   MySQL 8.0.19; same issue after upgrade to 8.0.25. MacOS Big Sur.

**To Reproduce**
Would be quite difficult to 100% give a path but hopefully the above is on the right track?

**Comment by evanelias** [comment]
Thank you for the thorough report! Coincidentally this was something I just found and fixed a few days ago in commit 3b52e87. Here's the backstory:

* Historically (MySQL before 8.0, and all versions of MariaDB), lack of a clause in a foreign key was treated as `RESTRICT` in `information_schema`. Even if you specify `RESTRICT` explicitly, it was hidden from `SHOW CREATE TABLE`, because it was the default. Meanwhile, although `NO ACTION` is completely equivalent to `RESTRICT`, specifying `NO ACTION` explicitly *would* show up in `SHOW CREATE TABLE`. Skeema handled all of this correctly for pre-8.0.
* MySQL 8.0 reversed all this behavior for no apparent reason: lack of a clause in a foreign key is now treated as `NO ACTION` in `information_schema`, and `SHOW CREATE TABLE` now hides `NO ACTION` and no longer hides `RESTRICT`.
* If a DB was created prior to 8.0 and then upgraded to 8.0 in-place, any pre-existing FKs retain their previous clause (often `RESTRICT` since this was the old default). This generally means `SHOW CREATE TABLE` now has a ton of `RESTRICT` clauses for these tables. 
* Unfortunately Skeema had a logic bug which didn't handle this correctly for 8.0, resulting in the "unable to generate DDL" warning if an 8.0 table has any `RESTRICT` FKs. This is rare for tables created fresh in 8.0, and the test suite previously didn't cover it since `RESTRICT`, `NO ACTION`, and (no clause at all) were all equivalent anyway. But it's more common for tables with FKs created prior to 8.0 and then upgraded, due to the previous bullet.

I have no idea why this behavior changed in MySQL 8, but there are hundreds of these tiny little changes they put in there, and some of them *only* come up when you upgrade. See commit 911c2ca for another recent one (unrelated to foreign keys) which took several full days to find and resolve :(

Anyway, happy to say it's fixed in the main branch, just isn't in a binary release yet.

> Skeema is already saving the day for me in so many ways, so if this had to be a Pro feature I would not be opposed.

Out of curiosity, are there any potential future features that could make the Premium products more appealing to you?

This bug is fixed in Community, and hopefully that will remain the case for any similar bug fixes in the future. But frankly right now everything really hinges on getting the Premium products to a point where more users find them compelling...

**Comment by evanelias** [comment]
One remaining problem I should mention: the bug is fixed in that these tables will no longer be skipped. However, if your local *.sql files have (no clause) but your mysql 8 DB's `SHOW CREATE TABLE` now has `RESTRICT`, Skeema's generated DDL will include attempts to drop the FKs with these RESTRICT clauses and re-create them without those clauses.

I'll try to improve this further so that changes between RESTRICT and NO ACTION are generally suppressed by default (with `exact-match=false`) and will close this issue then.

In the meantime, one workaround is to run `skeema pull` once, to bring the RESTRICT clauses into the *.sql files.

**Comment by andywall66** [comment]
Evan, that's awesome, way to be on top of this. I will grab the repo and do a build and see how it goes.

As far as compelling paid upgrades... I think a native GUI would complement Skeema quite well. I fully appreciate how GitHub built their desktop tool to really bring their workflow to people. Skeema is the type of workflow that everyone should have, and lot of people (like me) love this stuff (I use SourceTree on my desktop). Or license it to someone who's already charging $$$ for a DB admin tool like Navicat for them to resell as an upgrade package. Not sure!

**Comment by evanelias** [comment]
Just pushed another commit to main branch which suppresses diff clauses that only change between RESTRICT and NO ACTION by default (with exact-match=false). 

Closing this out, but will comment again here once the next binary release is out. No ETA yet, definitely not this month though since the previous release was last week.

> As far as compelling paid upgrades... I think a native GUI would complement Skeema quite well.

Appreciate the suggestion, but regrettably the development time required for a native GUI just isn't feasible. At this point my max timeframe is a couple more months to make the existing premium products more compelling... hopefully I can think of something to turn this ship around.

Anyway if you come across some area in the CLI where an obvious improvement would be worth paying for, please drop me a line. Thanks again.

**Comment by evanelias** [comment]
Just a quick update that Skeema v1.6.0 has been [released today](https://github.com/skeema/skeema/releases/tag/v1.6.0), containing the fix for this bug.
