### ISSUE TITLE
Ignore procedures or make it environment dependent

### ISSUE THREAD

**Issue by tonyqiu2020** [skeema/skeema#171]
We have some use cases to create store procedures. Currently the issue is that CREATE statement will include the skeema user name. In our environments, the different databases have different usernames for skeema migration user. It makes the SQL files not environment independent.  Any suggestions about that? 

On the other hand,  is there a way to ignore those procedures like we can ignore tables?

**Comment by evanelias** [comment]
> Currently the issue is that CREATE statement will include the skeema user name.

An option is planned for v1.6.0 of the premium CLI to strip DEFINER clauses from *.sql files. See #146.

> is there a way to ignore those procedures like we can ignore tables?

Also planning on `ignore-procedure` and `ignore-function` options in v1.6.0 of the premium CLI. No open issue yet so will keep this open to track.

Release date for v1.6.0-premium is still TBD, but likely target is sometime in November.

Just to set expectations though, all feature enhancements relating to stored procs/funcs will only appear in the paid Premium edition and not in the open source Community edition. The only reason procs/funcs are in the Community edition at all is because a company sponsored the initial development work. The support burden for this functionality has been extremely time-consuming though, and it isn't practical to spend unpaid time improving it. Thanks for understanding.

**Comment by tonyqiu2020** [comment]
Thanks for the quick response. It is possible to completely remove procedure/function support from the community edition, just like the view did? That would be much easier actually.

**Comment by evanelias** [comment]
> possible to completely remove procedure/function support from the community edition

No, that would be a ton of work and would go against the original sponsored development agreement to include it.

> just like the view did?

Views were never supported in the community edition in the first place; they were never "removed". The code to add them was only implemented in the premium edition.

> That would be much easier actually

If your company depends on Skeema, why not advocate for your company to become a premium subscriber once it supports the functionality you need here? This is clearly the easiest path, and it benefits both your company as well as the ongoing development of Skeema.

The current situation is pretty dire: if the vast majority of companies using Skeema remain unwilling to provide any monetary support for this software, all development on the community edition will be cease and this repo will be archived. This will happen within a few months unless the revenue situation improves.

**Comment by evanelias** [comment]
Happy to announce that today's release of [Skeema Premium CLI v1.6.0](https://www.skeema.io/download/) includes new global regex options [ignore-proc](https://www.skeema.io/docs/options/#ignore-proc) and [ignore-func](https://www.skeema.io/docs/options/#ignore-func), to permit ignoring stored procedures and functions (respectively) based on name pattern-matching.
