### ISSUE TITLE
Ability to pass --schema to diff and push

### ISSUE THREAD

**Issue by DanyC97** [skeema/skeema#173]
*Please refer to the Contributing link in the sidebar for guidance.*

Hi @evanelias ,

first of all genuine kudos for this tool, is impressive. While i was running a spike internally to see if is a good fit for my team (running against RDS Aurora mysql) i thought that would be nice for `skeema {diff, push}` to support the `--schema` flag.

I'm aware of the `--ignore-schema` but because we have various folks working on same db instance adding/ removing schemas is a bit hard to stay on top with the regex. Having the flag i can then implement in the PR something like `skeema push/ diff <env> --schema <only what i'm interested>` and in this way i'm 100% confident i don't risk to affect anyone's schemas.

Hope you find this use case valid, i understand this might not be available on the community edition. Once i finish my spike and convince my mgmt, we will need the paid version anyway due to views support.

**Comment by evanelias** [comment]
Thank you for your interest. It is not possible to supply `--schema` on the command-line for most commands because this conflicts with the way that the [schema option](https://www.skeema.io/docs/options/#schema) works in `.skeema` files. 

However, I believe the existing functionality already covers your use-case:

Most Skeema commands operate [recursively from the current working directory](https://www.skeema.io/docs/config/#execution-model-and-per-directory-option-files). So the easiest solution is to just `cd` to the desired bottom-level schema subdir before running `skeema diff`, `skeema push`, etc.

Another solution is to use [environment names in .skeema files](https://www.skeema.io/docs/config/#specifying-options-via-option-files). By default, `skeema init` places `schema=foo` in the bottom-level `.skeema` file outside of an environment, since the default assumption is that the schema name is the same between dev/prod/whatever. However, you can leverage environments for other purposes, for example changing that bottom-level `.skeema` file to look like this:
```
[production]
schema=foo

[danyc97]
schema=foo
```
This way, even from a higher-level directory, your schema will only be pushed upon running either `skeema push` (since the default environment is "production") or `skeema push danyc97`. But if a coworker runs e.g. `skeema push bob`, your subdir will be ignored if it doesn't ever define environment "bob".

**Comment by DanyC97** [comment]
fair point, thanks @evanelias . And thanks for wise suggestions 👍

**Comment by evanelias** [comment]
No problem, thanks for the question! A few other folks have also had similar questions over the years, so clearly the docs could be clearer on this. So I've now added it to the [FAQ](https://www.skeema.io/docs/faq/#i-have-several-database-schemas-how-do-i-interact-with-just-one-at-a-time) today, and also linked to the new FAQ entry in the docs for the [schema](https://www.skeema.io/docs/options/#schema) and [ignore-schema](https://www.skeema.io/docs/options/#ignore-schema).
