### ISSUE TITLE
Ability to ignore column order

### ISSUE THREAD

**Issue by TurqW** [skeema/skeema#178]
In legacy production databases with multiple instances, it's not always feasible to wait for a column reorder operation to execute against a large table, particularly if there's a chance of it being interrupted by a  constraint violation or the like. A flag to ignore column order when diffing/pushing would be very helpful.

**Comment by evanelias** [comment]
Thank you for the feature request!

Just to confirm I understand the use-case: you have multiple shards in one environment (for example using [host-wrapper](https://www.skeema.io/docs/options/#host-wrapper)), and some shards have differing column orders for some tables, but aside from that there's no other real drift/differences between shard state?

This could be added in theory, but I'm not sure how common this situation is, if I understand it correctly. I've encountered this situation once before, but a lot of other shard drift was present in that case, so unfortunately a new option just for ignoring column order wouldn't have been sufficient there.

Longer-term, options/commands to ignore drift (e.g. a way to only push the changes represented in a single git commit, ignoring all other preexisting state differences) may be explored, which might solve this as well. But no ETA yet, it's still in the early planning stages.

**Comment by WaltWh** [comment]
It's a distributed system across multiple datacenters, with an entirely separate DB server per datacenter but identical service code. We're trying to finally unify the DB schemas (in addition to the ordering differences, some have different column sizes in places) but I've ended up having to manually swap in different versions of the Really Big Table definition before doing a skeema push, because those column reorders simply won't finish.

**Comment by evanelias** [comment]
Thanks, I see. So I'm guessing you're using different environment names, or maybe swapping out the .skeema file, rather than using something like `host-wrapper` since you can't safely push the same .sql to multiple instances at once.

If your company is a premium subscriber on a tier which includes technical support, please reach out and we can try to determine an ETA for implementing this and discuss some workarounds in the meantime. Can't guarantee it will appear in the Community Edition though, it depends on whether it's beneficial for enough users for that to make sense.

**Comment by evanelias** [comment]
This feature will be present in Skeema v1.11.0: to suppress generation of ALTERs that only reorder columns, you can enable new option `lax-column-order`. Target release date is in September.

**Comment by evanelias** [comment]
Skeema v1.11.0 is [now available](https://www.skeema.io/blog/2023/09/26/v1110-released/), containing the new [lax-column-order](https://www.skeema.io/docs/options/#lax-column-order) option. Thanks again for the excellent feature request!
