### ISSUE TITLE
linux arm64 builds

### ISSUE THREAD

**Issue by andyli** [skeema/skeema#179]
It would be great if there are official Linux arm64 builds.

We're using [VS Code devcontainer](https://code.visualstudio.com/docs/remote/containers) in a M1 Mac, as such, the devcontainer is running arm64 Linux.

**Comment by evanelias** [comment]
Thank you for the feature request. Linux arm64 builds are planned soon, especially as AWS Graviton is gaining popularity. 

I had hoped to include Linux arm64 builds in the last release, but ended up bumping them for time. Hopefully they'll make it into the next release. The only blockers are logistical: web/doc updates, and having 8 additional build archives to juggle for each release, since Linux arm64 means providing each archive type -- tgz, rpm, deb, apk -- for Community and Premium editions.

**Comment by evanelias** [comment]
Update on this issue: Linux arm64 builds will be available beginning with the next release of Skeema, which should be later this month. Just waiting for the next quarterly MySQL 8 release to happen first, to ensure compatibility. (I suspect MySQL 8.0.28 may be out in 1-2 weeks, based on previous MySQL release schedules. Also possibly waiting on a GA release of MariaDB 10.7, since the 10.7.1 RC came out two months ago. Entirely possible that the pandemic could affect these schedules though.)

One other thing to note: @andyli for your specific case of running Skeema in a Docker container on an m1 Mac, I've found the amd64 (x86_64) Linux builds actually seem to work, since Docker for Mac uses QEMU to emulate x86 on ARM. It will just be a bit slower and use more CPU. You won't be able to install via the RPM or DEB files (they'll complain about arch mismatch), but if you use the tar.gz it should be fine. Alpine's `apk` also doesn't seem to complain about arch mismatch, fwiw.

**Comment by evanelias** [comment]
Happy to announce that Skeema v1.7.0 has been [released](https://www.skeema.io/blog/2022/01/24/v170-released/), including builds for linux/arm64!
