### ISSUE TITLE
Unknown option "generator" error during migration

### ISSUE THREAD

**Issue by funkswing** [skeema/skeema#183]
This issue just started happening. The `.skeema` config file has always contained this line:

```
generator=skeema:1.5.0-community
```

Is there any path to debugging this issue?

**Comment by evanelias** [comment]
Please paste the output of running `skeema version` on the machine that is showing this error.

**Comment by evanelias** [comment]
Typically "unknown option" errors are just caused by using a mix of different Skeema versions on the same repo. The [generator](https://www.skeema.io/docs/options/#generator) option didn't exist prior to 1.5.0, so I'm assuming that was the cause here, but please re-open if you're still getting this error even after upgrading.

When running Skeema from multiple different machines, ideally use the same version everywhere to ensure consistent behavior. If installing it via automation, you could pin a specific version in the URL instead of using `latest`.

The Premium edition also includes functionality to help stay current with the latest release: it will log a message if your version is out-of-date, and provides [single-command self-update ability](https://www.skeema.io/docs/commands/update/), in addition to providing secure [Linux package manager repos](https://www.skeema.io/docs/install/premium/).
