### ISSUE TITLE
Skeema push + table name case sensitivity 

### ISSUE THREAD

**Issue by SebastienMelki** [skeema/skeema#185]
Hello,

I have a table called an_hasLyrics (with a capital 'L') and I need skeema to create the table with the same case sensitive name. 

![image](https://user-images.githubusercontent.com/5787993/172415004-c3523c53-5a5a-4b98-b383-a11d3f4e2024.png)

But whenever I run 'skeema push local-env' , the table gets created as an_haslyrics  (notice the lowercase 'l')

<img width="650" alt="image" src="https://user-images.githubusercontent.com/5787993/172415155-3d529131-26ba-4add-ad23-b4a9f847fe28.png">

My local lower_case_table_names is set to 0 

Is there any special flag I need to pass to skeema when I'm pushing an environment so that it respects the casing of the table name?

I am using skeema version 1.4.7, commit df922ef8cbc92f7a3c11a24790aa503970b7a237, released 2021-01-05T23:36:31Z

Thank you!

**Comment by SebastienMelki** [comment]
Thank you @evanelias, I rechecked my configuration files and one of my databases had the lower_case_table_names set to 1, which was causing my issue. 
I removed that setting and all worked as expected :) 

I will close the issue. Thanks again

**Comment by evanelias** [comment]
No worries, that database setting is definitely tricky! If you're juggling different `lower_case_table_names` values, I would definitely recommend upgrading to Skeema v1.8.0 anyway, since this version is the first time non-zero values of `lower_case_table_names `are fully supported.

Relatedly I just published a [new blog post](https://www.skeema.io/blog/2022/06/07/lower-case-table-names/) with a deep-dive into `lower_case_table_names` and OS portability / name-case issues, since it's a common pain point!
