### ISSUE TITLE
Question: how to compare databases with different names on the same instance / env

### ISSUE THREAD

**Issue by avifatal** [skeema/skeema#19]
Hi,
So my usecase is a little bit different.
I have 3 mysql installations with 5 environments lets call them local, mid, production.

`local.dev_product` - for dvelopers each on his own computer.
`mid.qa_product` - for QA team
`mid.content_product` - for Content team
`mid.staging_product` - for management review and UI examining.
`production.production_product` - going live.

So I need a way to diff between the 3 `mid` databases since they are with a different name.
The mid instance will grow more.

Possible? same instance different database? As far as I remember its possible with old mysqldiff tool.

Thanks

**Comment by evanelias** [comment]
Sure, you can define 5 environments in your `.skeema` file. Three of them will have the same `host` but that's not a problem.

You could do this via `skeema init` to setup the production environment, and then edit `.skeema` after to add the other environments. (Or you could use `skeema add-environment`, but it won't handle this case well, assuming you want a "flat" dir structure instead of separate subdir levels for host and schema name)

```
$ mkdir schemas
$ cd schemas
$ skeema init -h whatever.prod.hostname.is.com --schema production_product --dir .
$ vi .skeema
```

And in `.skeema` you want it to end up looking something like:
```
[local]
host=127.0.0.1
schema=dev_product

[qa]
host=whatever.mid.hostname.is.com
schema=qa_product

[content]
host=whatever.mid.hostname.is.com
schema=content_product

[staging]
host=whatever.mid.hostname.is.com
schema=staging_product

[production]
host=whatever.prod.hostname.is.com
schema=production_product
```

And then to diff the filesystem vs a specific environment, use `skeema diff staging` or whichever environment you want to work against, and then `skeema push staging` if you want to apply the version in the filesystem to the staging environment, or `skeema pull local` if you want to take the version in dev and have the filesystem match it, etc.

Skeema does not yet offer a way to diff the environments against *each other*, though, as that's not really the purpose of the tool. `mysqldiff` is a better solution if you just want to diff live schemas against each other instead of using a local repo of schema files.

**Comment by avifatal** [comment]
Thanks. did that.
I have 1 more question if I may.
1.  > Skeema does not yet offer a way to diff the environments against each other

Please explain, maybe I did not explain myself. while im developing im adding and removing tables and columns. when I deploy from dev to qa qa I want to build an SQL script review it and run it. so all the changes will be applied in qa.

Than when going from QA to content and on and on.
Whats most critical for me is to review the upgrade sql script and put it in git. 
is this something skeema does?

I want that features in order to avoid mainaining upgrade scripts when using ORMs such as eloquant.

Thanks.

**Comment by evanelias** [comment]
The purpose of Skeema is to eliminate the need for a "SQL upgrade script" or any ORM-based migration tool or migration files. With Skeema, you have a repository (git or whatever SCM you prefer) of `CREATE TABLE` files, and maintain the history that way. You do not keep a "SQL upgrade script" in git or anywhere. Skeema uses a purely declarative approach: you can change the `CREATE TABLE` files, run `skeema diff` to preview auto-generated ALTERs for a specific environment, and `skeema push` to actually run those ALTERs. All operations/comparisons are between the repo of `CREATE TABLE` files and 1 environment.

A preview of what this actually looks like, with asciinema videos, is documented at https://github.com/skeema/skeema/blob/master/doc/examples.md.

The advantage of this approach is that it doesn't require linearly stepping through each individual change in an upgrade script or migration directory. Skeema automatically figures out what changes need to be made in order to have an environment become equivalent to the state in the schema repository. Adding a new environment is easy; adding new developers to the team is easy; and there's no risk of accidentally "skipping" individual migrations or steps in an upgrade file.

In your multi-environment example, the workflow would look like:

1. Develop using whatever flow you normally prefer. Maybe that's directly running CREATE TABLE, ALTER TABLE, etc in local dev environment manually. If so, do that as normal and then use `skeema pull local` to make the schema repo reflect the changes you just made in local dev.

2. If desired, commit those changes to the schema repo to git, open a PR, have a teammate review, whatever your normal review process is.

3. Once you're ready to apply changes to qa, run `skeema diff qa` to auto-generate a series of DDL statements that will make qa reflect the filesystem. If these look good, run `skeema push qa` to execute them.

4. Repeat step 2 for each environment.

A more detailed version of this is documented in https://github.com/skeema/skeema/blob/master/doc/workflow.md

**Comment by avifatal** [comment]
Thank you for the detailed answer. Understood.
