### ISSUE TITLE
Negative lookahead in --ignore-schema regex?

### ISSUE THREAD

**Issue by markododa** [skeema/skeema#192]
Is it possible to use negative lookahead in --ignore-schema

I'm getting the error message
`Invalid regexp for option ignore-schema: ^(?!maindb).*$`
Is negative lookahead not supported or am i missing something?

**Comment by evanelias** [comment]
Sorry, Golang's [regular expression engine](https://pkg.go.dev/regexp) doesn't support negative lookahead. (Skeema is written in Golang, and the regex options all use Golang's regular expression engine.)

If you're only trying to track a subset of your schemas in version control, this can usually be accomplished by some combination of:

* running [`skeema init`](https://www.skeema.io/docs/commands/init/) multiple times, specifying [--schema](https://www.skeema.io/docs/options/#schema) each time for just the schemas you want. This will create a more "flat" dir hierarchy where each subdir specifies both host and schema, instead of having an extra middle subdir level for the host, but you can freely edit/rearrange this if desired.
* hand-editing your subdir layout and .skeema files to remove ones you don't want
* using .gitignore 
* using [skip-new-schemas](https://www.skeema.io/docs/options/#new-schemas) so that [`skeema pull`](https://www.skeema.io/docs/commands/pull/) doesn't ever bring back the ones you don't want
* crafting a somewhat-hacky [ignore-schema](https://www.skeema.io/docs/options/#ignore-schema) regex that still filters out what you need without using negative lookahead
