### ISSUE TITLE
FR: shell completion support

### ISSUE THREAD

**Issue by chenrui333** [skeema/skeema#197]
It would be nice to have shell completion support for bash, zsh, fish. Thanks!

**Comment by evanelias** [comment]
Thank you for the feature request. I have no familiarity with implementing shell completions, so adding "help wanted" label in case an external contributor is interested in tackling this.

Are you thinking about this just for command names (diff, push, etc), or for environment names (production, staging, etc) as well?

I'd assume the command names would be easy, but that's very low benefit since most Skeema commands are just a few letters long... I'm not sure that would be worth implementing alone.

However, completing environment names would be more difficult. To build a list of all environment names, it would need to examine all global option files, as well as all .skeema files in the parent dir hierarchy, the current directory, and all subdirs recursively.

**Comment by evanelias** [comment]
Hi @chenrui333, just following up, could you please clarify which things you were desiring completions for? (commands? environment names? long-form option names?) Just trying to better understand the need. Thanks.

**Comment by evanelias** [comment]
Looking at the completions implementation in https://github.com/spf13/cobra as an example, it seems this would require several thousand lines of code and significant time to implement. And the value proposition seems questionable:

* Majority of skeema commands are only four letters long (`diff`, `pull`, `push`, `init`, `lint`). `format` is only six. `add-environment` is an exception but isn't used often.
* Some options have long names, but typically they should go in a `.skeema` option file if used consistently. And for options often used on CLI, most of those should have one-letter short-form versions already. More short-form flags can be added by request if there's a real need among multiple users.
* Environment names are user-defined, e.g. you can use "dev" instead of "development" to save on typing if you want
* A decent number of companies primarily run `skeema` from CI and/or custom automation wrappers rather than running it directly from the shell anyway

Issue creator hasn't elaborated on the need/use-case, so closing this for now. Happy to reopen if there's a real need among multiple users who can elaborate on the requirements, or if there's an external contributor who can implement this with minimal assistance.
