### ISSUE TITLE
Comma separated list of schemas does not work

### ISSUE THREAD

**Issue by pludi** [skeema/skeema#20]
When defining a list of schemas to pull in the config file, only the first item of the list gets pulled into the current directory. Expected would be the pull of all schemas into their respective directories.

Steps to reproduce:

1.  Create new databases and tables:
```
CREATE USER 'skeema'@'%' IDENTIFIED BY 'skeema';
GRANT SELECT ON *.* TO 'skeema'@'%';
GRANT ALL ON _skeema_tmp.* TO  'skeema'@'%';
CREATE DATABASE test01;
CREATE DATABASE test02;
CREATE TABLE test01.testtable01 (id INTEGER NOT NULL PRIMARY KEY, val VARCHAR(255));
CREATE TABLE test01.testtable02 (id INTEGER NOT NULL PRIMARY KEY, val VARCHAR(255));
CREATE TABLE test02.testtable03 (id INTEGER NOT NULL PRIMARY KEY, val VARCHAR(255));
CREATE TABLE test02.testtable04 (id INTEGER NOT NULL PRIMARY KEY, val VARCHAR(255));
```
2.  Create the `.skeema` file:
```
[test]
host=127.0.0.1
port=3306
user=skeema
password=skeema
schema=test01,test02
```
3. Fetch the schema: `skeema pull test`

Expected result: A tree like `127.0.0.1/{test01,test02}/testtable??.sql`

Actual result: Only the tables from DB `test01` are pulled into the current directory. Likewise, when the order is reversed, the `test01` tables are removed and files for the `test02` tables are created.

**Comment by evanelias** [comment]
Thank you for trying out Skeema! This feature is actually working as designed; its behavior is just a little different than what you are expecting.

The key is that each of the schema subdirs `127.0.0.1/test01/` and `127.0.0.1/test02/` should have its own `.skeema` file, specifying each schema name for that dir. So you'd want `127.0.0.1/test01/.skeema` with just the line`schema=test01`, and `127.0.0.1/test02/.skeema` with just the line `schema=test02`. The other configurations, for host/port/user/password, should stay in the parent `127.0.0.1/.skeema` -- the options specified there will automatically be inherited by its subdirs, cascading sort of like how Apache .htaccess files cascade.

But, there's no need to set up these directories and .skeema files by hand! If your goal is to build a tree like `127.0.0.1/{test01,test02}/testtable??.sql`, please use the `skeema init` command once as your first step to build this tree. This command will examine what database schemas exist on the supplied database instance, and then will create a directory structure with the correct .skeema files and *.sql files for each schema it finds (aside from system schemas like `performance_schema`, `information_schema`, `mysql`, etc which it automatically ignores). After the one-time init step, you can use `skeema pull` any time to update the filesystem with any out-of-band changes made to the database (i.e. changes made outside of Skeema).

For examples on how to use `skeema init`, please see the [examples doc](https://github.com/skeema/skeema/blob/master/doc/examples.md) and [workflow doc](https://github.com/skeema/skeema/blob/master/doc/workflow.md). The main connection options are identical to those of the `mysql` command-line client, in terms of how to supply host, port, username, password.

Again, by default, `skeema init` will create directories for every non-system schema it finds. But it also supports a couple alternative workflows:
* If you intentionally only want a directory for just one specific schema, ignoring all others, you can specify this at init time via `skeema init --schema foo`. In this case, Skeema will collapse the instance and schema directories into a single flat dir with just that one schema, and subsequent calls to `skeema pull` won't create dirs for any other new schemas. This is a bit different than the use-case you're describing here though.
* If you want to *ignore* one or more non-system schemas, you can use the new [ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) option to supply a regex. For example, `skeema init --ignore-schema='^foo'` will ignore any schema names that begin with "foo".

So that all said, back to comma-separated schema name lists -- what do these do? This feature is a bit of an edge-case. It is designed to support sharding schemes where multiple schemas on the same mysql instance intentionally have the exact same set of tables. So specifying `schema=test01,test02` means that you are declaring test01 and test02 to be two shards with the same exact set of table names/structure. This is why `skeema pull` only looks at test01 in this case; it pulls from the first schema name on the list, since looking at subsequent ones is unnecessary. But meanwhile commands like `skeema diff` and `skeema push` can optionally run against all listed schemas, allowing a workflow for applying a schema change to all shards.

The comma-separated schema list (and sharding support in general) is described a bit more in the doc for the [schema](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) option. I hope to flesh out the sharding support docs more in the future, as it still needs some examples. It's a complex subject since every company arranges their shards slightly differently.

Let me know if you have any questions, happy to help!

**Comment by pludi** [comment]
Thank you for the quick response. Our actual use case is – more or less – fetching most, but not all, schemas from a host. So, if I read this right, the best approach would be to fetch everything with `init`, remove the extranous stuff (including in the `.skeema` files), and just use `pull` from there on?

**Comment by pludi** [comment]
Thanks a lot! That actually helps a lot for our use case!

**Comment by evanelias** [comment]
Awesome, glad to hear! Credit goes to @tomkrouper of @github for contributing the excellent `ignore-schema` feature :)

**Comment by FlaviuRadulescu** [comment]
Evan,

just a quick question here.

is it possible to use init with --schema=schema1,schema2 ? I am  trying to do this  `skeema init -h localhost -S /var/lib/mysql/mysql.sock -d dir --schema=schema1,schema2` and I get an errror:
[ERROR] Schema  schema1,schema2 does not exist on instance localhost:/var/lib/mysql/mysql.sock

the only option is to use --ignore-schema?

thanks

**Comment by tomkrouper** [comment]
@FlaviuRadulescu, is there an issue with running it on all schemas and then just deleting the directory/schemas you don't want to use skeema with?

**Comment by evanelias** [comment]
@FlaviuRadulescu I would recommend using `--ignore-schema` in this situation. Otherwise future calls to `skeema pull` will do the wrong thing. As an example, say you have 4 schemas but you want this structure with just the first 2 schemas:

* dir/
  * .skeema config file with mysql instance-level configurations (host, port, etc)
  * schema1/
     * .skeema config file with schema-level configuration (`schema=schema1`, etc)
     * *.sql for tables in schema1
  * schema2/
     * .skeema config file with schema-level configuration (`schema=schema2`, etc)
     * *.sql for tables in schema2

If there's no `ignore-schema` specified, then the next call to `skeema pull` from the instance-level `dir` will detect that there are "new" schemas, schema3 and schema4, which don't have directories yet. So it will create and populate them, which isn't what you want. But if you have `ignore-schema=^(schema3|schema4)$` in `dir/.skeema`, future calls to `skeema pull` will know to skip these.

An alternative work-around is to only ever run `skeema pull` from inside the schema subdirs (e.g. `cd schema1; skeema pull; cd ../schema2; skeema pull`) since this avoids the instance-level logic, including the "auto-detect new schemas that don't have dirs yet" logic. But it is a bit awkward.

**Comment by evanelias** [comment]
> I don't know why it was implemented to ignore some DBs but not be able to define the DBs that you want?

So it sounds like you have many schemas, but you explicitly don't want to manage or track most of them in a schema repo? This is not a common situation, so Skeema is not geared for this use-case. Can you explain your use-case in more detail -- e.g. why do you have many schemas that you don't want to track, and why doesn't ignore-schema handle the situation?

**Comment by evanelias** [comment]
Thinking about this further, would an option to disable the "find new schemas and create dirs for them" behavior of `skeema pull` help in your use-case? I just created #38 to track this idea.
