### ISSUE TITLE
Add support for ignoring existing SQL files within the init directory

### ISSUE THREAD

**Issue by josiahhaswell** [skeema/skeema#200]
# Overview
I have containerized Skeema and am attempting to automate Skeema migrations.  My current process is:

1. Create a MySQL container
2. Create a Skeema container
3. Start the MySQL container and assign it a network identity <host>
4. Mount a set of SQL files into a directory <directory> within the Skeema container
5. Run `skeema init --dir <directory> --host <host>`
6. Run `skeema push`

Outcome: Skeema fails to perform the migrations, complaining that SQL files are already there

# Requested solution
Add a flag (e.g. `--force`, etc.) that allows Skeema to proceed

I'm happy to submit a PR implementing this if this is a feature you would like to implement

This may be a duplicate of https://github.com/skeema/skeema/issues/22

**Comment by evanelias** [comment]
Thank you for the feature request, but afraid I'm not following the desired workflow... can you clarify these steps a bit more please? Specifically, what's in the set of SQL files in step 4? And what's the state of the database right before step 5?

It generally doesn't make sense to run `skeema push` immediately after `skeema init` unless there are other steps in-between. The purpose of `skeema init` is to dump the schema definitions from the target database, so if you run `skeema push` right after that, it will always be an empty diff / no-op.

Generally you want to have a schema repo (or a mono-repo that has a schema subdir tree) that was initially created using `skeema init` a single time per db cluster. And then you commit changes to those files over time. See https://www.skeema.io/docs/workflow/ for more info.

For CI use-cases involving ephemeral databases, the schema repo pull request flow usually looks like this:

1. Create an empty dockerized database on a predictable port (i.e. 3306)
2. `git checkout` the "previous" state of the schema repo; for a pull request situation, this should be the PR branch's merge-base, i.e. the commit at which the PR branch diverged. Or for a simpler but less comprehensive approach, the HEAD of the default branch.
3. Populate the dockerized database from the schema repo, e.g. `cat *.sql | mysql [dbname]`
4. `git checkout` the new desired state of the schema repo, e.g. the pull request's branch
5. `skeema diff` to preview and lint whatever changes were present in the branch

That's just CI though. If you want full CD as well, it's generally more complicated and depends a lot on your company's infrastructure and security practices.

**Comment by josiahhaswell** [comment]
Thanks for the prompt response!  I'm not sure if Skeema understands the topological ordering of SQL tables qua their foreign key constraints, but I'm attempting to handle the following situation, which dumping the SQL files into MySQL does not solve:

```
create table `a` (
	id int primary key,
	foreign key (`id`) references `b`(id) on delete cascade
);

create table `b` (
	id int primary key
);

```
If `a` is declared in `a.sql` and `b` is declared in `b.sql` then the lexicographical ordering is incompatible with the topological ordering.  I guess the question becomes: does skeema topologically sort tables when constructing its plan?  If not, this may be a moot question.  If so, `cat *.sql | mysql [dbname]` won't work in the general case and it would be awesome to implement it, if possible, in Skeema.

I'm aware that parsing SQL is a pain and some degree of that would be required.  There are compliant Antlr4 parsers available, and there's a Go Antlr4 target as well that could help (I'm familiar with both) if that's a feature you'd be interested in adding.

**Comment by evanelias** [comment]
By default, `skeema push` executes DDL with session-level `foreign_key_checks=0`, disabling enforcement of FK constraints just for Skeema's session, so it does not need to sort tables. This is necessary because circular dependencies may exist among the FKs, meaning there's no guarantee that a "legal" ordering even exists.

See MySQL's [foreign_key_checks variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_foreign_key_checks) as well as Skeema's [similar option](https://www.skeema.io/docs/options/#foreign-key-checks). 

Anyway, to solve your issue, there are a couple workarounds:
a) Adjust the `mysql` command-line in step 3 so that it disables foreign key checks too, for example `cat *.sql | mysql --init-command='SET SESSION foreign_key_checks=0' [dbname]`

or

b) To populate the initially-empty db in step 3, just use `skeema push` instead of using the `mysql` client. This has the downside of skipping any statements that Skeema doesn't support though, e.g. if you want to set up some users/grants or manipulate some global variables in your containerized db.

Regarding parsing SQL, actually Skeema [intentionally](https://www.skeema.io/docs/faq/#no-reliance-on-sql-parsing) does not rely on fully parsing SQL in its functionality.

**Comment by josiahhaswell** [comment]
Awesome!  This indeed works for me.  Thank you for the time and the info--wonderful project
