### ISSUE TITLE
new linter proposal: lint-y2k38

### ISSUE THREAD

**Issue by morgo** [skeema/skeema#209]
*Please refer to the Contributing link in the sidebar for guidance.*

Currently there is a linter for temporal types, [`--lint-has-time`](https://www.skeema.io/docs/options/#lint-has-time). I'm actually OK with using (some-of) MySQL's built-in temporals so I don't plan to enable this.

What I am more concerned about, is the subset of the temporal types which will [stop working in less than 15 years](https://en.wikipedia.org/wiki/Year_2038_problem). This is getting too close for comfort.

I propose a new linter `--lint-y2k38`, which I would suggest should be a warning by default. I am happy to provide a PR.

**Comment by evanelias** [comment]
Is this just `TIMESTAMP`, or are there any other types with y2k38 issues?

With `TIMESTAMP`, personally I'm not too worried yet, given the primary use-case of timestamping the *current* date/time for creation, modification, etc. Although I'm sure there are also many cases of folks using it for arbitrary temporal values, there's no way for automation to tell the difference without also inspecting row data :/

Have Oracle or MariaDB provided any clarity on whether they view this `TIMESTAMP` limitation as a bug, and if so, with what priority? Hopefully they plan to address this in the near future, in which case this is less pressing... my initial preference would be wait-and-see, and meanwhile to keep this FR open but not implement yet. In Skeema the number of linter checks, and options in general, is getting quite large and I'm concerned it could lead to cognitive overload or be intimidating to new users. There's still room for more linters and more options, but the bar gets higher with each one added. And longer-term, the future JSON support in Premium should make it easier to add custom checks to a CI pipeline in any programming language, without them needing to be in the core of Skeema.

If this linter is eventually implemented, the default would need to be `ignore`, due to the widespread nature of "only timestamping the current date/time" use-cases (which are still safe until 2038, sufficiently beyond the EOL dates for all currently-available MySQL and MariaDB versions). Unfortunately, warning on all `TIMESTAMP` cols by default would create a support headache, from past experience with some other overly-noisy defaults in Skeema, some of which still need to be tweaked.

**Comment by morgo** [comment]
> Is this just `TIMESTAMP`, or are there any other types with y2k38 issues?

I thought it was more, but you're right - it just looks like `TIMESTAMP`.

> Have Oracle or MariaDB provided any clarity on whether they view this TIMESTAMP limitation as a bug, and if so, with what priority?

It's tracked as https://dev.mysql.com/worklog/task/?id=1872 / https://bugs.mysql.com/bug.php?id=12654 - no updates in a long time.

If you consider that GA releases are supported for 8 years, any release after 2030 is at risk of not being able to store `timestamp` dates by its EOL. That is too soon for my comfort, but other users might have different opinions.

Unfortunately `TIMESTAMP` has the better handling around `DST`. IMHO it's also not safe to use `DATETIME`/`TIME` *when* the server's timezone is not in UTC. This is perhaps a more nuanced view of the existing linter `--lint-has-time`.

> If this linter is eventually implemented, the default would need to be ignore

Sure, fine with that.

Another suggestion is that it could be changed to something based on "disallow datatype". So that `TIMESTAMP` can provide a warning (unfortunately if it's generic, the explanation why is less useful).

**Comment by evanelias** [comment]
Hmm, so if I understand https://dev.mysql.com/worklog/task/?id=1872 correctly, the root cause is that MySQL currently limits timestamp values to only 31 bits? Meanwhile https://bugs.mysql.com/bug.php?id=12654 is marked as closed/completed, since it focused on the functions but not the column type...

In my opinion, the best path forward in the near-term would be for larger MySQL users / MySQL Enterprise customers to encourage Oracle to prioritize fixing this in the server.

**Comment by evanelias** [comment]
If we improve the annotation text for the existing lint-has-time check, is it possible that `lint-has-time=warning` could be workable for your use-case @morgo? Here's what I'm currently noodling over in a branch:

* The annotation message could differ for timestamp vs other types. For example, the timestamp message could include a strongly-worded warning about the y2k38 problem with this type.

* Despite timestamp's y2k38 limitations, even if a company usually normally bans timestamp, there may be situations where it's acceptable -- i.e. using it to only store the current timestamp, in low-risk applications that aren't expected to be in use for many years, proof-of-concept situations, internal tools, etc. Also some frameworks / off-the-shelf OSS use timestamp and it's not always possible to change this.

* Even if a company prefers datetime instead of timestamp, it can still be beneficial to have a linter warning which reminds users that datetime doesn't perform timezone conversion or store associated timezones with values.

* The annotation wording around preferring ints (in place of temporal types altogether) could be omitted for `lint-has-time=warning`, and only included for `lint-has-time=error`. The intention would be that `lint-has-time=error` is for companies who have a blanket ban on all temporal types, typically due to having non-UTC system time which is impractical to change (I'm aware of a few giant companies in this bucket :sweat_smile:)... whereas `lint-has-time=warning` would be useful for companies who allow some or all of these types, but need engineers to exercise caution in picking the appropriate type for the situation.

Would that be beneficial, at least for now? Or do you strictly need the ability to warn/error on timestamp alone?

**Comment by morgo** [comment]
Yes, this works for me -- and is beneficial.

In terms of Oracle and MySQL's response: we can't guarantee the data type will be 'fixed'. It might be that the other types are instead encouraged and `TIMESTAMP` becomes deprecated. Or it might be that there is an upgrade path, but it's not great - such as with old temporals from earlier versions. So if the linter just states fact that the current type is y2k38 limited, users can do with this knowledge as they like.

> Would that be beneficial, at least for now? Or do you strictly need the ability to warn/error on timestamp alone?

That's my intended behavior, but I can strip it out at the layer above skeema if necessary.

> Even if a company prefers datetime instead of timestamp, it can still be beneficial to have a linter warning which reminds users that datetime doesn't perform timezone conversion or store associated timezones with values.

We always have server's in UTC, so we are not exposed to this risk. But I agree it's not possible for you to know this, since the linter might be performed against a different server to the apply. For this reason I agree it's reasonable.
