### ISSUE TITLE
Why doesn't Skeema support Vitess?

### ISSUE THREAD

**Issue by 205g0** [skeema/skeema#215]
Pretty much the title and out of curiosity (I'd like to use it with PlanetScale)

**Comment by evanelias** [comment]
It's not supported because of a multi-year pattern of behavior by a group of people currently employed by that company, several of whom I once considered personal friends. These folks *repeatedly* used core Skeema code in ways which directly compete with Skeema commercial products.

Skeema is a bootstrapped product, meaning I've personally paid for all of this out-of-pocket for years, and ongoing development is 100% dependent on revenue from our premium products. So when a well-funded company does something like [this](https://github.com/planetscale/tengo/commits/7fb6c95) with Skeema's diff library -- and that's the *third time* this same group of people did something along these lines -- it's a substantial threat to the ongoing viability of Skeema, along with the years of work and personal investment I've put into it.

To be clear, they weren't using this diff code for something minor. At launch time for their commercial managed database product, literally their entire marketing strategy focused on "their" schema management features. For added context, these people haven't contributed one line of code, nor a single cent to Skeema, nor have they ever made a recruitment or acquisition outreach of any kind.

They eventually switched to their own in-house table diff library, but it took nearly a year for them to even start on this. And long before that, I repeatedly suggested that a good *mutually beneficial* path forward would be for them to write some code bridging their SQL parser with Skeema/Tengo's diff code; naturally they completely ignored this.

I should note, everything they did was absolutely *legal* and in accordance with Skeema's license. However, on a human level, they burned this bridge so severely that I want no further interaction with that company, its products, or its employees under any circumstances for the rest of my natural life.

Closing and locking -- I'm not mad at you for asking, please don't misinterpret. I just don't have the energy to discuss this further, as I really need to focus on completing the next Skeema release this week.
