### ISSUE TITLE
Skeema does not support generating a diff of this table. Use --debug 

### ISSUE THREAD

**Issue by waveney** [skeema/skeema#217]
**Describe the bug**
*A clear and concise description of what the bug is.*

I have been using Skeema for years to generate the starting tables for my project on remote instances.   I now wish to use it to maintain those tables.  I had a few issues with the local copy and remotes having different character sets and collations.  This I have resolved to use utf8mb4/utf8mb4_general_ci in all cases.

On my own machine it apparently runs without grief.   On a remote machine (after extensive debugging) I get this for EVERY table (data taken from a very simple one):

2023-08-07 17:05:41 [WARN]  Skipping table `TsAndCs2`: Skeema does not support generating a diff of this table. Use --debug to see which properties of this table are not supported.
2023-08-07 17:05:41 [DEBUG] --- Expected CREATE
2023-08-07 17:05:41 [DEBUG] +++ MySQL-actual SHOW CREATE
2023-08-07 17:05:41 [DEBUG] @@ -11 +11 @@
2023-08-07 17:05:41 [DEBUG] -) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
2023-08-07 17:05:41 [DEBUG] +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

The distributed sql for that table is:

CREATE TABLE `TsAndCs2` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Name` text COLLATE utf8mb4_general_ci,
  `Content` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

An export from the live database gives:

CREATE TABLE `TsAndCs2` (
  `id` int NOT NULL,
  `Name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

...

ALTER TABLE `TsAndCs2`
  ADD PRIMARY KEY (`id`);

(Along with lots of real data)

**Environment**
Both machines: skeema version 1.7.0-community (snapshot build from source)

Local: Linux Ubuntu 22.04.2 LTS.   
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 8.0.33-0ubuntu0.22.04.4 - (Ubuntu)
Protocol version: 10

Remote: Linux Ubuntu 22.04.2 LTS
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1 - Ubuntu 22.04
Protocol version: 10

- Skeema version: *[e.g. v1.5.0]*
- Database vendor, version, OS/platform: *[e.g. MySQL 8.0.23 running on Linux]*
- Any other environmental notes or special configuration:

**To Reproduce**
*Steps to reproduce the behavior.*

No idea

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The diff/push to have worked

**Additional context**
*Add any other context about the problem here.*

This is part of a larger open source project which is just about to gain another 1/2 developers and be deployed to rather more than the current one site.

**Comment by evanelias** [comment]
Simply upgrade to a newer version of Skeema to solve this. You're using an old Skeema release from January 2022, against newer database server versions from Feb 2023 (MariaDB 10.6.12) and April 2023 (MySQL 8.0.33).

MariaDB's point releases from Nov 2022 unexpectedly changed the output logic for collations in SHOW CREATE TABLE, which broke compatibility with a core safety check in Skeema. See #193, #194, #195. This was fixed in Skeema 1.9.0 that same month.

This sort of backwards-incompatible change on the database server side is rare, but it does happen sometimes, and there's no way to predict it ahead of time on Skeema's side. And besides, upgrading Skeema is much easier than upgrading your database server version.

Side note, but you **really** need to be careful when mixing and matching MySQL 8 with MariaDB. They are absolutely [not drop-in replacements](https://www.skeema.io/blog/2023/05/10/mysql-vs-mariadb-schema/) for each other.

**Comment by waveney** [comment]
Thanks
