### ISSUE TITLE
Improved handling of system tables

### ISSUE THREAD

**Issue by dveeden** [skeema/skeema#221]
When working on #220 I noticed that:

1. System tables are defined filtered at three different places

- [`isSystemSchema`](https://github.com/skeema/skeema/blob/a3ecc184bc719e5cf8bbfe9e9d4d7e639eece058/cmd_init.go#L110)
- [`filterSchemaNames`](https://github.com/skeema/skeema/blob/a3ecc184bc719e5cf8bbfe9e9d4d7e639eece058/internal/fs/dir.go#L484)
- [Instance](https://github.com/skeema/skeema/blob/main/internal/tengo/instance.go) (multiple SQL queries)

2. These lists are static and not defined per vendor/flavor.

For TiDB I needed to add `METRICS_SCHEMA` for which I basically made an instance specific `isSystemSchema`.

3. The list is likely not complete

For MySQL 8.0/8.1 these might be missing:
- [`ndbinfo`](https://dev.mysql.com/doc/refman/8.1/en/mysql-cluster-ndbinfo.html) when NDB is being used.
- `mysql_innodb_cluster_metadata` for Group Replication / InnoDB Cluster.
- [`query_rewrite`](https://dev.mysql.com/doc/refman/8.1/en/rewriter-query-rewrite-plugin.html) for the query rewrite plugin

Side note, I wish MySQL would handle this better: https://bugs.mysql.com/bug.php?id=78314

**Comment by evanelias** [comment]
Ideally the list shouldn't be duplicated in multiple code paths, but it's a small list and there's not much benefit to a refactor. Again, this is a bootstrapped business, resources are limited and everything must be prioritized based on potential impact.

If multiple users start getting annoyed by `mysql_innodb_cluster_metadata`, then it might make sense to add it to these lists, but I haven't previously heard user feedback about this. Until then, [--ignore-schema](https://www.skeema.io/docs/options/#ignore-schema) is a very easy workaround.

Meanwhile since `query_rewrite` involves manually INSERTing rows (if I recall correctly), it can actually be useful to track for Skeema Premium users. They can use the seed data feature in Skeema Premium to dump the INSERTs to a .sql file and track them in a repo, and then use `skeema push` to manage rewrite rules across multiple environments or clusters.

As for `ndbinfo`, Skeema primarily just supports [InnoDB](https://www.skeema.io/docs/requirements/) at this time, nothing about NDB is supported well in general here and I don't anticipate that will change (complete lack of demand among paying customers).
