### ISSUE TITLE
Changing partition names aren't detected

### ISSUE THREAD

**Issue by lioraltarescu** [skeema/skeema#225]
Hello, 
I'm using the skeema open source version 1.11.0 and im Im adding partitions and removing partitions from the table.

I've test it on my m1 mac using a skeema 1.11.0 and 1.11.1 . I've tested it on  mysql 8.0.23 which i run as a docker container 

to reproduce use this table 
init table 

```
create table test(
 id varchar(30),  
 name varchar(30),  
 age int,  
 partition_key int,  
 PRIMARY KEY(id,partition_key)
 ) PARTITION BY LIST (partition_key)(   
 PARTITION PART_0 VALUES IN (0),  
 PARTITION PART_1 VALUES IN (1),  
 PARTITION PART_2 VALUES IN (2));
```

updated table
```
create table test(
 id varchar(30),
 name varchar(30),
 age int,
 partition_key int,
 PRIMARY KEY(id,partition_key)
 ) PARTITION BY LIST (partition_key)( 
 PARTITION PART_0 VALUES IN (0),
 PARTITION PART_1 VALUES IN (1),
 PARTITION PART_2 VALUES IN (2),
 PARTITION PART_3 VALUES IN (3));
```
I'd expect there the be drop and add partition commands in the diff instead of no result
```
2023-12-18 12:21:49 [INFO]  Generating diff of 127.0.0.1:3306 test vs skeema_dir/schemas/*.sql
2023-12-18 12:21:49 [INFO]  127.0.0.1:3306 test: No differences found
```

thank you

**Comment by evanelias** [comment]
Thank you for the report, but this is actually working as designed and documented. Please see the [requirements doc on partitioned tables](https://www.skeema.io/docs/requirements/#partitioned-tables) for important information on how Skeema interacts with partitioned tables.

To summarize: one common use-case for LIST or RANGE partitioning in MySQL is time-limited data retention, where each partition stores data for some time interval, and an external cron/task manages partition rotation. This approach leverages partitioning simply in order to efficiently drop old data when it is no longer needed, since dropping a partition performs much better than DELETE queries. In that workflow, users shouldn't track every change to the partition list in their schema repo in Git, because the partitions change on their own outside of Skeema (similar situation to auto_increment counters). So Skeema completely ignores changes to the list of partitions for this reason.

Skeema's current partitioning functionality is built only for that specific workflow, including the ability to configure some environments to strip partitioning (i.e. allowing use an external partition management cron in prod, while avoiding partitioning altogether in dev). Development of this functionality in Skeema was [generously sponsored by a large user](https://github.com/skeema/skeema/#credits) and it was built to handle their specific partitioning use-case. I have also seen several other large companies using partitioning in the exact same manner though, so it's not unique to the sponsor.

For other partitioning workflows, Skeema's handling may not be a good fit yet. If you can please describe your partitioning use-case and workflow in more detail, we can convert this to a feature request issue to track. Thanks!

**Comment by evanelias** [comment]
Hi @lioraltarescu, just following up regarding partitioning. If you can describe your typical workflows around modifying the list of partitions in a partitioned table, I'd be happy to convert this to a feature request. Thanks again! Or we can close if this was a one-off situation.

In any case, definitely agree the current partition-handling behavior isn't always intuitive. We have a major revision to the web docs in progress, and one small part of that includes clarifying Skeema's current partitioning interactions in more detail. Should go live in a couple weeks.
