### ISSUE TITLE
Redundant Index checker is too confident

### ISSUE THREAD

**Issue by morgo** [skeema/skeema#237]
**Describe the bug**

There are cases where indexes may appear redundant, but are not completely. Understanding these nuanced cases is probably not possible, so the suggested fix I have here is to tone down the confidence of the language in this message:

> reason = fmt.Sprintf("Index %s of %s is redundant to larger index %s.\nConsider dropping index %s.", dupeIndexName, table.ObjectKey(), betterIndexName, dupeIndexName)

**Environment**

(in main)

**To Reproduce**

I have several cases like this. Assume `a` is not the highest cardinality key:
```
CREATE TABLE t1 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 a INT NOT NULL,
 b INT NOT NULL,
 c INT NOT NULL,
 d INT NOT NULL,
 INDEX a_b_c (a,b,c),
 INDEX (a)
);
SELECT * FROM t1 WHERE a = 1234 ORDER BY id DESC LIMIT 1;
```

Without any data you an see the difference between the two plans:
```
mysql> explain SELECT * FROM t1 WHERE a = 1234 ORDER BY id DESC LIMIT 1;
+----+-------------+-------+------------+------+---------------+-------+---------+-------+------+----------+----------------+
| id | select_type | table | partitions | type | possible_keys | key   | key_len | ref   | rows | filtered | Extra          |
+----+-------------+-------+------------+------+---------------+-------+---------+-------+------+----------+----------------+
|  1 | SIMPLE      | t1    | NULL       | ref  | a_b_c,a       | a_b_c | 4       | const |    1 |   100.00 | Using filesort |
+----+-------------+-------+------------+------+---------------+-------+---------+-------+------+----------+----------------+
1 row in set, 1 warning (0.00 sec)

mysql> explain SELECT * FROM t1 FORCE INDEX (a) WHERE a = 1234 ORDER BY id DESC LIMIT 1;
+----+-------------+-------+------------+------+---------------+------+---------+-------+------+----------+---------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref   | rows | filtered | Extra               |
+----+-------------+-------+------------+------+---------------+------+---------+-------+------+----------+---------------------+
|  1 | SIMPLE      | t1    | NULL       | ref  | a             | a    | 4       | const |    1 |   100.00 | Backward index scan |
+----+-------------+-------+------------+------+---------------+------+---------+-------+------+----------+---------------------+
1 row in set, 1 warning (0.00 sec)
```

The index on `a_b_c` needs to resort all the data to find 1 row. Let's assume it's a lot.

The index on `a` just scans the index backwards and finds the first row, and stops.

**Expected behavior**

I think it just needs to allude to the potential of false positives. Maybe this is as simple as `s/Consider dropping index x/In most cases it is safe to drop index x/`

**Additional context**

**Comment by evanelias** [comment]
Excellent catch, thank you for reporting this! I agree with your revised wording, that looks great. If you'd like to open a PR, I'll happily approve and merge.

On my end I'll also aim to clarify this in the [docs for lint-dupe-index](https://www.skeema.io/docs/options/#lint-dupe-index) in the next few days. Just trying to figure out how best to word this succinctly, especially since not all users are necessarily familiar with InnoDB's behavior re: secondary indexes always automatically including the PK cols. Besides the specific query pattern in your example (`WHERE` on all columns of a smaller secondary index + `ORDER BY` on the PK) are there any common ones that come to mind?

Separately, I've found another unrelated edge case in the opposite direction (a redundant index pattern that the checker doesn't currently catch), but it's rare and annoying to implement. It involves unique indexes that are effectively redundant when considering the combination of a smaller unique index and some other overlapping non-unique index. `pt-duplicate-key-checker` actually finds those, so we probably should too. I'll create a separate issue to track that soon.

**Comment by morgo** [comment]
I'm happy to open a PR to attempt it. I've always been impressed with your wordsmithing, so please help me refine it it.

> Besides the specific query pattern in your example

No this is the only one I've really noticed.

**Comment by evanelias** [comment]
Thanks! I think your suggested wording above is pretty good, so overall maybe this string:

`"Index %s of %s is redundant to larger index %s.\nIn most cases, it is safe to drop index %s."`

A slightly longer PR could improve a couple other aspects of this, but no need to tackle these here unless you reeeeally feel inclined 😄 

* "larger" is not always the correct word. Specifically, there's the case where unique index A and non-unique index B have the exact same columns. But this situation is rare, and I figured the message's intent is still clear enough... and fixing it would require rewriting the helper function a bit, which is annoying.

* If the server flavor is recent enough to support invisible indexes, the linter annotation could include text suggesting to use that prior to dropping. Good operational practice, but users might glaze over the text if it's too long. And this would require more conditional logic based on the flavor for the right syntax (`INVISIBLE` in mysql 8.0+ vs `IGNORED` in mariadb 10.6+).
  Also potentially messy if your pipeline normally does everything through an OSC tool. Longer-term, Skeema should be smart enough to identify alters that should bypass OSC, but we're not there yet.

Again totally fine to punt on these two nits. I'm only mentioning them here since I already had them on an internal list of low priority things to fix/tweak.
