### ISSUE TITLE
About partition table get differences

### ISSUE THREAD

**Issue by iwanghc** [skeema/skeema#240]
Hi~ skeema helped me a lot, but I found some problems when using it
When I tried to use skeema to get the difference between two partitioned tables, I seemed to return results that did not match expectations，did not get the alter statement.
Why return an empty ModifyPartitions{} when the number of partitions is different？
![image](https://github.com/user-attachments/assets/15a4f08c-d81f-4ac7-bb0b-7c0e5d10be5b)

**Comment by evanelias** [comment]
This is described in the [partitioning documentation](https://www.skeema.io/docs/features/tables/#partitioned-tables). In brief, Skeema's partitioning support assumes that you are using an external cron to manage RANGE or LIST partitions, since that's how many big tech companies use partitioning in MySQL. With that partitioning use-case, it is undesirable to track partition changes in a Git repo, because partition rotation happens on a regular basis completely outside of your schema change flow. 

The partitioning support can certainly be expanded to cover additional use-cases/workflows in the future. The first step would be a clear description of the intended use-case, and from there we can figure out a design which generically matches the needs of multiple companies without breaking the existing support.

If you would like to propose additional partitioning functionality, please open a [discussion](https://github.com/skeema/skeema/discussions) describing your company's use-case / workflow. Thanks!
