### ISSUE TITLE
Slow on a DB with ~200 tables

### ISSUE THREAD

**Issue by PsyonixDan** [skeema/skeema#25]
Hi,

We are evaluating skeema. Overall it looks great and could be a really good fit for our use case. But the biggest concern so far has been speed on one of our DBs. This DB has ~200 tables. Doing a diff or a push takes about 4 minutes. We are running skeema from a machine that has a ~80ms ping to the DB.

- Is it expected to take that long on a DB of that size?
- Are there any options that could help speed things up?
- Is running this from a dev machine that is separate from the DB not an expected use case?

Looking at the actual steps in a diff, there seem to be multiple operations that take place sequentially on each table. (13 of these types of operations based on a packet capture.) So with ~200 tables and ~80ms of latency, each of these takes 15-20 seconds to complete. Is it possible to batch or parallelize these operations? I'd be happy to share more detail about what I saw through the packet capture if you'd like.

Thanks,
Dan

**Comment by PsyonixDan** [comment]
Thanks for the quick follow up and the thorough explanation.

>With an ~80ms ping, I am guessing that either there is some geographic distance between the client (skeema) and server (db), and/or perhaps a VPN?

This is from our office (skeema) to a GCP VM (db), hosted in the `us-central1-c` zone.

>Also, are all of the 200 tables in the same database schema?

Yes.

>Are any unusual settings in use in Skeema?

Nope, nothing unusual.

>...as mentioned above `--skip-verify` will speed things up, though with one safety check disabled

I tried this and it brought the time for a diff from 4 minutes down to 2 minutes.

>I'd love to get more insight into whether just reducing the latency between client and server is sufficient first...

I ran the diff on a VM in the same zone as the DB, and it was vastly improved. It took ~18 seconds to do the full run, and ~9 seconds with `--skip-verify`. I suppose we could set up some kind of tooling that would let us trigger skeema locally, but then send it to a cloud VM to actually run. But that's obviously not ideal. If we could find a way to run it more quickly that would certainly be better.

Thanks again!

**Comment by evanelias** [comment]
Good data points, thanks! I agree that this use-case (running Skeema from the office against prod DBs in a different location) should be supported without being insanely slow, and I will make some performance improvements for it to be more viable. There are some query pattern improvements I should be able to make within the next couple days, and I'll comment back on this issue once those are in place.

Out of curiosity, in your environment do you also have any dev/test MySQL instances running in your office (i.e. on each engineer's laptop/desktop, or perhaps a central local dev server)? And/or do you typically use Docker on your engineers' machines?

I ask because one additional potential optimization path would be to move all temporary schema operations (3rd bullet in my previous reply) to an in-office machine, or even a temporary local Dockerized instance. These operations don't strictly need to run on the production database; any other mysql-server running the same version is sufficient. Skeema doesn't support offloading these operations to a different machine yet, but I could add support for that fairly easily if there's interest?

> I suppose we could set up some kind of tooling that would let us trigger skeema locally, but then send it to a cloud VM to actually run. But that's obviously not ideal.

Agreed. Longer-term there will be a built-in client/server way of running Skeema, but even optimistically that's at least a few months down the road.

**Comment by PsyonixDan** [comment]
>There are some query pattern improvements I should be able to make within the next couple days, and I'll comment back on this issue once those are in place.

Thanks, that's greatly appreciated!

>Out of curiosity, in your environment do you also have any dev/test MySQL instances running in your office (i.e. on each engineer's laptop/desktop, or perhaps a central local dev server)? And/or do you typically use Docker on your engineers' machines?

We don't run any DBs locally - everything is in GCP, including dev and test. But we do have Docker on everyone's machines. In fact, I've been running Skeema using a Docker image!

>I ask because one additional potential optimization path would be to move all temporary schema operations (3rd bullet in my previous reply) to an in-office machine, or even a temporary local Dockerized instance.

My main concern with this would be any differences between the real DB server and what is set up in Docker or some other local DB - things like a different version of MySQL or different settings, and what effect those could have. It's possible I'm paranoid though. And that seems like a good option if we can't get things fast enough with the remote DB.

**Comment by evanelias** [comment]
I’ve just merged some performance improvements in #26. If you have a chance, I'd love to get feedback on whether this is now fast enough for regular use. Easiest way to upgrade is  via `go get -u github.com/skeema/skeema`. Thanks!

My back-of-the-envelope estimate is that `skeema diff` should now take ~15 to 20 seconds in your environment from your office, or 1 to 2 seconds from a GCP VM. Also, `--skip-verify` should no longer make much of a difference, since the verification logic has now been optimized for minimal overhead.

I haven’t implemented the logic to optionally offload the temp schema operations to a local/dockerized DB yet, but I’ll keep that in mind for the future. Regarding your version/settings concerns, I agree, totally valid. One solution could be for Skeema to examine relevant attributes and settings on the real db (mysql version and flavor; settings relating to sql_mode, storage engines, charsets, etc) and then dynamically spin up a dockerized MySQL instance matching this. I already have working code to do the latter half of that in Skeema’s testing suite, so only the version/setting matching part would need to be written :) Starting Dockerized mysqld locally can take ~10 sec though, so the container would likely need to be reused between invocations to avoid it being a new source of slowness.

**Comment by PsyonixDan** [comment]
The diff took ~20 sec from the office - good estimating! I haven't tested from a GCP VM yet.

> One solution could be for Skeema to examine relevant attributes and settings on the real db (mysql version and flavor; settings relating to sql_mode, storage engines, charsets, etc) and then dynamically spin up a dockerized MySQL instance matching this.

That's a really interesting idea. Seems feasible.

And thanks for the help! This definitely gets Skeema into the realm of usability for us.

I should mention - there are a couple of additional parts to our current DB updating process which  Skeema doesn't support. Specifically stored procs and seed/init data. We're still evaluating Skeema for schema management, but will need to either fit it into our current process, or add support for those things to Skeema itself.

Thanks again.

**Comment by evanelias** [comment]
Very glad to hear! I may tweak the concurrency up a little bit further soon, which may shave off a few more seconds, but otherwise closing this out.

re: stored procs and seed data, yeah totally understandable. I've mostly been prioritizing things based on level of demand. Seed data has been coming up a lot, but there are still some nuances to figure out (see #22). Haven't heard many asks about stored procs, but please feel free to open an issue. In both cases I'd love to hear more about multiple companies' use-cases / workflows, to ensure that Skeema can handle it in a generic manner. PRs always welcome too of course, but that can be a big time commitment :)
