### ISSUE TITLE
Error 1031: Table storage engine '<Table>' doesn't have this option.

### ISSUE THREAD

**Issue by ohsono** [skeema/skeema#40]
> 2018-09-11 15:05:22 [ERROR] Skipping ::<local_dir_and_schema.sql>::
>  Error executing DDL: Error 1031: Table storage engine for '<Table>' doesn't have this option.

I've gotten Error 1031 when I ran "skeema diff". what this really weird is it only occurred on mysql 5.6 docker. Once I upgrade 5.7, it's not an issue anymore.

**Comment by evanelias** [comment]
Thank you for trying out Skeema and reporting an issue! I may need more info to debug this, but I have an initial hunch. 

* If you try using `skeema diff --connect-options="innodb_strict_mode=0"`, does the problem go away in MySQL 5.6?
* Was this table originally created as MyISAM and later converted to InnoDB? (or perhaps is this diff intended to change the storage engine?)
* If you manually run `SHOW CREATE TABLE` on the table, are there any unusual table-level settings present at the end, such as `ROW_FORMAT` or `KEY_BUFFER_SIZE`?
  * And/or are there any such clauses in your *.sql file? If so, did you put them there manually, or were they placed there automatically by Skeema (e.g. `skeema init`, `skeema pull`, or `skeema lint`)?

The most common cause of this error is that a MyISAM-to-InnoDB conversion can leave a dangling `ROW_FORMAT` clause, even though that clause doesn't do anything in InnoDB. In mysql 5.6, `innodb_strict_mode` is overly picky and rejects such no-op `ROW_FORMAT` clauses; mysql 5.7+ ignores it even with `innodb_strict_mode`. As of the latest Skeema release, it now defaults to enabling `innodb_strict_mode` in its connections.

Skeema typically proactively removes/ignores such clauses, so I didn't think the new `innodb_strict_mode` default would break any mysql 5.6 users. But perhaps some code path isn't removing these clauses properly, which I'll track down if it's the case.

If the problem is caused by something other than the above theory, can you please post the `SHOW CREATE TABLE` output (original state of the table) and the corresponding *.sql file (desired new state of the table), and/or a brief description of the intended diff? If you can't post this publicly, feel free to email me at the address on any Skeema git commit -- if you clone the repo and run `git show -s --format='%ae' HEAD` it should show my email. Thanks!

**Comment by ohsono** [comment]
Thanks for explanation. The problem only should be happening for mysql5.6. (I totally agree for it if someone said 5.6 is not the greatest one:-1: ). As I follow your guide by using the option(innodb_strict_mode=0) with skeema, this is working fine.

However, I've already put it on the global variables before to try that. I guess this value is dynamic as well.
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| innodb_strict_mode | OFF   |
+--------------------+-------+
1 row in set (0.00 sec)

Once again, thanks for sharing it. I've first seen your project at Percona live 2017 but this is a truly my first time examine it.

**Comment by ohsono** [comment]
Here is the detail of steps that I've ran.
1. skeema init -d mysql56_test -uroot -p -P6603
2. add client.sql to the folder
3. skeema diff (without option provided)

And configuration files and more

::docker-compose.yaml::
version: "2"

services:
  db1:
    image: mysql:5.7
    command: --datadir=/var/lib/mysql/data
    volumes:
      - "db-data1:/var/lib/mysql"
      - "db-log1:/var/log/mysql"
      - "db-cnf1:/etc/my.cnf"
      - "db-tmp1:/tmp"
    ports:
      - 3306:3306
    networks:
      db_br:
        ipv4_address: 192.16.1.10                  
    environment:
      MYSQL_ROOT_PASSWORD: complex_pw
      MYSQL_DATABASE: test1234
      restart: unless-stopped

  db2:
    image: mysql:5.6
    command: --datadir=/var/lib/mysql/data
    volumes:
      - "db-data2:/var/lib/mysql"
      - "db-log2:/var/log/mysql"
      - "db-tmp1:/tmp"
    ports:
      - 6603:3306
    networks:
      db_br:
        ipv4_address: 192.16.1.11
    environment:
      MYSQL_ROOT_PASSWORD: very_complex_pw
      MYSQL_DATABASE: test1234

volumes:
  db-data1:
    driver: local
  db-log1:
    driver: local
  db-cnf1:
    driver: local
  db-tmp1:
    driver: local
  db-data2:
    driver: local
  db-log2:
    driver: local
  db-tmp2:
    driver: local

networks:
  db_br:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.16.1.1/24
        gateway: 192.16.1.1


:: .skeema file config::
[production]
flavor=mysql:5.6
host=127.0.0.1
port=6603
user=root

::client.sql::
CREATE TABLE `client` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) DEFAULT NULL,
  `field_name` varchar(100) NOT NULL COMMENT '',
  `field_description` varchar(300) DEFAULT NULL COMMENT '',
  `field_label` varchar(200) DEFAULT NULL COMMENT '',
  `is_active` tinyint(1) DEFAULT NULL,
  `create_date` datetime NOT NULL,
  `remove_date` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `idx_client_1` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=164 ROW_FORMAT=DYNAMIC;

Hope this help to improve it
Thanks

**Comment by evanelias** [comment]
> add client.sql to the folder
> ...
> ENGINE=InnoDB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=164 ROW_FORMAT=DYNAMIC;

That helps, thanks! To fix this problem the best way, I would recommend that you configure your dockerized MySQL 5.6 to use `innodb_file_format=Barracuda` globally.  Or, alternatively, remove `ROW_FORMAT=DYNAMIC` from your client.sql file.

You're getting mysql error 1031 because of trying to create a new innodb table with `ROW_FORMAT=DYNAMIC`. In MySQL 5.6, this is [not allowed unless `innodb_file_format=Barracuda`](https://dev.mysql.com/doc/refman/5.6/en/innodb-row-format-dynamic.html), which [isn't the default in 5.6](https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_file_format).

However, without `innodb_strict_mode`, MySQL 5.6 just gives a warning and allows the statement to proceed. But this is generally unsafe; an explicit error is usually preferred, which is what happens with strict mode enabled. So I think Skeema is doing the right thing here by using strict mode by default, and propagating the MySQL error in this situation. It would be better if MySQL gave a clearer error here, but that's really up to MySQL / Oracle.

As for why this works fine in MySQL 5.7+, seems it's due to a change in behavior for innodb_file_format. According to the [5.7 manual](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_file_format), 

> The innodb_file_format setting is ignored when creating tables that use the DYNAMIC row format. A table created using the DYNAMIC row format always uses the Barracuda file format, regardless of the innodb_file_format setting.

This wasn't the case in 5.6 (nor is it the case in MariaDB fwiw).
