### ISSUE TITLE
Store Procedure/Function/Trigger/View Support

### ISSUE THREAD

**Issue by jmillstein** [skeema/skeema#41]
Hi Evanelias .  Firstly, thank you for the product! Was wondering if you had plans to support stored procedure/functions/triggers and views in the near future?

**Comment by evanelias** [comment]
Thanks for using Skeema! No immediate plans for stored procedures, triggers, or views yet. But it's definitely possible in the future, or possible via third-party pull requests, or sponsored development. These features should fit in well with Skeema's declarative approach; ditto with users/grants/roles, and possibly also seed data (see #22).

One near-term blocker is that the codebase currently makes some restrictive assumptions around file layout -- specifically, 1 *.sql file = 1 CREATE TABLE statement, with table name matching the file name. That presents problems for supporting things other than tables, since there's no logical place to put them. But I'm currently working on a branch with better file parsing, which allows that restriction to be lifted. So after that point, it should be easier to implement support for things other than tables.

**Comment by evanelias** [comment]
Just released [Skeema v1.0.6](https://github.com/skeema/skeema/releases/tag/v1.0.6), which includes a merge of the file-handling refactor. The codebase no longer assumes that 1 .sql file = 1 CREATE TABLE statement, which will make it possible for other kinds of DDL / object types (procs, funcs, triggers, views, grants, etc) to be supported in the future.

**Comment by f3rn4nd0-c354r** [comment]
It would be a nice improvement in the documentation to detail unsupported features like this.

**Comment by ppolydoras** [comment]
Hello Evanelias. Skeema is an amazing tool, much better than the rest of the competition. If you incorporate stored procs, functions and views it would 100% satisfy our requirements and will definitely be employed by our company. Keep up the great work!

Did you give any thought on that? What will it take to add it? Thank you in advance for your response.

**Comment by evanelias** [comment]
Hi @ppolydoras, thanks for checking out Skeema! Eventually I would like the tool to support everything in this issue + the other open issues, but realistically it will take some time. There are a lot of "long tail" features in MySQL/MariaDB that are not used by every company, and prioritization will be based partially on how many users request each feature.

Since Skeema isn't backed by a corp or VC funding, a chunk of my time is currently going towards building [SaaS CI/CD functionality](https://www.skeema.io/blog/2019/01/19/github-api-beta/) and sometimes [consulting](https://www.indexhint.com/). That said, given that the Skeema command-line tool is fully open source, I always welcome third-party code contribution (I could give guidance on possible implementation paths) or sponsored development (where a company pays for a feature to be added more quickly, in a way that matches the company's preferred workflow).

**Comment by evanelias** [comment]
I'm happy to announce that support for stored procedures and functions has been implemented in #60, contained in today's release of [Skeema v1.2.0](https://github.com/skeema/skeema/releases/tag/v1.2.0).

The remaining object types from this issue have been split out into separate tracking issues:
* Views in #63 
* Triggers in #62 
* Events in #61

**Comment by f3rn4nd0-c354r** [comment]
Great! Congratulations!
