### ISSUE TITLE
How to start using this?

### ISSUE THREAD

**Issue by waveney** [skeema/skeema#42]
I have an ongoing (open source) project with a database of growing complexity.  I develop it on my laptop, and then push it with git to github, deploying to the live server through git.   At present it is used on one site, but soon it will be used on several and I don't want to have to keep a record of every change done via phpmyadmin to the structure and manually update each instance of the database.  It would be really nice to have the schema stored as part of the repo.     Skeema seems what I need...

I have downloaded it, and tried to run it locally:

```
./skeema init -h localhost -u wmff
2018-10-21 21:54:54 [ERROR] Unable to connect to localhost:/tmp/mysql.sock for /home/rjp/localhost: dial unix /tmp/mysql.sock: connect: no such file or directory

```
MariaDB is running and accessable from the programs and phpmyadmin.   There is no file called mysql.sock anywhere, both my Centos servers have /var/lib/mysql/mysql.sock though.   Laptop is ubuntu if it makes any difference.  

I am not sure where I should be running Skeema:  The home directory for the development project is: ~/Projects/wmff/dev/, the live system (and stage) are on their own dedicated server.

**Comment by evanelias** [comment]
Thank you for checking out Skeema! The connection options for `skeema init` are designed to mimic the [standard `mysql` command-line client](https://dev.mysql.com/doc/refman/5.6/en/mysql.html), so if you can get that working first, the same options should then work for `skeema init`.

You can run `skeema` from any host, as long as that host can reach your database. Typically running `skeema` from a laptop or dev server is most convenient. 

Assuming you are running Skeema from your laptop and your database is password-protected, your `skeema init` command-line will probably look something like: `skeema init -h [hostname or IP of prod database] -u [username] -p`. This will prompt you for the password on STDIN. Alternatively, you can supply a password via the ~/.my.cnf option file, or the MYSQL_PWD environment variable, or directly on the command-line; see the [docs](https://github.com/skeema/skeema/blob/master/doc/options.md#password) for more info.

Once you've successfully run `skeema init`, you can then add your staging db using `skeema add-environment -h [hostname or IP of staging database] -u [username] -p staging`. 

After you've done that one-time setup, you can use a schema change workflow like this:
* Make changes to your dev/staging DB using phpmyadmin or whatever you prefer
* Run `skeema pull staging` to update the filesystem representation of the changes you made to the staging db. Commit those changes to git as usual.
* Run `skeema diff production` to preview what changes need to be made to update prod to match the filesystem representation, or `skeema push production` to actually run those changes on the prod db. (Note: since `production` is always the default, you could simply run `skeema diff` and `skeema push` without explicitly saying `production` here if you want.)

**Comment by waveney** [comment]
Thanks for the reply, but skeema init still does not connect:

`rjp@linuxlaptopq:~$ mysql -u wmff
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 889
Server version: 10.1.34-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> quit
Bye
rjp@linuxlaptopq:~$ ./skeema init -u wmff
2018-10-22 08:40:44 [ERROR] Option --host must be supplied on the command-line
rjp@linuxlaptopq:~$ ./skeema init -h localhost -u wmff
2018-10-22 08:37:11 [ERROR] Unable to connect to localhost:/tmp/mysql.sock for /home/rjp/localhost: dial unix /tmp/mysql.sock: connect: no such file or directory
` 
I can access via mysql -u wmff (no password needed), but this skeema init -u wmff, complains about lack of -h, adding the -h localhost it complains about no mysql.sock.

**Comment by evanelias** [comment]
By default, the mysql client uses `localhost` if no host is specified, and `localhost` in mysql has a special meaning of "use a UNIX domain socket instead of tcp/ip". Your Linux distribution has probably packaged MariaDB in such a way that the correct default socket path is pre-compiled-in to both the client and server, but Skeema has no way of knowing where this is automatically.

The mariadb manual describes how to use the "status" command to find out where your mysql.sock is: https://mariadb.com/kb/en/library/mysql-command-line-client/#linuxunix

Once you find your mysql.sock, you could pass it to skeema using `skeema init -h localhost -S /path/to/mysql.sock`. Alternatively, if you want to use tcp/ip instead of a UNIX socket, specify `-h 127.0.0.1` instead of `-h localhost`.

That all said, using `localhost` for `skeema init` is generally not recommended. `skeema init` is intended to be pointed at a *production database*, not a dev database on your laptop. The idea is that your prod database is the canonical source-of-truth to use for setting up the initial filesystem representation of your schemas.

**Comment by waveney** [comment]
Evan,

Accessing via  -h 127.0.0.1  worked.

MariaDB status tells me the socket is at: UNIX socket:	/var/run/mysqld/mysqld.sock

Which is very similar to the sockets on my servers.

As to Production/Development setup, you are probably right.  However, the dev system is ahead of the live system and in a few months there may be no real "master" other than the dev.  

Currently the flow is approximately: Dev feeds github/Master which feeds Stage, if when I am happy I pull Master to Live on github.   Which then deploys to the site.

In the future, it may be users fork github/live then adds their own content/styling and deploys to their own site or they just configure it, the current site being one of many users - each with their own data.  Details to be determined.  Not all users using all of the current system.

This may not be an ideal setup, but is what it has evolved into.

**Comment by evanelias** [comment]
Awesome, glad that `-h 127.0.0.1` worked! Closing this out, but please feel free to reopen if you hit other questions.
