### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by waveney** [skeema/skeema#47]
I have two related issues:

1) On my development machine I have multiple databases - it would be nice to make Skeema limit itself to just one - the one related to the project I am using it for.  (I can work round this, but is not nice)

2) The project has now been deployed to two additional users.   On a target production machine, there needs to be a way to have the database not called by the name it was on the development machine.  One of the additional users is on the same server as the original target, they need their own databases, each has the same structure and table names, but totally independent data, and may be updated at different times.  In time there are likely to be lots of users and lots of copies around.

**Comment by TorTorT** [comment]
I have the same challenge with your first problem, I have found that by creating a user for skeema with only permission to the one database I want it manage it successfully limit the scope, you might want to give it a try.

**Comment by evanelias** [comment]
Happily, these use-cases are already supported, they just require a bit of configuration.

1. There are three ways to solve this one, depending on your preferred workflow:

1a. If you're only ever managing a single logical schema (i.e. just one directory of *.sql files), you can "flatten" the directory structure and define the `host` and `schema` in the same .skeema file. This is what `skeema init` will do by default if you pass in the [--schema](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) option on the command-line, to only init a single specific schema. Or if you already ran init and have a repo, you can always move things around and edit the .skeema file manually.

1b. If the schema(s) you want to ignore follow a predictable naming schema, you can use the [ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) regex option, either on the command-line or in a .skeema file. This option only affects `skeema init` and `skeema pull` if the unwanted directory doesn't already exist, though; so just delete it manually first if it already exists.

1c. If you previously did an init against production, but you have extra schemas on dev that you don't want `skeema pull` to interact with, use [skip-new-schemas](https://github.com/skeema/skeema/blob/master/doc/options.md#skip-new-schemas) on the command-line or in the `[development]` section of a .skeema file. This will prevent `skeema pull` from creating dirs for schemas found only on development (or whichever environments you configure it for).

2. In .skeema you can create named environments for each user, and define the schema name there as needed. For example,
```
[bob-dev]
host=dev.mycompany.com
schema=foo

[jim-dev]
host=dev.mycompany.com
schema=bar
```
Then Jim can use `skeema pull jim-dev`, `skeema push jim-dev`, etc. They can be on the same host or different hosts; and the host can be defined here or in a parent directory. The exact layout doesn't matter. Skeema just uses whatever is configured for the specified environment, with parent option files cascading down to the current dir.

Another possibility is to use unix env variables and a backtick-wrapped shellout for the [schema](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) value. For example:
```
[development]
host=dev.mycompany.com
schema=`echo $DB_NAME`
```
Then the value of $DB_NAME env variable will be used. (Although if the env var is simply not set, the directory will be skipped, since effectively the directory isn't mapping to a schema name anymore.)

**Comment by waveney** [comment]
Getting there, thanks.

Splatting the schema from my existing repo, and starting again with init --schema I think does what I want to solve #1.  The generated .sql files are now included in the repo, but not the .skeema file.

The command line at my end to init was: skeema init -h 127.0.0.1 -u wmff --schema=wmff -d ../Schema dev

For #2 I think I need to construct the .skeema file in my installation script, once this is right it will always do "skeema push" as part the upgrade script (auto executed after git pull).  These are all "Production" environments.  The installation script already knows what the database is to be called and the username/password.

Is this what I need it to create?
 
    schema=DATABASENAME
    default-character-set=utf8mb4
    default-collation=utf8mb4_general_ci

    host=127.0.0.1
    port=3306 
    user=USERNAME
    password=PASSWORD (or omitted)

Or does it need [production] in there?

Note: in all cases the database is local and closed to external access as it may contain sensitive information.

**Comment by evanelias** [comment]
> Is this what I need it to create?

I think that will work, but can't predict for certain, as your use-case is unique. Try it and see if it works?

> Or does it need [production] in there?

It depends on what you're trying to do / whether or not you have other named environments.

Options that appear at the top of the file, prior to any environment name, are always applied to all environments. These may be overridden by options subsequently appearing in a specific environment. More info and example:

* https://github.com/skeema/skeema/blob/master/doc/config.md#specifying-options-via-option-files
* https://github.com/skeema/skeema/blob/master/doc/examples.md#advanced-configuration

**Comment by waveney** [comment]
It works (as far as I can tell) - I will now close it.
