### ISSUE TITLE
Unsupported diff if foreign key uses NO ACTION clause

### ISSUE THREAD

**Issue by mugli** [skeema/skeema#50]
A foreign key constraint is defined in the skeema generated .sql file as:

```
CONSTRAINT `xyz_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
```

On target database/table, it is also the same:
```
CONSTRAINT `xyz_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
```

But the `diff --debug` command shows:

```
2018-12-02 18:15:25 [WARN]  Skipping table xyz: unable to generate ALTER TABLE due to use of unsupported features. Use --debug for more information.
2018-12-02 18:15:25 [DEBUG] --- Expected
2018-12-02 18:15:25 [DEBUG] +++ MySQL-actual
2018-12-02 18:15:25 [DEBUG] @@ -11 +11 @@
2018-12-02 18:15:25 [DEBUG] -  CONSTRAINT `xyz_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
2018-12-02 18:15:25 [DEBUG] +  CONSTRAINT `xyz_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
```

I'm using `skeema version 1.1.2-dev (snapshot build from source)` with mysql 5.6

**Comment by evanelias** [comment]
Thank you for the issue report! Verified as described. Should be an easy fix.

For background on this Skeema bug, in MySQL foreign keys these 3 clauses all [have the exact same effect](https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html#foreign-keys-referential-actions):
* `ON DELETE NO ACTION`
* `ON DELETE RESTRICT`
* Omitting the `ON DELETE` clause entirely

If you specify `ON DELETE RESTRICT`, MySQL removes the clause from `SHOW CREATE TABLE`, since it's equivalent to omitting the clause. However, if you specify `ON DELETE NO ACTION`,  apparently MySQL still displays the clause in `SHOW CREATE TABLE` even though it has no effect. The current logic in Skeema assumes the clause should be omitted (just like the equivalent handling of `RESTRICT`), which is what breaks the diff logic's safety-check.

Above is also true for foreign key `ON UPDATE` clauses as well.

I should have a fix in master later today. It might be a week or two until I make another prebuilt binary release, but it sounds like you're building from source anyway, so hopefully that isn't a problem. Or a temporary work-around would be to use "RESTRICT" in place of "NO ACTION" since the two are equivalent in functionality.

**Comment by mugli** [comment]
Awesome! I'll build from the source, that's totally fine. Thank you for looking into it so promptly 👍

**Comment by evanelias** [comment]
Now fixed in master branch. Thanks again for reporting this!
