### ISSUE TITLE
Add the ability to manage non partitioned columns in tables with partitions

### ISSUE THREAD

**Issue by silviabotros** [skeema/skeema#57]
Understanding that skeema is not yet ready to manage partitions, it seems right now that it nopes out of doing any action on tables with partitions including adding a 'normal' column which would operate under the hood the same as any other schema change using the `alter-wrapper`

It would be great if at least some limited functionality is allowed in the case of partitioned tables where no partition specific changes are being attempted.

**Comment by evanelias** [comment]
I agree completely. The ability to manipulate other parts of a partitioned table (i.e. aside from the partitioning clauses) would definitely be a good improvement.

For background on the current functionality, where it refuses to diff/alter any part of an existing partitioned table: 

Skeema performs table introspection by querying `information_schema` and running various `SHOW` commands. It has a safety mechanism where it ensures its "understanding" of a table is correct by comparing the output of `SHOW CREATE TABLE` to what the tool *thinks* the canonical `CREATE TABLE` should be for the given mysql flavor/version. If they differ, Skeema refuses to diff/alter the table in any way.

Between this and other safety checks, it should be impossible for Skeema to ever run the "wrong" ALTER -- whether due to an obscure difference in some new mysql flavor/version, or due to a logic bug in Skeema itself. Instead, Skeema just refuses to modify a table that it doesn't fully understand.

The downside is extra complexity for things like partitioning, where the `SHOW CREATE TABLE` comparison would need to be smart enough to optionally ignore the specific partition list. There's precedent for this in Skeema's handling of AUTO_INCREMENT, but that's a simpler case to support.

In terms of overall path to partitioning support, it could come in a few stages:

1. Ability to alter other parts of an already-partitioned table (this issue).

2. Ability to partition a previously unpartitioned table; or remove partitioning from a partitioned table; or change the PARTITION BY expression of a partitioned table.

3. Ability to manage the partition list for an already-partitioned table. I suspect this is better left to a separate tool, with partition list changes automated in a way separate from a schema repo. But I'm eager to hear more about different companies' ideal workflow to see what makes the most sense.

One potential point of complexity, in all of these stages, is flavor/version related differences. I know that MySQL 8 removed the old "generic" partitioning support, in favor of storage-engine handling of partitioning, but I haven't researched what this entails yet.

Ideally I'd like to start tackling partitioning support in a few months, but definitely willing to adjust priority based on community feedback. Also always open to third-party contribution (I could give guidance on possible implementation paths) or sponsored development (where a company pays for the feature to be added more quickly, and/or supporting a specific workflow).

**Comment by evanelias** [comment]
I'm happy to announce that today's release of [Skeema v1.4.0](https://github.com/skeema/skeema/releases/tag/v1.4.0) includes support for managing partitioned tables. See [usage notes](https://github.com/skeema/skeema/blob/v1.4.0/doc/requirements.md#partitioned-tables) and the new [partitioning option](https://github.com/skeema/skeema/blob/v1.4.0/doc/options.md#partitioning) to customize Skeema's partitioning behavior.

Huge thank you to [Etsy](https://www.etsy.com) for generously sponsoring the development of this functionality!
