### ISSUE TITLE
Can we specify acceptable timeouts ?

### ISSUE THREAD

**Issue by d33psky** [skeema/skeema#67]
Happily using skeema on 3 database servers, but the 4th always times out : 
```
[mysql] 2019/03/28 12:07:33 packets.go:36: read tcp 1.2.3.4:47520->1.2.3.5:3306: i/o timeout
```
This timeout is 5 seconds. tcpdump shows skeema traversing all databases.

This happens on a mysql server with a few databases where one has over 500 tables, the other 3 mysql servers are small with just a few databases with about 20 tables.

Maybe I'm doing something wrong as I'm only interested in managing a single database with only a few tables. I saw no way to make skeema ignore the other database with hundreds of tables. Or how to increase the timeout from 5 seconds.

**Comment by evanelias** [comment]
You can ignore databases using the [ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) option, and/or ignore tables using the [ignore-table](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-table) option.

Alternatively, if you only want to manage a single schema on a particular db server, supply the [--schema](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) option on the command line when you first run `skeema init`. This will "flatten" the directory layout for that server.

You can configure timeouts (connect, read, write) using the [connect-options](https://github.com/skeema/skeema/blob/master/doc/options.md#connect-options) option. Scroll towards the bottom for the driver/protocol settings.

When operating on databases with high table counts, I recommend running Skeema in the same data center as the database server if possible, rather than running from a local laptop/desktop. Or in cases where there's unavoidable high network latency, using [workspace=docker](https://github.com/skeema/skeema/blob/master/doc/options.md#workspace) can help.

> I saw no way to make skeema ignore the other database with hundreds of tables. Or how to increase the timeout from 5 seconds.

In general I would recommend using GitHub's repo search functionality to find relevant docs and previous issues.
