### ISSUE TITLE
go get pulls v 1.2.1-dev, not 1.2.2

### ISSUE THREAD

**Issue by cglendenning** [skeema/skeema#69]
Hi Evan, 

go get -ldflags "-s -w" github.com/skeema/skeema builds v 1.2.1-dev, but 1.2.2 is the latest release.

**Comment by evanelias** [comment]
Thank you for the issue report! It seems I forgot to bump the fallback version text used by `skeema version` in the last release. So even though `skeema version` is outputting `v1.2.1-dev` when built from `go get`, it's really the HEAD of master, i.e. currently 1.2.2 plus potentially some newer commits.

The [precompiled releases](https://github.com/skeema/skeema/releases) always report the correct version, since the build pipeline automatically compiles in the version string from the corresponding git tag. But builds from source (including `go get`) currently rely on fallback text that I manually change each release. I'll look into automating that at some point, but in the meantime, I'll fix the version in master momentarily. Thanks again for catching this!

**Comment by cglendenning** [comment]
Thank you for the quick fix!

I did not realize it was cosmetic, and was actually building 1.2.2 + commits. 

Craig
