### ISSUE TITLE
[Q] Best way to run DML statements against many DBs and shards

### ISSUE THREAD

**Issue by slisznia** [skeema/skeema#77]
Skeema has helped us bring hundreds of shards over tens of instances in sync. THANK YOU. 

What (CLI) tool or toolset do you recommend for issuing queries/DML statements across the cluster? For example, on occasion we populate the shards with const or default data, or apply common data transformations. We use a combination of ssh/make to run the commands but we want to make this process more formal where a script would assert pre-conditions (state of the data before running the statements), apply, validate post-condition, commit. This could be done to all or a rolling update.

**Comment by evanelias** [comment]
Thanks for using Skeema, and very glad to hear the sharding support is proving to be useful!

DML is tough to tackle generically in a system like Skeema, since the desired use-cases and workflows vary significantly between companies/users. In the near-term, the most likely stepping-stone towards DML support will just be extra hook points, to allow Skeema users to configure custom scripts that Skeema will execute on each db/shard before or after each push. Some discussion in https://github.com/skeema/skeema/issues/22#issuecomment-477743720.

In terms of what tool to use once hooks are supported -- depends a bit on whether you're doing fairly straightforward write queries for simple changes, vs diff'ing data for seed data, vs doing complex multi-step migrations across all shards. Many companies roll their own. For open source things to look at for inspiration in sharded environments, some examples range from parallel-querying tools like [pmysql](https://dom.as/2010/08/12/pmysql-multi-server-mysql-client/) and [ccql](https://github.com/github/ccql), to more complex migration frameworks like [Jetpants](https://github.com/tumblr/jetpants) (disclaimer: I'm the original author, but haven't been involved in years) or more modern toolkits like [Ghostferry](https://github.com/Shopify/ghostferry).

**Comment by evanelias** [comment]
Closing this out, but please feel free to re-open if you have any follow-up questions.

On a slightly different topic, just wanted to add a quick plug for the newly-launched [Skeema.io CI beta](https://www.skeema.io/ci/). I'd love to get some beta testers with interesting setups, such as your sharded environment. If your Skeema-managed schema repo is stored on GitHub, the new CI system provides automated linting and diff'ing of commits and pull requests -- directly from your repo, without any need to connect to your actual databases. Check it out if you have some time, no pressure though :)

**Comment by slisznia** [comment]
Sounds really promising - is this github-specific integration? We use bitbucket.

**Comment by evanelias** [comment]
Currently it only supports GitHub, since their [Checks API](https://github.blog/2018-05-07-introducing-checks-api/) made the development process a lot easier. Hope to offer a BitBucket version in the future though!
