### ISSUE TITLE
"Failed to parse" on empty stored procedure

### ISSUE THREAD

**Issue by apapsch** [skeema/skeema#81]
When diffing the schema against one particular environment, skeema may fail with a rather generic error message:

```
$ skeema diff --allow-unsafe --debug -p stage
Enter password: 
2019-07-02 13:19:08 [DEBUG] Instance 127.0.0.1:3346 flavor cannot be parsed; using dir /home/[...] configured flavor mysql:5.7 instead
2019-07-02 13:19:17 [WARN]  Skipping 127.0.0.1:3346 for /home/[...]: Failed to parse 
2019-07-02 13:19:17 [ERROR] Skipped 1 operation due to error
2019-07-02 13:19:17 [DEBUG] Exit code 2
```

I found one instance of the string `Failed to parse` in `./vendor/github.com/skeema/tengo/instance.go:1140` (regarding stored procedures):

```
return fmt.Errorf("Failed to parse %s", r.CreateStatement)
```

So, CreateStatement must be empty. Skeema selects from `information_schema.routines`, where `routine_definition` is indeed `NULL` in that environment. I suspect it's a bug or someone is working on that procedure (the culprit has not come forward, yet).

Anyway, how should empty stored procedures be treated? My suggestions:

* Create the procedure just as empty.
* Skip the procedure, logging a warning.

**Comment by evanelias** [comment]
Thank you for the report! Unfortunately I'm unable to reproduce this scenario so far.

In this code path, `r.CreateStatement` isn't actually coming from `information_schema.routines`; rather, it's coming from the output of `SHOW CREATE PROCEDURE` / `SHOW CREATE FUNCTION`. So far I can't seem to find a situation in which that SHOW command is valid and yet returns a blank creation string, nor can I find a way to create an empty routine at all...

A few questions to help debug this:

1. What vendor and version of MySQL are you using? The warning about `flavor cannot be parsed` is potentially a bad sign... would you mind posting the output of this query please? 
```sql
SELECT @@global.version_comment, @@global.version;
```

2. Is this a function or is it a procedure?

3. What's the full output of `SHOW CREATE PROCEDURE` / `SHOW CREATE FUNCTION` ?

4. What happens when you actually call this routine in mysql?

5. Just to confirm, this routine is not a native (c/c++) UDF or a mariadb package, correct? (re: last two bullets of https://github.com/skeema/skeema/blob/master/doc/requirements.md#edge-cases-for-routines)

Please feel free to edit out sensitive info in your answers, and/or reach out privately via email using the support address on https://github.com/skeema. Thanks again! I just want to make sure I have a valid repro case for this before attempting a patch, since otherwise there's no way to add an integration test for it.

**Comment by apapsch** [comment]
> What vendor and version of MySQL are you using?

```
@@global.version_comment    @@global.version
--------------------------  ---------------------------
(Ubuntu)                    5.7.26-0ubuntu0.18.04.1-log
1 row in set
```

It is the mysql-server-core-5.7 Ubuntu package.

> Is this a function or is it a procedure?

It's a procedure.

> What's the full output of SHOW CREATE PROCEDURE / SHOW CREATE FUNCTION ?

```
Procedure       sql_mode                Create Procedure    character_set_client    collation_connection    Database Collation
--------------  ----------------------  ------------------  ----------------------  ----------------------  --------------------
kop2_shop_load  NO_ENGINE_SUBSTITUTION  <null>              utf8mb4                 utf8mb4_general_ci      utf8_unicode_ci
```

> What happens when you actually call this routine in mysql?

I'd rather not, because I've never run it and it does many things.

> Just to confirm, this routine is not a native (c/c++) UDF or a mariadb package, correct?

Yes, it's none of that.

I dug a bit more and found this bit in the [MariaDB docs](https://mariadb.com/kb/en/library/show-create-procedure/):

> [SHOW CREATE PROCEDURE requires] that you are the owner of the routine or have the SELECT privilege on the mysql.proc table. When neither is true, the statements display NULL for the Create Procedure or Create Function field.

In fact, the procedure was created with a special user, and `skeema diff` uses another user which does not have the SELECT privilege on mysql.proc. Luckily, this means no big bug to hunt down. I would still send a PR for a clearer error message though. In `func (instance *Instance) querySchemaRoutines` after the `if` of line 1075, I'd return an error if the CREATE code is empty, suggesting to check the privileges.

**Comment by apapsch** [comment]
With the SELECT privilege, skeema now has no problem anymore. (It creates a DROP PROCEDURE though, which will not work, because the skeema mysql user does not have the ALTER PROCEDURE privilege).

**Comment by evanelias** [comment]
> It is the mysql-server-core-5.7 Ubuntu package

Ah, thanks! I'll add code to map Ubuntu's version comments to standard MySQL.

> In fact, the procedure was created with a special user, and skeema diff uses another user which does not have the SELECT privilege on mysql.proc.

Excellent find, thank you!

> In func (instance *Instance) querySchemaRoutines after the if of line 1075, I'd return an error if the CREATE code is empty, suggesting to check the privileges.

I agree. I'll make this change soon and will also update the docs around permissions and routines. The only tricky thing is some version-related differences; at minimum I know that MySQL 8.0 has completely different permission behavior here.

> It creates a DROP PROCEDURE though, which will not work, because the skeema mysql user does not have the ALTER PROCEDURE privilege

Makes sense. Out of curiosity is the DROP expected in this case? i.e. are you actively trying to modify or drop the procedure? Or does this procedure only exist on some environments, and didn't exist on the environment used in `skeema init`?

**Comment by evanelias** [comment]
Now fixed in master. I ended up taking a slightly different approach -- rather than erroring, Skeema will now just ignore any routines with inaccessible bodies. 

Definitely some trade-offs there... silently ignoring things may be non-ideal for some users, but it does permit Skeema to be functional for users who intentionally have some routines that should not be touched/managed by automation. And this behavior is more consistent with how other privilege problems work -- in most other cases, if Skeema's user can't see something, it simply doesn't manifest in information_schema at all anyway.

In any case, I updated the docs a bit to mention some of the privileges related to managing routines.

Thank you again for the issue report and for digging in to the root cause!

**Comment by apapsch** [comment]
That was fast, thank you! The chosen trade-offs seem fine to me.

> Out of curiosity is the DROP expected in this case? i.e. are you actively trying to modify or drop the procedure? Or does this procedure only exist on some environments, and didn't exist on the environment used in skeema init?

I inititalized using the production environment and then diffed to the stage environment. The procedure only exists in stage currently. I wanted to get a clear picture of the differences between the environments (one of the strong points of skeema, you can easily compare). I'd not have pushed to stage, thus dropping the procedures. Once I got the SELECT privilege for mysql.proc, I pulled from stage.
