### ISSUE TITLE
Question regarding multiple schemas with general tablespace

### ISSUE THREAD

**Issue by egezonberisha** [skeema/skeema#87]
Context:

For example, in cases where one DB represents one customer, we are mapping schemas using schema option, so we maintain one sql file/table across all DBs. And that is working fine.

Problem:

In cases where each database lives is in their own tablespace (using general tablespace), and adding new tables does not place each table in the tablespace of the database. What do you recommend for this case.
Do you plan to cover this case in the future? Since this is not very common I guess, I wonder if you take PRs, I was thinking if we could come up with an option something like `tablespce-wrapper` that allows the following options:
```
1. tablespce-wrapper="some_executable_script"
2. tablespce-wrapper="hardcoded_string"
3. tablespce-wrapper=SAME_NAME_AS_DB + "some_suffix"
```
The above is just something I came up with now, not sure if there are much better ways or there is an easier ways to implement this.

Thanks!

**Comment by evanelias** [comment]
Interesting question, thanks! I'd have to think more about this... using 1 shared tablespace per database schema is honestly not something I have experience with. If you're able to share, would you mind describing the motivation / use-case in more depth, vs using file-per-table? (Is it just based on file-per-table metadata memory bloat from having many many shards per mysqld and many tables per shard?)

Anyway, if possible I'd lean towards a more generic solution involving DDL string manipulation, rather than something specific to tablespaces. Currently you could solve this in Skeema using a custom script in [ddl-wrapper](https://github.com/skeema/skeema/blob/master/doc/options.md#ddl-wrapper):
* At minimum, pass in `{HOST}`, `{SCHEMA}`, `{DDL}`, `{CLASS}`, `{TYPE}` to the script; maybe others too
* Your script could check if `{CLASS}` is "TABLE" and `{TYPE}`is "CREATE", then manipulate the `{DDL}` string using regexes:
  * If the string already contains a TABLESPACE clause, rewrite it to be correct for the `{SCHEMA}`. (Otherwise it may be wrong in the filesystem if you ever use `skeema pull`.)
  * Otherwise, add a TABLESPACE clause at the end of the DDL string
* Execute the DDL string against the `{HOST}` and `{SCHEMA}`
* Exit code 0 if the DDL execution was successful, 1+ if not

This can be slightly annoying to implement though, due to having to code the execution step. In other words, `skeema push` won't execute the DDL for you if using `ddl-wrapper`; responsibility for that falls to the wrapper.

I'm considering adding new hook options i.e. `pre-push-hook` to make this a bit easier. The STDOUT of a `pre-push-hook` script could be read by Skeema and used in place of the original DDL. That way, the hook script can focus purely on string manipulation, but still have Skeema execute the DDL as usual. I haven't totally decided about this yet though.

**Comment by egezonberisha** [comment]
Interesting, looks like the `ddl-wrapper` might work for us, will give that a try and see how it goes. 

The reason why we used a general tablespace (one for db) is because we have too many DBs(many tables per DB), and we wanted to reduce the number of files, so the general tablespace worked for us.
