### ISSUE TITLE
Error when starting docker container inside another docker container

### ISSUE THREAD

**Issue by Gerben-T** [skeema/skeema#89]
My setup: Windows Ubuntu subsystem -> Docker container Ubuntu 18.04 -> Skeema --workspace=DOCKER --flavor=percona:5.7

When running `skeema diff` i get the following error:
```
2019-07-26 12:48:02 [INFO]  Using container skeema-percona-5.7 (image=percona:5.7) for workspace operations
2019-07-26 12:48:02 [WARN]  Skipping /home: Get http://unix.sock/containers/skeema-percona-5.7/json: dial unix /var/run/docker.sock: connect: no such file or directory

2019-07-26 12:48:02 [ERROR] Skipped 1 operation due to error
```

For my build server i need to be able to run Skeema inside a Docker container, that's why this setup looks so weird.

**Comment by Gerben-T** [comment]
Okay so i may have found a "fix".

Reading https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker

I changed my docker command to the following:
```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock ubuntu:18.04 /bin/bash
```

It still failed, but with a different error:
```
2019-07-26 13:54:09 [INFO]  Using container skeema-percona-5.7 (image=percona:5.7) for workspace operations
2019-07-26 13:54:39 [WARN]  Skipping /home: dial tcp 127.0.0.1:32768: getsockopt: connection refused

2019-07-26 13:54:39 [ERROR] Skipped 1 operation due to error
```

After reading https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

I again changed my docker command:
```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock --network="host" ubuntu:18.04 /bin/bash
```

Which made it work.

Now i don't know if this is a proper fix or if i might get into some trouble in the future, but for now it looks like it works.

**Comment by evanelias** [comment]
Yes, exactly, this is a limitation of Docker itself. If you need to run Skeema inside of a Docker container, you basically have 3 options, all of which have different trade-offs:

a) Stay with the default of `workspace=temp-schema`, so that Skeema does not need to interact with additional Docker containers.

b) Bind-mount the Docker socket into Skeema's container (the solution you've described above). Functionally, this should generally work fine. Operationally, it may be problematic in container orchestration systems like Kubernetes. It can also be a theoretical security concern, however in that respect it should be no different than running Skeema outside of a container.

c) Run a separate Docker daemon *inside* Skeema's container. In theory this should be possible if running Skeema in a privileged image that inherits from a Docker-in-Docker (dind) image, such as the official one at https://hub.docker.com/_/docker/. This has some [complications](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) though, especially around image caching.

I'll update the docs for Skeema's `workspace` option to mention this situation. Sorry this wasn't documented previously!

**Comment by evanelias** [comment]
In case anyone is still watching this issue: if you use workspace=docker combined with running Skeema itself from a container, the proposal in #186 may affect you. Feedback on that issue would be greatly appreciated -- thanks!
