### ISSUE TITLE
pxc_strict_mode=ENFORCING

### ISSUE THREAD

**Issue by 529** [skeema/skeema#9]
I have a question.
I use PXC5.7.
pxc_strict_mode  is 'ENFORCING';
I try to Execute 'skeema diff'.
The following error occurs.
```
 [ERROR] Skipping xxxx Unable to lock temporary schema on xxxx:3306: Unable to acquire lock
```
Can I use it without LOCK?

https://github.com/skeema/skeema/blob/611b1b9fec33098b21b5e62c1e948f95deffff9a/target.go#L362

regards.

**Comment by evanelias** [comment]
Thank you for trying out Skeema! 

The `GET_LOCK` call is an important safety mechanism to prevent two simultaneous executions of Skeema from interfering with each other in a dangerous way. It's far from a comprehensive solution, since the locks are only held while Skeema performs operations in its temporary scratch-space db, and not while a long ALTER TABLE runs, for example. But it does prevent the worst class of possible collisions, where Skeema's diff logic could do the wrong thing if 2 copies of Skeema are stomping on each others' scratch space operations.

So removing the locking is risky, unless you have some other solution in place to prevent 2 simultaneous copies of Skeema from running at once. And I should also mention that Skeema has not been tested on Galera-based clustering solutions (including PXC) at all, so PXC isn't considered [supported](https://github.com/skeema/skeema/blob/master/doc/requirements.md#mysql-version-and-flavor) yet anyway. 

That all said, if you want to give this a try (at your own risk!) you can compile Skeema with the locking calls removed. Edit target.go and replace the last two methods in the file with:
```go
func (t *Target) lockTempSchema(maxWait time.Duration) (*sql.Tx, error) {
    return nil, nil
}

func (t *Target) unlockTempSchema(tx *sql.Tx) error {
    return nil
}
```

You'll also have to remove the import of `errors` at the top of target.go. After that, `go install` should be able to compile Skeema successfully with the locking removed.

If you give that a try, please let me know how that goes! If that's currently the only blocker around using Skeema with Galera/PXC, I can definitely make the locking configurable. But I suspect there may be other caveats, and Skeema may also need addition functionality to support both possible values of Galera's `wsrep_OSU_method` option.

**Comment by evanelias** [comment]
Just wanted to check in on this. Any luck using Skeema with PXC with the above hack, or did you encounter any other problems?
