### ISSUE TITLE
Backticks in {CLAUSE} mess up my alter-wrapper

### ISSUE THREAD

**Issue by Gerben-T** [skeema/skeema#91]
I'm trying to echo my percona commands to a file using the `alter-wrapper` options, but the backticks in the `{CLAUSE}` part are messing up the wrapper as you can see below.

```
\! echo "pt-online-schema-change --dry-run --alter 'ADD COLUMN `test` varchar(450) DEFAULT NULL' D=xxx,t=xxx,h=xxx,P=xxx,u=xxx,p=xxx" >> /skeema_wrapper_output
/bin/sh: 1: test: not found
2019-08-02 09:24:39 [INFO]  xxx:xxx xxx: push complete
```

My `alter-wrapper`:
```
alter-wrapper=echo "pt-online-schema-change --dry-run --alter {CLAUSES} D={SCHEMA},t={TABLE},h={HOST},P={PORT},u={USER},p={PASSWORDX}" >> /skeema_wrapper_output
```

What is the best way to echo all my commands to a file?

**Comment by Gerben-T** [comment]
It seems to work by surrounding the `{CLAUSE}` with a single-qoute followed by a double-qoute
```
alter-wrapper=echo "pt-online-schema-change --dry-run --alter '"{CLAUSES}"' D={SCHEMA},t={TABLE},h={HOST},P={PORT},u={USER},p={PASSWORDX}" >> /skeema_wrapper_output
```

**Comment by evanelias** [comment]
Yeah, this is due to quoting behavior of the Bourne shell, which is outside of Skeema's control. This doesn't normally come up if you're using a real command and not `echo`.

Side topic but can you describe your use-case in more detail? I generally don't recommend using an alter-wrapper of `echo`, as this prevents `skeema push` from actually pushing. This is not guaranteed to work in future versions -- it's possible `push` may have extra verifications of the success of the push in the future.

If you just want to generate pt-osc command lines from an automated pipeline, I usually recommend invoking `skeema diff | tee some-file`. Or if you need to remove the `\! ` prefixes on shell-outs, this could be filtered by putting something like `sed` in the middle of the pipeline.

I've also considered supporting alter-wrapper output in the automatic diff comments in the [hosted CI system](https://www.skeema.io/ci/), but handling of passwords becomes problematic there, and ditto for size-based options like `alter-wrapper-min-size`.

**Comment by Gerben-T** [comment]
Well, i'm doing it this way because we have a special user for doing alters. This user only has localhost access on our database server due to security.

The build server, where i'm running skeema, is a seperate server and thus should not execute any alters.

My workflow is:
1. Skeema diff
2. Fail if any errors are found
3. Skeema push (with the `alter-wrapper`)
4. Execute all commands, in the output file, on the database server through SSH
