### ISSUE TITLE
Circular foreign key support

### ISSUE THREAD

**Issue by trevorr** [skeema/skeema#92]
In SQL, it's valid for two (or more) tables to have foreign key references to one another (assuming at least one is nullable). When creating such tables, it's necessary to break the cycle by creating at least some of the foreign key constraints after the tables exist (i.e. using ALTER TABLE). I'm dealing with such a schema, so I'm wondering, does or should skeema support this?

For reasons discussed in #11, I'm somewhat ambivalent about using foreign keys in production. However, I think they're valuable for use in development, so I've separated them out into a separate file (which skeema will warn about: "Ignoring unsupported or unparseable SQL statement"). This seemed like a handy workaround for the circular issue, but the problem I then run into is that skeema wants to drop all the foreign keys when I run diff or push. Perhaps this could be fixed by a flag to ignore foreign keys?

As context for my approach, I'm trying to use the same SQL scripts for creating a new development database as are used to migrate the production database. I'm using the MySQL docker image, which has a handy feature that any SQL (or shell) scripts in `/docker-entrypoint-initdb.d` get run on first-time database initialization in sorted filename order. Therefore, my foreign key constraints script is alongside the table creation scripts with a filename that sorts last. Is there a way to get skeema to ignore this file to suppress the warnings mentioned above?

**Comment by evanelias** [comment]
> does or should skeema support this?

I believe circular foreign keys already work properly in Skeema, since Skeema operates using `foreign_key_checks=0` in its sessions by default. (This is [configurable](https://github.com/skeema/skeema/blob/master/doc/options.md#foreign-key-checks), but enabling FK checks can definitely lead to order-of-operation problems, so I don't recommend it.)

With the default of disabling FK checks, I believe situations involving circular references are fine:
* Adding 2 new tables that reference each other: no errors, since `foreign_key_checks=0` prevents MySQL from erroring when an FK refers to a nonexistent table
* Adding a new FK to an existing table, that references a new column in another existing table: this should also be ok, Skeema orders multiple operations such that FK-adding ALTERs always happen last, after all other CREATEs and ALTERs

If you have a circular FK situation that leads to an error though, please let me know!

Also, one important caveat -- all of the above only works properly within a single database schema. If you have FKs that cross database boundaries, you may need to manually order your pushes to avoid errors in general, and there may be major problems with circular references.

> Perhaps this could be fixed by a flag to ignore foreign keys?

That could work in theory, but the use-case (FKs in dev but not prod) seems somewhat rare. I'm already pretty hesitant about any new FK-specific features in general; more explanation [here](https://github.com/skeema/skeema/pull/79#issuecomment-508889996).

> Is there a way to get skeema to ignore this file to suppress the warnings mentioned above?

Not yet, although I've thought about adding options to control which files are included/excluded in a directory for a different feature; see 2nd bullet [here](https://github.com/skeema/skeema/issues/22#issuecomment-459907251). No concrete timeline for that yet though.

**Comment by trevorr** [comment]
> I believe circular foreign keys already work properly in Skeema, since Skeema operates using foreign_key_checks=0 in its sessions by default.

I think I see what you mean. I had thought that option just applied to DML or ALTER TABLE with existing data, but I see it also applies to CREATE TABLE, such that the referenced table needn't even exist yet. If skeema is pushing my new tables, it will run with `foreign_key_checks=0`. If I want to initialize the database myself with them (e.g. using `/docker-entrypoint-initdb.d`), I need to `set foreign_key_checks=0` too (either in each file or by temporarily changing the server setting).

> That could work in theory, but the use-case (FKs in dev but not prod) seems somewhat rare.

I'll admit it was just an idea that occurred to me. It seems best to avoid FKs in production, but it would be nice to identify RI bugs early in dev and test. It would only be feasible on new code, but I'm lucky enough to have that. Still, I think for now I can mostly forego FKs in dev, and just use the FK creation script in automated/transient test environments that don't use skeema.

> I've thought about adding options to control which files are included/excluded in a directory for a different feature

I'm trying to figure out seed data and data migrations myself. It seems like there needs to be a language/framework-agnostic migration tool that builds on skeema the same way skeema builds on OSC tools. For instance, skeema diffs could provide SQL- or OSC-based changeset scripts to roll forward and backward to a migration tool (a la Liquibase or Flyway but less cumbersome) that tracks which changesets have been applied. Ideally, it could just base its changesets off git commits, and figure out what to apply by following the branching structure. Of course, now I'm just dreaming.

I'll close this issue, as it seems like any possible changes are being tracked elsewhere. Thanks for the quick response!

**Comment by evanelias** [comment]
>  I see it also applies to CREATE TABLE, such that the referenced table needn't even exist yet.

Yes, exactly. The behavior of MySQL's `foreign_key_checks=0` is a bit confusing in that way: it permits references to nonexistent tables. Yet for some reason it does *not* permit references to nonexistent *columns* in tables that *do* already exist, which can cause some order-of-operation headaches. Skeema does some simple reordering to try to prevent the most common ordering problems within a single database, but there's still potential for edge cases requiring manual adjustment.

> It seems like there needs to be a language/framework-agnostic migration tool that builds on skeema the same way skeema builds on OSC tools.

I agree, though it's a complex problem space to solve generically. The requirements can vary quite a bit between different companies. For example, executing DML is straightforward with reasonable table sizes. But with a very large table, it becomes necessary to split DML statements into smaller chunks to avoid huge transactions, ideally tracking those chunks though some sort of persistent task queue with configurable levels of concurrency.

>  Ideally, it could just base its changesets off git commits, and figure out what to apply by following the branching structure

I've thought about this a bit too. It could work reasonably well as long as the tool is stateful (persisting which commit was last applied) and git-specific. For that reason it would probably be a separate system built on top of the Skeema CLI (or using the CLI's subpackages as libraries), to allow the CLI to remain stateless and SCM-agnostic.

Even so, there are some challenging edge cases, like what to do if the most recent applied change becomes an orphaned commit (e.g. if the git history is rewritten by a forced push after a rebase or amend). Anyway, this is all pretty far out in the future :)
