### ISSUE TITLE
Add option for workspace query concurrency to override default=10

### ISSUE THREAD

**Issue by paulcaskey** [skeema/skeema#93]
Even with --concurrent-instances=1 (default), "skeema diff" performs its create - test - drop TABLE operations 10 at a time. That number (10) is too low in some environments, and too high in others. In some cases, a stream of CREATE and DROP operations over hundreds of temp tables can choke out normal operation of mysqld due to the Linux mutex contention.

**Comment by evanelias** [comment]
Thank you for the feature request! Just to clarify a few details here, in case an open source contributor wants to pick this up before I get a chance:

* This would be handled by a new option (maybe `workspace-concurrency`) which would then get passed through as a new field in [workspace.Options](https://github.com/skeema/skeema/blob/707fd2f6fb62c2a8531ec605ae3780c7e642567e/workspace/workspace.go#L73), populated by [workspace.OptionsForDir()](https://github.com/skeema/skeema/blob/707fd2f6fb62c2a8531ec605ae3780c7e642567e/workspace/workspace.go#L108).
* Workspace table *creation* concurrency is handled in [workspace.ExecLogicalSchema()](https://github.com/skeema/skeema/blob/707fd2f6fb62c2a8531ec605ae3780c7e642567e/workspace/workspace.go#L254-L255). This one is easy to change since the opts struct value is already available here.
* Workspace table *drop* concurrency is more annoying to change. This is handled by each Workspace implementation in its Cleanup() function, by calling [tengo.DropTablesInSchema()](https://github.com/skeema/tengo/blob/e2da95da8db3cbb0f2e5c7a8dc6de57c686355b3/instance.go#L545). It would need a new third param indicating concurrency, or perhaps its second param (currently a bool) should be changed to a new options struct. Either way, this breaks backwards compatibility... but since tengo is pre-1.0, that's acceptable (albeit non-ideal).
* Potentially this new option could/should also affect schema *introspection* concurrency in several other places in tengo's instance.go. Undecided on this.
* Overall this issue is unrelated to `concurrent-instances`. (That option controls concurrency among multiple mysqld instances in a sharded environment; it has no involvement with concurrency within a single mysqld instance.)

**Comment by evanelias** [comment]
Happy to say this is now implemented in the master branch, and will be included in the release of Skeema v1.4, currently planned for later this month.

First, some background on what I found doing testing on Skeema's previous concurrency defaults:
* For most users, dict_sys mutex contention shouldn't be a major problem; running Skeema with its default of `workspace=temp-schema` generally won't cause a noticeable impact to production queries.
* Users with a very large number of tables may encounter problems though, especially if the normal query workload also involves high client connection counts. Increasing the size of MySQL's table cache can help, but this has memory implications.
* Another major cause of dict_sys contention is workloads involving inserts to InnoDB tables that lack a primary key. Skeema's previous concurrency defaults could be problematic for workloads with many such inserts.
* I suspect extensive use of foreign keys may make the contention worse (since at minimum it increases the amount of work that each CREATE or DROP does), but I didn't explore this.
* MySQL 8's new data dictionary greatly improves the situation (less contention there).

Two new options have been implemented in Skeema to address this:
* [temp-schema-threads](https://github.com/skeema/skeema/blob/master/doc/options.md#temp-schema-threads) controls concurrency for workspace operations. The default is 5, just to lean on the safer side (relative to Skeema's previous hardcoded value of 10).
* [temp-schema-binlog](https://github.com/skeema/skeema/blob/master/doc/options.md#temp-schema-binlog) controls whether or not workspace operations are written to the binary log. The default is to auto-detect whether or not Skeema's user has sufficient privs to set `sql_log_bin=0` for workspace sessions, and skip binlogging when possible. Users may reconfigure this to "off" to never write the workspace queries to binlog (fatal error if insufficient privs), or "on" to always write to binlog.
