### ISSUE TITLE
cannot parse stored procedure

### ISSUE THREAD

**Issue by obissick** [skeema/skeema#95]
Failed to parse stored procedure from MariaDB.

Getting parse error on init.
2019-08-14 14:18:07 [DEBUG] Exit code 2

**Comment by evanelias** [comment]
Thank you for the issue report. Can you please share the CREATE statement for the procedure generating this error? I can't debug this without that info. If you cannot post it publicly, please e-mail the support address listed on https://github.com/skeema -- thanks!

**Comment by obissick** [comment]
I sent it in the email, thanks.

**Comment by evanelias** [comment]
Received, thank you! I haven't been able to reproduce the problem on that proc though. Can you please let me know what version of MariaDB and what version of Skeema you're using? Thanks!

**Comment by obissick** [comment]
i am using the latest version of Skeema and i forgot i recently updated or dev servers to MariaDB 10.4 which is not in the support list. I did try with MariaDB 10.3 and i still get that error but for a different procedure.

**Comment by evanelias** [comment]
Thanks, yeah MariaDB 10.4 is not supported yet. I hope to add support in Skeema 1.3 but have not started looking into it yet.

Can you please e-mail me the error / procedure body that you're encountering with MariaDB 10.3? I can't debug this until I can fully reproduce the issue in my environment. Thanks!

**Comment by obissick** [comment]
ok sounds good. I just sent the one from 10.3.

**Comment by evanelias** [comment]
Awesome, thank you! After a lot of digging, I've been able to identify the root cause. This one was subtle -- it will happen under any vendor/version (not MariaDB-specific) under a very specific set of conditions:

* Running Skeema with a non-root user lacking privileges to query the `mysql.proc` table (or, alternatively, using MySQL 8.0 where `mysql.proc` does not exist)
AND
* The procedure was defined using formatting that contains newlines before, between, or after the procedure's parameter list

Basically, Skeema first tries to bulk-query `mysql.proc` to introspect routines as efficiently as possible. But if that query fails (lack of access or lack of that table existing), the error is silently ignored, since as a fallback Skeema runs a bunch of separate `SHOW CREATE PROCEDURE` queries instead. In that fallback case, it has to parse the result using a regular expression, but that expression is not correctly accounting for the possibility of newlines inside the arg list.

I should have a fix in master by the end of the week, and a patch release sometime next week. If you need a faster work-around, I believe running Skeema as root (or at least as a user with privs to query `mysql.proc`) should do the trick, and perform better as well if you have a high number of procs.

Sorry for the bug, and thank you again for the report!

**Comment by obissick** [comment]
No worries! i can wait until you release the patch. Thanks for your quick response to this issue.

**Comment by obissick** [comment]
also will there be any support for partitions?

**Comment by evanelias** [comment]
Diff'ing partitioned tables would be time-consuming to implement; see notes in #57. Since partitioned tables are primarily only used by larger/established companies, I'd probably only proceed with that (in open source) if a company wants to sponsor the necessary development work. Otherwise, I may save it for a commercial/enterprise version of Skeema, if I ever go that route in the future.

**Comment by evanelias** [comment]
I've just released [Skeema v1.2.6](https://github.com/skeema/skeema/releases/tag/v1.2.6) containing this fix. Thanks again for the bug report!

**Comment by evanelias** [comment]
@obissick just to follow up re: your last question on partitioning, [Skeema v1.4.0](https://github.com/skeema/skeema/releases/tag/v1.4.0) now contains support for partitioned tables.
