### ISSUE TITLE
Struggling to import procedures 

### ISSUE THREAD

**Issue by kaihendry** [skeema/skeema#96]
Hi, I'm trying to manage the schema of an AWS Aurora mysql compatible database, and on init using `skeema version 1.2.6-dev (snapshot build from source)` it seems unable to grok our procedures. We make extensive use of procedures because of [lambda triggers](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Lambda.html).

* https://github.com/unee-t/skeema-experiment/blob/master/init.log

And then somewhat surprisingly after init-ing and changing nothing, a `skeema diff` wants to delete several procedures.

* https://github.com/unee-t/skeema-experiment/blob/master/diff.log

How can I help you better support our database?

**Comment by evanelias** [comment]
Thank you for trying out Skeema and for the bug report!

To investigate this, I'd like to review the contents of some of the procs that are failing. Can you please send the output of these queries, executed manually using the same user as you ran Skeema with?

```sql
SHOW CREATE PROCEDURE bugzilla.remove_user_from_default_cc\G
SHOW CREATE PROCEDURE unee_t_enterprise.ut_bulk_assign_units_to_a_user\G
SELECT name, type, body, param_list, returns FROM mysql.proc WHERE db = 'bugzilla' AND name = 'remove_user_from_default_cc'\G
SELECT name, type, body, param_list, returns FROM mysql.proc WHERE db = 'unee_t_enterprise' AND name = 'ut_bulk_assign_units_to_a_user'\G
```

I'm not sure if `mysql.proc` is exposed in Aurora, so it's possible those last two will fail.

If you're not able to post these publicly, please e-mail the support address listed on https://github.com/skeema. Thanks!

**Comment by kaihendry** [comment]
Thanks! Here goes: https://media.dev.unee-t.com/2019-08-31/add-to-bug.txt

I think my collegue maintains the schema here: https://github.com/unee-t/bz-database/

**Comment by evanelias** [comment]
Thank you. Unfortunately I'm not able to reproduce the problem on normal MySQL 5.7, even when using your same client charset, collation, sql_mode, etc. I don't have an Aurora cluster to test against though.

Even so, my guess would be it somehow relates to use of the utf8mb4_unicode_520_ci collation, but I'm not certain. That collation is fairly rare as-is; combined with Aurora and huge procs (that 2nd one is nearly 3000 lines long...), that's quite an extreme combination of edge cases.

Anyway, I've added a commit to Skeema's master branch that provides slightly more information in this situation. If you could please upgrade (e.g. `go get -u github.com/skeema/skeema`) and run the `skeema init` again fresh, I'd be very curious to see the error output this time. Thanks!

**Comment by kaihendry** [comment]
He's the output, doesn't get very far!

https://media.dev.unee-t.com/2019-08-31/1-3.txt

**Comment by evanelias** [comment]
Awesome, thank you, that revealed a Skeema bug: the parser is failing on lines with completely empty comments, e.g. "#\n", due to a bug in a regular expression. I've just put a new commit in master which solves that problem. Hopefully that's the cause of the other failures as well, but fingers crossed!

I believe I wasn't able to reproduce this yesterday using the definitions in https://media.dev.unee-t.com/2019-08-31/add-to-bug.txt because many of the lines in that file seem to have extra whitespace appended to the ends, so there's no case of a # *immediately* followed by a newline. Checking the original definitions in the source repo though, the extra whitespace isn't present there, so I'm guessing this was a terminal output problem or somehow introduced via cut-and-paste.

Anyway, after upgrading and starting fresh again, please let me know if `skeema init` hits any other errors. Thanks again!

**Comment by kaihendry** [comment]
Appears to be working as I expected! Thank you for great support.
https://media.dev.unee-t.com/2019-09-01/working.txt

I guess there is no way to avoid unsafe operations when updating a procedure?

**Comment by evanelias** [comment]
Excellent, glad to hear that solved it!

> I guess there is no way to avoid unsafe operations when updating a procedure?

Correct; Skeema considers this unsafe because there's no way to modify the body of a procedure in-place in MySQL. Instead the proc needs to be dropped and recreated, and in theory it's possible that an application could try to call the proc during the split-second that it doesn't exist, resulting in an application-facing error. So `--allow-unsafe` is required as a safety mechanism, to bring attention to the fact that the operation carries some risk.

There's been some previous discussion of making allow-unsafe more granular in #51, and I could envision this being useful e.g. to permit proc replacements but not destructive table changes. Happy to get more input on that issue if this seems like it could be beneficial for your use-case.
